// Generated by Claude (claude.ai) | Date: 2026-05-18 | Model: claude-sonnet-4-6
// Re-generation prompt: Task 10 of awsext provider plan

package provider

import (
	"context"
	"errors"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/appintegrations"
	appintegrationstypes "github.com/aws/aws-sdk-go-v2/service/appintegrations/types"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var _ resource.Resource = &AppIntegrationsApplicationResource{}
var _ resource.ResourceWithImportState = &AppIntegrationsApplicationResource{}

func NewAppIntegrationsApplicationResource() resource.Resource {
	return &AppIntegrationsApplicationResource{}
}

type AppIntegrationsApplicationResource struct{ config aws.Config }

// -------------------------------------------------------------------
// Model types
// -------------------------------------------------------------------

type AppIntegrationsApplicationResourceModel struct {
	ApplicationId          types.String                          `tfsdk:"application_id"`
	ApplicationArn         types.String                          `tfsdk:"application_arn"`
	Name                   types.String                          `tfsdk:"name"`
	Namespace              types.String                          `tfsdk:"namespace"`
	Description            types.String                          `tfsdk:"description"`
	ApplicationType        types.String                          `tfsdk:"application_type"`
	ApplicationSourceConfig *AppIntegrationsSourceConfigModel    `tfsdk:"application_source_config"`
	Permissions            types.List                            `tfsdk:"permissions"`
	Publications           []AppIntegrationsPublicationModel     `tfsdk:"publications"`
	Subscriptions          []AppIntegrationsSubscriptionModel    `tfsdk:"subscriptions"`
	InitializationTimeout  types.Int64                           `tfsdk:"initialization_timeout"`
	IframeConfig           *AppIntegrationsIframeConfigModel     `tfsdk:"iframe_config"`
	Tags                   types.Map                             `tfsdk:"tags"`
}

type AppIntegrationsSourceConfigModel struct {
	ExternalUrlConfig AppIntegrationsExternalUrlConfigModel `tfsdk:"external_url_config"`
}

type AppIntegrationsExternalUrlConfigModel struct {
	AccessUrl       types.String `tfsdk:"access_url"`
	ApprovedOrigins types.List   `tfsdk:"approved_origins"`
}

type AppIntegrationsPublicationModel struct {
	Event       types.String `tfsdk:"event"`
	Schema      types.String `tfsdk:"schema"`
	Description types.String `tfsdk:"description"`
}

type AppIntegrationsSubscriptionModel struct {
	Event       types.String `tfsdk:"event"`
	Description types.String `tfsdk:"description"`
}

type AppIntegrationsIframeConfigModel struct {
	Allow   types.List `tfsdk:"allow"`
	Sandbox types.List `tfsdk:"sandbox"`
}

// -------------------------------------------------------------------
// Metadata / Schema
// -------------------------------------------------------------------

func (r *AppIntegrationsApplicationResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_appintegrations_application"
}

func (r *AppIntegrationsApplicationResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Creates and manages an Amazon AppIntegrations Application " +
			"(appintegrations:CreateApplication / GetApplication / UpdateApplication / DeleteApplication). " +
			"Used to register AgentCore gateway MCP servers as Connect workspace applications.",

		Attributes: map[string]schema.Attribute{
			"application_id": schema.StringAttribute{
				Computed:    true,
				Description: "Service-assigned unique identifier for the Application.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"application_arn": schema.StringAttribute{
				Computed:    true,
				Description: "Amazon Resource Name (ARN) of the Application.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "The name of the application. Updatable in place.",
			},
			"namespace": schema.StringAttribute{
				Required:    true,
				Description: "The namespace of the application. Must match the AgentCore gateway ID. Forces replacement.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"description": schema.StringAttribute{
				Optional:    true,
				Description: "Description of the application. Updatable in place.",
			},
			"application_type": schema.StringAttribute{
				Optional:    true,
				Description: "The type of application. Use `MCP_SERVER` for AgentCore gateway integrations. Forces replacement.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.OneOf("STANDARD", "SERVICE", "MCP_SERVER"),
				},
			},
			"application_source_config": schema.SingleNestedAttribute{
				Required:    true,
				Description: "Configuration for where the application should be loaded from. Forces replacement.",
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.RequiresReplace(),
				},
				Attributes: map[string]schema.Attribute{
					"external_url_config": schema.SingleNestedAttribute{
						Required:    true,
						Description: "External URL configuration for the application.",
						Attributes: map[string]schema.Attribute{
							"access_url": schema.StringAttribute{
								Required:    true,
								Description: "The URL used to access the application.",
							},
							"approved_origins": schema.ListAttribute{
								Optional:    true,
								ElementType: types.StringType,
								Description: "Additional approved origin URLs for the application.",
							},
						},
					},
				},
			},
			"permissions": schema.ListAttribute{
				Optional:    true,
				ElementType: types.StringType,
				Description: "Configuration of events or requests that the application has access to. Updatable in place.",
			},
			"publications": schema.ListNestedAttribute{
				Optional:    true,
				Description: "Events that the application publishes. Forces replacement. Deprecated by AWS in favor of permissions.",
				PlanModifiers: []planmodifier.List{
					listplanmodifier.RequiresReplace(),
				},
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"event": schema.StringAttribute{
							Required:    true,
							Description: "The name of the publication event.",
						},
						"schema": schema.StringAttribute{
							Required:    true,
							Description: "The JSON schema of the publication event.",
						},
						"description": schema.StringAttribute{
							Optional:    true,
							Description: "Description of the publication.",
						},
					},
				},
			},
			"subscriptions": schema.ListNestedAttribute{
				Optional:    true,
				Description: "Events that the application subscribes to. Forces replacement. Deprecated by AWS in favor of permissions.",
				PlanModifiers: []planmodifier.List{
					listplanmodifier.RequiresReplace(),
				},
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"event": schema.StringAttribute{
							Required:    true,
							Description: "The name of the subscription event.",
						},
						"description": schema.StringAttribute{
							Optional:    true,
							Description: "Description of the subscription.",
						},
					},
				},
			},
			"initialization_timeout": schema.Int64Attribute{
				Optional:    true,
				Description: "Maximum time in milliseconds allowed to establish a connection with the workspace. Updatable in place.",
			},
			"iframe_config": schema.SingleNestedAttribute{
				Optional:    true,
				Description: "Iframe configuration for the application. Updatable in place.",
				Attributes: map[string]schema.Attribute{
					"allow": schema.ListAttribute{
						Optional:    true,
						ElementType: types.StringType,
						Description: "List of features allowed in the iframe.",
					},
					"sandbox": schema.ListAttribute{
						Optional:    true,
						ElementType: types.StringType,
						Description: "List of sandbox attributes for the iframe.",
					},
				},
			},
			"tags": schema.MapAttribute{
				Optional:    true,
				Computed:    true,
				ElementType: types.StringType,
				Description: "Tags to assign to the application.",
			},
		},
	}
}

// -------------------------------------------------------------------
// Configure
// -------------------------------------------------------------------

func (r *AppIntegrationsApplicationResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	cfg, ok := req.ProviderData.(aws.Config)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *aws.Config, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.config = cfg
}

// -------------------------------------------------------------------
// Create
// -------------------------------------------------------------------

func (r *AppIntegrationsApplicationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data AppIntegrationsApplicationResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := appintegrations.NewFromConfig(r.config)

	// Build ApplicationSourceConfig
	srcConfig := &appintegrationstypes.ApplicationSourceConfig{
		ExternalUrlConfig: &appintegrationstypes.ExternalUrlConfig{
			AccessUrl: aws.String(data.ApplicationSourceConfig.ExternalUrlConfig.AccessUrl.ValueString()),
		},
	}
	if !data.ApplicationSourceConfig.ExternalUrlConfig.ApprovedOrigins.IsNull() &&
		!data.ApplicationSourceConfig.ExternalUrlConfig.ApprovedOrigins.IsUnknown() {
		var origins []string
		data.ApplicationSourceConfig.ExternalUrlConfig.ApprovedOrigins.ElementsAs(ctx, &origins, false)
		srcConfig.ExternalUrlConfig.ApprovedOrigins = origins
	}

	in := &appintegrations.CreateApplicationInput{
		Name:                    aws.String(data.Name.ValueString()),
		Namespace:               aws.String(data.Namespace.ValueString()),
		ApplicationSourceConfig: srcConfig,
	}

	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		in.Description = aws.String(data.Description.ValueString())
	}
	if !data.ApplicationType.IsNull() && !data.ApplicationType.IsUnknown() {
		in.ApplicationType = appintegrationstypes.ApplicationType(data.ApplicationType.ValueString())
	}
	if !data.Permissions.IsNull() && !data.Permissions.IsUnknown() {
		var perms []string
		data.Permissions.ElementsAs(ctx, &perms, false)
		in.Permissions = perms
	}
	if !data.InitializationTimeout.IsNull() && !data.InitializationTimeout.IsUnknown() {
		v := int32(data.InitializationTimeout.ValueInt64())
		in.InitializationTimeout = &v
	}
	if data.IframeConfig != nil {
		ifc := &appintegrationstypes.IframeConfig{}
		if !data.IframeConfig.Allow.IsNull() && !data.IframeConfig.Allow.IsUnknown() {
			var allow []string
			data.IframeConfig.Allow.ElementsAs(ctx, &allow, false)
			ifc.Allow = allow
		}
		if !data.IframeConfig.Sandbox.IsNull() && !data.IframeConfig.Sandbox.IsUnknown() {
			var sandbox []string
			data.IframeConfig.Sandbox.ElementsAs(ctx, &sandbox, false)
			ifc.Sandbox = sandbox
		}
		in.IframeConfig = ifc
	}
	if len(data.Publications) > 0 {
		pubs := make([]appintegrationstypes.Publication, 0, len(data.Publications))
		for _, p := range data.Publications {
			pub := appintegrationstypes.Publication{
				Event:  aws.String(p.Event.ValueString()),
				Schema: aws.String(p.Schema.ValueString()),
			}
			if !p.Description.IsNull() && !p.Description.IsUnknown() {
				pub.Description = aws.String(p.Description.ValueString())
			}
			pubs = append(pubs, pub)
		}
		in.Publications = pubs
	}
	if len(data.Subscriptions) > 0 {
		subs := make([]appintegrationstypes.Subscription, 0, len(data.Subscriptions))
		for _, s := range data.Subscriptions {
			sub := appintegrationstypes.Subscription{
				Event: aws.String(s.Event.ValueString()),
			}
			if !s.Description.IsNull() && !s.Description.IsUnknown() {
				sub.Description = aws.String(s.Description.ValueString())
			}
			subs = append(subs, sub)
		}
		in.Subscriptions = subs
	}

	tagMap, err := appIntegrationsTagsFromMap(ctx, data.Tags)
	if err != nil {
		resp.Diagnostics.AddError("Error reading tags", err.Error())
		return
	}
	if tagMap != nil {
		in.Tags = tagMap
	}

	out, err := conn.CreateApplication(ctx, in)
	if err != nil {
		resp.Diagnostics.AddError("Error creating AppIntegrations Application", err.Error())
		return
	}

	tflog.Trace(ctx, "created appintegrations application")

	data.ApplicationId = types.StringValue(aws.ToString(out.Id))
	data.ApplicationArn = types.StringValue(aws.ToString(out.Arn))

	if tags, err := readAppIntegrationsTags(ctx, conn, data.ApplicationArn.ValueString()); err == nil {
		data.Tags = tags
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// -------------------------------------------------------------------
// Read
// -------------------------------------------------------------------

func (r *AppIntegrationsApplicationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data AppIntegrationsApplicationResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := appintegrations.NewFromConfig(r.config)

	out, err := conn.GetApplication(ctx, &appintegrations.GetApplicationInput{
		Arn: aws.String(data.ApplicationArn.ValueString()),
	})
	if err != nil {
		var nf *appintegrationstypes.ResourceNotFoundException
		if errors.As(err, &nf) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading AppIntegrations Application",
			fmt.Sprintf("Could not read Application %s: %s", data.ApplicationArn.ValueString(), err))
		return
	}
	if out == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	data.ApplicationId = types.StringValue(aws.ToString(out.Id))
	data.ApplicationArn = types.StringValue(aws.ToString(out.Arn))
	data.Name = types.StringValue(aws.ToString(out.Name))
	data.Namespace = types.StringValue(aws.ToString(out.Namespace))

	if out.Description != nil {
		data.Description = types.StringValue(aws.ToString(out.Description))
	} else {
		data.Description = types.StringNull()
	}

	if out.ApplicationType != "" {
		data.ApplicationType = types.StringValue(string(out.ApplicationType))
	} else {
		data.ApplicationType = types.StringNull()
	}

	// ApplicationSourceConfig
	if out.ApplicationSourceConfig != nil && out.ApplicationSourceConfig.ExternalUrlConfig != nil {
		euc := out.ApplicationSourceConfig.ExternalUrlConfig
		approvedOrigins := types.ListNull(types.StringType)
		if len(euc.ApprovedOrigins) > 0 {
			ao, diags := types.ListValueFrom(ctx, types.StringType, euc.ApprovedOrigins)
			if !diags.HasError() {
				approvedOrigins = ao
			}
		}
		data.ApplicationSourceConfig = &AppIntegrationsSourceConfigModel{
			ExternalUrlConfig: AppIntegrationsExternalUrlConfigModel{
				AccessUrl:       types.StringValue(aws.ToString(euc.AccessUrl)),
				ApprovedOrigins: approvedOrigins,
			},
		}
	}

	// Permissions
	if len(out.Permissions) > 0 {
		perms, diags := types.ListValueFrom(ctx, types.StringType, out.Permissions)
		if !diags.HasError() {
			data.Permissions = perms
		}
	} else {
		data.Permissions = types.ListNull(types.StringType)
	}

	// Publications
	if len(out.Publications) > 0 {
		pubs := make([]AppIntegrationsPublicationModel, 0, len(out.Publications))
		for _, p := range out.Publications {
			pm := AppIntegrationsPublicationModel{
				Event:  types.StringValue(aws.ToString(p.Event)),
				Schema: types.StringValue(aws.ToString(p.Schema)),
			}
			if p.Description != nil {
				pm.Description = types.StringValue(aws.ToString(p.Description))
			} else {
				pm.Description = types.StringNull()
			}
			pubs = append(pubs, pm)
		}
		data.Publications = pubs
	} else {
		data.Publications = nil
	}

	// Subscriptions
	if len(out.Subscriptions) > 0 {
		subs := make([]AppIntegrationsSubscriptionModel, 0, len(out.Subscriptions))
		for _, s := range out.Subscriptions {
			sm := AppIntegrationsSubscriptionModel{
				Event: types.StringValue(aws.ToString(s.Event)),
			}
			if s.Description != nil {
				sm.Description = types.StringValue(aws.ToString(s.Description))
			} else {
				sm.Description = types.StringNull()
			}
			subs = append(subs, sm)
		}
		data.Subscriptions = subs
	} else {
		data.Subscriptions = nil
	}

	// InitializationTimeout
	if out.InitializationTimeout != nil {
		data.InitializationTimeout = types.Int64Value(int64(*out.InitializationTimeout))
	} else {
		data.InitializationTimeout = types.Int64Null()
	}

	// IframeConfig
	if out.IframeConfig != nil {
		ifc := &AppIntegrationsIframeConfigModel{}
		if len(out.IframeConfig.Allow) > 0 {
			allow, diags := types.ListValueFrom(ctx, types.StringType, out.IframeConfig.Allow)
			if !diags.HasError() {
				ifc.Allow = allow
			}
		} else {
			ifc.Allow = types.ListNull(types.StringType)
		}
		if len(out.IframeConfig.Sandbox) > 0 {
			sandbox, diags := types.ListValueFrom(ctx, types.StringType, out.IframeConfig.Sandbox)
			if !diags.HasError() {
				ifc.Sandbox = sandbox
			}
		} else {
			ifc.Sandbox = types.ListNull(types.StringType)
		}
		data.IframeConfig = ifc
	} else {
		data.IframeConfig = nil
	}

	if tags, err := readAppIntegrationsTags(ctx, conn, data.ApplicationArn.ValueString()); err == nil {
		data.Tags = tags
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// -------------------------------------------------------------------
// Update
// -------------------------------------------------------------------

func (r *AppIntegrationsApplicationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state AppIntegrationsApplicationResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := appintegrations.NewFromConfig(r.config)

	in := &appintegrations.UpdateApplicationInput{
		Arn:  aws.String(state.ApplicationArn.ValueString()),
		Name: aws.String(plan.Name.ValueString()),
	}

	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		in.Description = aws.String(plan.Description.ValueString())
	}
	if !plan.Permissions.IsNull() && !plan.Permissions.IsUnknown() {
		var perms []string
		plan.Permissions.ElementsAs(ctx, &perms, false)
		in.Permissions = perms
	}
	if !plan.InitializationTimeout.IsNull() && !plan.InitializationTimeout.IsUnknown() {
		v := int32(plan.InitializationTimeout.ValueInt64())
		in.InitializationTimeout = &v
	}
	if plan.IframeConfig != nil {
		ifc := &appintegrationstypes.IframeConfig{}
		if !plan.IframeConfig.Allow.IsNull() && !plan.IframeConfig.Allow.IsUnknown() {
			var allow []string
			plan.IframeConfig.Allow.ElementsAs(ctx, &allow, false)
			ifc.Allow = allow
		}
		if !plan.IframeConfig.Sandbox.IsNull() && !plan.IframeConfig.Sandbox.IsUnknown() {
			var sandbox []string
			plan.IframeConfig.Sandbox.ElementsAs(ctx, &sandbox, false)
			ifc.Sandbox = sandbox
		}
		in.IframeConfig = ifc
	}

	_, err := conn.UpdateApplication(ctx, in)
	if err != nil {
		resp.Diagnostics.AddError("Error updating AppIntegrations Application",
			fmt.Sprintf("Could not update Application %s: %s", state.ApplicationArn.ValueString(), err))
		return
	}

	if err := updateAppIntegrationsTags(ctx, conn, state.ApplicationArn.ValueString(), state.Tags, plan.Tags); err != nil {
		resp.Diagnostics.AddError("Error updating AppIntegrations Application tags",
			fmt.Sprintf("Could not update tags for Application %s: %s", state.ApplicationArn.ValueString(), err))
		return
	}

	// Carry computed fields from state
	plan.ApplicationId = state.ApplicationId
	plan.ApplicationArn = state.ApplicationArn

	if tags, err := readAppIntegrationsTags(ctx, conn, state.ApplicationArn.ValueString()); err == nil {
		plan.Tags = tags
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// -------------------------------------------------------------------
// Delete
// -------------------------------------------------------------------

func (r *AppIntegrationsApplicationResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data AppIntegrationsApplicationResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := appintegrations.NewFromConfig(r.config)

	_, err := conn.DeleteApplication(ctx, &appintegrations.DeleteApplicationInput{
		Arn: aws.String(data.ApplicationArn.ValueString()),
	})
	if err != nil {
		var nf *appintegrationstypes.ResourceNotFoundException
		if errors.As(err, &nf) {
			return
		}
		resp.Diagnostics.AddError("Error deleting AppIntegrations Application",
			fmt.Sprintf("Could not delete Application %s: %s", data.ApplicationArn.ValueString(), err))
	}
}

// -------------------------------------------------------------------
// ImportState
// -------------------------------------------------------------------

// ImportState accepts the Application ARN as the import ID. The ARN is used
// directly for GetApplication; the ID is parsed from the read response.
//
// Import command:
//
//	terraform import awsext_appintegrations_application.example arn:aws:app-integrations:us-east-1:123456789012:application/<id>
func (r *AppIntegrationsApplicationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	if req.ID == "" {
		resp.Diagnostics.AddError(
			"Invalid import ID",
			"Import ID must be the Application ARN (arn:aws:app-integrations:...:application/<id>).",
		)
		return
	}
	// Store the ARN in application_arn; Read will populate all other fields including application_id.
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("application_arn"), req.ID)...)
}

// -------------------------------------------------------------------
// Inline tag helpers (appintegrations-scoped)
// -------------------------------------------------------------------

func readAppIntegrationsTags(ctx context.Context, conn *appintegrations.Client, arn string) (types.Map, error) {
	out, err := conn.ListTagsForResource(ctx, &appintegrations.ListTagsForResourceInput{
		ResourceArn: aws.String(arn),
	})
	if err != nil {
		return types.MapNull(types.StringType), err
	}
	result, diags := types.MapValueFrom(ctx, types.StringType, out.Tags)
	if diags.HasError() {
		return types.MapNull(types.StringType), fmt.Errorf("error converting appintegrations tags to map")
	}
	return result, nil
}

func updateAppIntegrationsTags(ctx context.Context, conn *appintegrations.Client, arn string, oldTags, newTags types.Map) error {
	var oldTagMap, newTagMap map[string]string

	if !oldTags.IsNull() && !oldTags.IsUnknown() {
		oldTags.ElementsAs(ctx, &oldTagMap, false)
	}
	if !newTags.IsNull() && !newTags.IsUnknown() {
		newTags.ElementsAs(ctx, &newTagMap, false)
	}

	var keysToDelete []string
	for k := range oldTagMap {
		if _, exists := newTagMap[k]; !exists {
			keysToDelete = append(keysToDelete, k)
		}
	}

	if len(keysToDelete) > 0 {
		if _, err := conn.UntagResource(ctx, &appintegrations.UntagResourceInput{
			ResourceArn: aws.String(arn),
			TagKeys:     keysToDelete,
		}); err != nil {
			return err
		}
	}

	if len(newTagMap) > 0 {
		if _, err := conn.TagResource(ctx, &appintegrations.TagResourceInput{
			ResourceArn: aws.String(arn),
			Tags:        newTagMap,
		}); err != nil {
			return err
		}
	}

	return nil
}

func appIntegrationsTagsFromMap(ctx context.Context, tags types.Map) (map[string]string, error) {
	if tags.IsNull() || tags.IsUnknown() {
		return nil, nil
	}
	var tagMap map[string]string
	if diags := tags.ElementsAs(ctx, &tagMap, false); diags.HasError() {
		return nil, fmt.Errorf("error reading appintegrations tags")
	}
	return tagMap, nil
}
