// GENERATED FILE — DO NOT EDIT BY HAND
// Generated by: Claude (claude-fable-5)
// Skills: (none loaded)
// Generation date: 2026-07-20

package provider

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/appstream"
	appstreamtypes "github.com/aws/aws-sdk-go-v2/service/appstream/types"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var _ resource.Resource = &AppstreamImageCopyResource{}
var _ resource.ResourceWithImportState = &AppstreamImageCopyResource{}

const (
	appstreamImageCopyDefaultCreateTimeout = 30 * time.Minute
	appstreamImageCopyDefaultDeleteTimeout = 10 * time.Minute
)

func NewAppstreamImageCopyResource() resource.Resource {
	return &AppstreamImageCopyResource{}
}

type AppstreamImageCopyResource struct {
	config aws.Config
}

type AppstreamImageCopyResourceModel struct {
	Name                 types.String `tfsdk:"name"`
	Description          types.String `tfsdk:"description"`
	SourceImageName      types.String `tfsdk:"source_image_name"`
	SourceRegion         types.String `tfsdk:"source_region"`
	Arn                  types.String `tfsdk:"arn"`
	State                types.String `tfsdk:"state"`
	Tags                 types.Map    `tfsdk:"tags"`
	CreateTimeoutMinutes types.Int64  `tfsdk:"create_timeout_minutes"`
	DeleteTimeoutMinutes types.Int64  `tfsdk:"delete_timeout_minutes"`
}

func (r *AppstreamImageCopyResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_appstream_image_copy"
}

func (r *AppstreamImageCopyResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Copies an AppStream image from a source region into the provider's region via CopyImage. " +
			"Only images owned by the account can be copied (not images merely shared with it). " +
			"Create waits until the destination image reaches AVAILABLE before returning. " +
			"Import using the destination image name.",

		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Required:    true,
				Description: "The name for the copied image in the destination (provider) region.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"description": schema.StringAttribute{
				Optional:    true,
				Description: "A description for the copied image.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"source_image_name": schema.StringAttribute{
				Required:    true,
				Description: "The name of the source image to copy. The image must be owned by this account.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"source_region": schema.StringAttribute{
				Required:    true,
				Description: "The AWS Region identifier where the source image resides.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"arn": schema.StringAttribute{
				Computed:    true,
				Description: "The ARN of the copied image in the destination region.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"state": schema.StringAttribute{
				Computed:    true,
				Description: "The state of the image (PENDING, AVAILABLE, FAILED, COPYING, DELETING, CREATING, IMPORTING, VALIDATING).",
			},
			"tags": schema.MapAttribute{
				Optional:    true,
				ElementType: types.StringType,
				Description: "Tags to assign to the copied image.",
			},
			"create_timeout_minutes": schema.Int64Attribute{
				Optional:    true,
				Description: "How long to wait for the copied image to reach AVAILABLE, in minutes. Defaults to 30.",
			},
			"delete_timeout_minutes": schema.Int64Attribute{
				Optional:    true,
				Description: "How long to retry deletion while the image is still in use, in minutes. Defaults to 10.",
			},
		},
	}
}

func (r *AppstreamImageCopyResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	config, ok := req.ProviderData.(aws.Config)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *aws.Config, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.config = config
}

func (r *AppstreamImageCopyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data AppstreamImageCopyResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	destinationRegion := r.config.Region
	if destinationRegion == "" {
		resp.Diagnostics.AddError("Missing destination region",
			"The provider region must be set; it is used as the destination region for the image copy.")
		return
	}

	// CopyImage is issued against the SOURCE region and pushes to DestinationRegion.
	sourceConn := appstream.NewFromConfig(r.config, func(o *appstream.Options) {
		o.Region = data.SourceRegion.ValueString()
	})

	input := &appstream.CopyImageInput{
		SourceImageName:      aws.String(data.SourceImageName.ValueString()),
		DestinationImageName: aws.String(data.Name.ValueString()),
		DestinationRegion:    aws.String(destinationRegion),
	}

	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		input.DestinationImageDescription = aws.String(data.Description.ValueString())
	}

	_, err := sourceConn.CopyImage(ctx, input)

	if err != nil {
		resp.Diagnostics.AddError("Error copying AppStream image",
			fmt.Sprintf("Could not copy AppStream image %s from region %s, unexpected error: %s",
				data.SourceImageName.ValueString(), data.SourceRegion.ValueString(), err))
		return
	}

	tflog.Trace(ctx, "started appstream image copy")

	conn := appstream.NewFromConfig(r.config)

	timeout := appstreamImageCopyDefaultCreateTimeout
	if !data.CreateTimeoutMinutes.IsNull() && !data.CreateTimeoutMinutes.IsUnknown() {
		timeout = time.Duration(data.CreateTimeoutMinutes.ValueInt64()) * time.Minute
	}

	img, err := waitForAppstreamImageAvailable(ctx, conn, data.Name.ValueString(), timeout)
	if err != nil {
		resp.Diagnostics.AddError("Error waiting for AppStream image copy",
			fmt.Sprintf("Image %s did not become AVAILABLE: %s", data.Name.ValueString(), err))
		return
	}

	data.Arn = types.StringValue(aws.ToString(img.Arn))
	data.State = types.StringValue(string(img.State))

	if !data.Tags.IsNull() && !data.Tags.IsUnknown() {
		var tagMap map[string]string
		resp.Diagnostics.Append(data.Tags.ElementsAs(ctx, &tagMap, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		if len(tagMap) > 0 {
			if _, err := conn.TagResource(ctx, &appstream.TagResourceInput{
				ResourceArn: img.Arn,
				Tags:        tagMap,
			}); err != nil {
				resp.Diagnostics.AddError("Error tagging AppStream image",
					fmt.Sprintf("Could not tag AppStream image %s, unexpected error: %s", data.Name.ValueString(), err))
				return
			}
		}
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AppstreamImageCopyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data AppstreamImageCopyResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := appstream.NewFromConfig(r.config)

	output, err := conn.DescribeImages(ctx, &appstream.DescribeImagesInput{
		Names: []string{data.Name.ValueString()},
	})

	if err != nil {
		var notFound *appstreamtypes.ResourceNotFoundException
		if errors.As(err, &notFound) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading AppStream image copy",
			fmt.Sprintf("Could not read AppStream image %s, unexpected error: %s", data.Name.ValueString(), err))
		return
	}

	if len(output.Images) == 0 {
		resp.State.RemoveResource(ctx)
		return
	}

	img := output.Images[0]
	data.Name = types.StringValue(aws.ToString(img.Name))
	if img.Description != nil {
		data.Description = types.StringValue(*img.Description)
	} else {
		data.Description = types.StringNull()
	}
	data.Arn = types.StringValue(aws.ToString(img.Arn))
	data.State = types.StringValue(string(img.State))

	if tagsOutput, err := conn.ListTagsForResource(ctx, &appstream.ListTagsForResourceInput{
		ResourceArn: img.Arn,
	}); err == nil && len(tagsOutput.Tags) > 0 {
		tags, diags := types.MapValueFrom(ctx, types.StringType, tagsOutput.Tags)
		if !diags.HasError() {
			data.Tags = tags
		}
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AppstreamImageCopyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state AppstreamImageCopyResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := appstream.NewFromConfig(r.config)

	var oldTagMap, newTagMap map[string]string
	if !state.Tags.IsNull() && !state.Tags.IsUnknown() {
		state.Tags.ElementsAs(ctx, &oldTagMap, false)
	}
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		plan.Tags.ElementsAs(ctx, &newTagMap, false)
	}

	var keysToDelete []string
	for k := range oldTagMap {
		if _, exists := newTagMap[k]; !exists {
			keysToDelete = append(keysToDelete, k)
		}
	}

	if len(keysToDelete) > 0 {
		if _, err := conn.UntagResource(ctx, &appstream.UntagResourceInput{
			ResourceArn: aws.String(state.Arn.ValueString()),
			TagKeys:     keysToDelete,
		}); err != nil {
			resp.Diagnostics.AddError("Error updating AppStream image tags",
				fmt.Sprintf("Could not remove tags for AppStream image %s, unexpected error: %s", state.Name.ValueString(), err))
			return
		}
	}

	if len(newTagMap) > 0 {
		if _, err := conn.TagResource(ctx, &appstream.TagResourceInput{
			ResourceArn: aws.String(state.Arn.ValueString()),
			Tags:        newTagMap,
		}); err != nil {
			resp.Diagnostics.AddError("Error updating AppStream image tags",
				fmt.Sprintf("Could not update tags for AppStream image %s, unexpected error: %s", state.Name.ValueString(), err))
			return
		}
	}

	plan.Arn = state.Arn
	plan.State = state.State

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *AppstreamImageCopyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data AppstreamImageCopyResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := appstream.NewFromConfig(r.config)

	timeout := appstreamImageCopyDefaultDeleteTimeout
	if !data.DeleteTimeoutMinutes.IsNull() && !data.DeleteTimeoutMinutes.IsUnknown() {
		timeout = time.Duration(data.DeleteTimeoutMinutes.ValueInt64()) * time.Minute
	}

	// Deletes can fail with ResourceInUseException while AWS asynchronously
	// releases fleet/image-builder associations; retry with backoff.
	deadline := time.Now().Add(timeout)
	backoff := 15 * time.Second

	for {
		_, err := conn.DeleteImage(ctx, &appstream.DeleteImageInput{
			Name: aws.String(data.Name.ValueString()),
		})

		if err == nil {
			return
		}

		var notFound *appstreamtypes.ResourceNotFoundException
		if errors.As(err, &notFound) {
			return
		}

		var inUse *appstreamtypes.ResourceInUseException
		if !errors.As(err, &inUse) || time.Now().After(deadline) {
			resp.Diagnostics.AddError("Error deleting AppStream image copy",
				fmt.Sprintf("Could not delete AppStream image %s, unexpected error: %s", data.Name.ValueString(), err))
			return
		}

		tflog.Trace(ctx, fmt.Sprintf("appstream image %s still in use, retrying delete in %s", data.Name.ValueString(), backoff))

		select {
		case <-ctx.Done():
			resp.Diagnostics.AddError("Error deleting AppStream image copy",
				fmt.Sprintf("Context cancelled while deleting AppStream image %s: %s", data.Name.ValueString(), ctx.Err()))
			return
		case <-time.After(backoff):
		}

		if backoff < time.Minute {
			backoff *= 2
		}
	}
}

func (r *AppstreamImageCopyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}

// waitForAppstreamImageAvailable polls DescribeImages until the image reaches
// AVAILABLE, failing fast on FAILED or DELETING.
func waitForAppstreamImageAvailable(ctx context.Context, conn *appstream.Client, name string, timeout time.Duration) (*appstreamtypes.Image, error) {
	deadline := time.Now().Add(timeout)

	for {
		output, err := conn.DescribeImages(ctx, &appstream.DescribeImagesInput{
			Names: []string{name},
		})

		if err != nil {
			var notFound *appstreamtypes.ResourceNotFoundException
			if !errors.As(err, &notFound) {
				return nil, err
			}
			// The destination image may not be visible immediately after CopyImage; keep polling.
		} else if len(output.Images) > 0 {
			img := output.Images[0]
			switch img.State {
			case appstreamtypes.ImageStateAvailable:
				return &img, nil
			case appstreamtypes.ImageStateFailed, appstreamtypes.ImageStateDeleting:
				reason := ""
				if img.StateChangeReason != nil {
					reason = aws.ToString(img.StateChangeReason.Message)
				}
				return nil, fmt.Errorf("image entered state %s: %s", img.State, reason)
			}
		}

		if time.Now().After(deadline) {
			return nil, fmt.Errorf("timeout after %s waiting for image %s to become AVAILABLE", timeout, name)
		}

		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-time.After(30 * time.Second):
		}
	}
}
