// =============================================================================
// GENERATED FILE — DO NOT EDIT BY HAND
// Generated by: Claude (claude-fable-5)
// Skills: usan-code v1.1.0.719339
// Generation date: 2026-07-21
// =============================================================================

package provider

import "testing"

func TestParseImagePermissionImportID(t *testing.T) {
	tests := []struct {
		name        string
		id          string
		wantImage   string
		wantAccount string
		wantErr     bool
	}{
		{name: "valid", id: "workbench-test/733153951967", wantImage: "workbench-test", wantAccount: "733153951967"},
		{name: "image name containing slash keeps split at first slash only", id: "a/b/c", wantImage: "a", wantAccount: "b/c"},
		{name: "missing separator", id: "workbench-test", wantErr: true},
		{name: "empty image name", id: "/733153951967", wantErr: true},
		{name: "empty account id", id: "workbench-test/", wantErr: true},
		{name: "empty string", id: "", wantErr: true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			image, account, err := parseImagePermissionImportID(tt.id)
			if tt.wantErr {
				if err == nil {
					t.Fatalf("expected error for %q", tt.id)
				}
				return
			}
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if image != tt.wantImage || account != tt.wantAccount {
				t.Fatalf("got (%q, %q), want (%q, %q)", image, account, tt.wantImage, tt.wantAccount)
			}
		})
	}
}
