// =============================================================================
// GENERATED FILE — DO NOT EDIT BY HAND
// Generated by: Claude (claude-fable-5)
// Skills: usan-code v1.1.0.719339
// Generation date: 2026-07-21
// =============================================================================

package provider

import (
	"context"
	"errors"
	"strings"
	"testing"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/appstream"
	appstreamtypes "github.com/aws/aws-sdk-go-v2/service/appstream/types"
)

const testPollInterval = time.Millisecond

// fakeImageDescriber returns one scripted response per DescribeImages call,
// repeating the final response once the script is exhausted.
type fakeImageDescriber struct {
	responses []describeImagesResponse
	calls     int
}

type describeImagesResponse struct {
	output *appstream.DescribeImagesOutput
	err    error
}

func (f *fakeImageDescriber) DescribeImages(_ context.Context, _ *appstream.DescribeImagesInput, _ ...func(*appstream.Options)) (*appstream.DescribeImagesOutput, error) {
	idx := f.calls
	if idx >= len(f.responses) {
		idx = len(f.responses) - 1
	}
	f.calls++
	return f.responses[idx].output, f.responses[idx].err
}

func imageInState(state appstreamtypes.ImageState) *appstream.DescribeImagesOutput {
	return &appstream.DescribeImagesOutput{
		Images: []appstreamtypes.Image{
			{
				Name:  aws.String("test-image"),
				Arn:   aws.String("arn:aws:appstream:us-west-2:000000000000:image/test-image"),
				State: state,
			},
		},
	}
}

func TestWaitForAppstreamImageAvailable_ReturnsImageWhenAvailable(t *testing.T) {
	fake := &fakeImageDescriber{responses: []describeImagesResponse{
		{output: imageInState(appstreamtypes.ImageStateAvailable)},
	}}

	img, err := waitForAppstreamImageAvailable(context.Background(), fake, "test-image", time.Second, testPollInterval)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if img.State != appstreamtypes.ImageStateAvailable {
		t.Fatalf("got state %s, want AVAILABLE", img.State)
	}
}

func TestWaitForAppstreamImageAvailable_PollsThroughPending(t *testing.T) {
	fake := &fakeImageDescriber{responses: []describeImagesResponse{
		{output: imageInState(appstreamtypes.ImageStatePending)},
		{output: imageInState(appstreamtypes.ImageStateCopying)},
		{output: imageInState(appstreamtypes.ImageStateAvailable)},
	}}

	img, err := waitForAppstreamImageAvailable(context.Background(), fake, "test-image", time.Second, testPollInterval)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if img.State != appstreamtypes.ImageStateAvailable {
		t.Fatalf("got state %s, want AVAILABLE", img.State)
	}
	if fake.calls != 3 {
		t.Fatalf("got %d DescribeImages calls, want 3", fake.calls)
	}
}

func TestWaitForAppstreamImageAvailable_PollsThroughNotFound(t *testing.T) {
	fake := &fakeImageDescriber{responses: []describeImagesResponse{
		{err: &appstreamtypes.ResourceNotFoundException{}},
		{output: imageInState(appstreamtypes.ImageStateAvailable)},
	}}

	_, err := waitForAppstreamImageAvailable(context.Background(), fake, "test-image", time.Second, testPollInterval)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestWaitForAppstreamImageAvailable_FailsFastOnFailedState(t *testing.T) {
	failed := imageInState(appstreamtypes.ImageStateFailed)
	failed.Images[0].StateChangeReason = &appstreamtypes.ImageStateChangeReason{
		Message: aws.String("internal error"),
	}
	fake := &fakeImageDescriber{responses: []describeImagesResponse{{output: failed}}}

	_, err := waitForAppstreamImageAvailable(context.Background(), fake, "test-image", time.Second, testPollInterval)
	if err == nil {
		t.Fatal("expected error for FAILED state")
	}
	if !strings.Contains(err.Error(), "FAILED") || !strings.Contains(err.Error(), "internal error") {
		t.Fatalf("error should name the state and reason, got: %v", err)
	}
	if fake.calls != 1 {
		t.Fatalf("got %d DescribeImages calls, want 1 (fail fast)", fake.calls)
	}
}

func TestWaitForAppstreamImageAvailable_ReturnsAPIError(t *testing.T) {
	apiErr := errors.New("access denied")
	fake := &fakeImageDescriber{responses: []describeImagesResponse{{err: apiErr}}}

	_, err := waitForAppstreamImageAvailable(context.Background(), fake, "test-image", time.Second, testPollInterval)
	if !errors.Is(err, apiErr) {
		t.Fatalf("expected the API error to propagate, got: %v", err)
	}
}

func TestWaitForAppstreamImageAvailable_TimesOut(t *testing.T) {
	fake := &fakeImageDescriber{responses: []describeImagesResponse{
		{output: imageInState(appstreamtypes.ImageStatePending)},
	}}

	_, err := waitForAppstreamImageAvailable(context.Background(), fake, "test-image", 5*time.Millisecond, testPollInterval)
	if err == nil {
		t.Fatal("expected timeout error")
	}
	if !strings.Contains(err.Error(), "timeout") {
		t.Fatalf("expected timeout error, got: %v", err)
	}
}

func TestWaitForAppstreamImageAvailable_HonorsContextCancellation(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	fake := &fakeImageDescriber{responses: []describeImagesResponse{
		{output: imageInState(appstreamtypes.ImageStatePending)},
	}}

	_, err := waitForAppstreamImageAvailable(ctx, fake, "test-image", time.Second, testPollInterval)
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("expected context.Canceled, got: %v", err)
	}
}
