// =============================================================================
// GENERATED FILE — DO NOT EDIT BY HAND
// Generated by: Claude (claude-fable-5)
// Skills: usan-code v1.1.0.719339
// Generation date: 2026-07-21
// =============================================================================

package provider

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/appstream"
	appstreamtypes "github.com/aws/aws-sdk-go-v2/service/appstream/types"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var _ resource.Resource = &AppstreamImagePermissionResource{}
var _ resource.ResourceWithImportState = &AppstreamImagePermissionResource{}

// NewAppstreamImagePermissionResource returns the
// awsext_appstream_image_permission resource implementation.
func NewAppstreamImagePermissionResource() resource.Resource {
	return &AppstreamImagePermissionResource{}
}

// AppstreamImagePermissionResource manages the sharing permissions for one
// (image, account) pair via UpdateImagePermissions / DeleteImagePermissions.
type AppstreamImagePermissionResource struct {
	config aws.Config
}

// AppstreamImagePermissionResourceModel is the Terraform plan/state model for
// awsext_appstream_image_permission.
type AppstreamImagePermissionResourceModel struct {
	ImageName         types.String `tfsdk:"image_name"`
	SharedAccountID   types.String `tfsdk:"shared_account_id"`
	AllowFleet        types.Bool   `tfsdk:"allow_fleet"`
	AllowImageBuilder types.Bool   `tfsdk:"allow_image_builder"`
}

// Metadata sets the full resource type name.
func (r *AppstreamImagePermissionResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_appstream_image_permission"
}

// Schema defines the resource attributes.
func (r *AppstreamImagePermissionResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Shares a private AppStream image with another AWS account via UpdateImagePermissions. " +
			"One instance manages the permissions for one (image, account) pair. " +
			"Destroying this resource revokes the sharing permission. " +
			"Import using the format: image_name/shared_account_id.",

		Attributes: map[string]schema.Attribute{
			"image_name": schema.StringAttribute{
				Required:    true,
				Description: "The name of the private AppStream image to share. AppStream keys image permissions by name, not ID.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"shared_account_id": schema.StringAttribute{
				Required:    true,
				Description: "The 12-digit AWS account ID to share the image with.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"allow_fleet": schema.BoolAttribute{
				Required:    true,
				Description: "Whether the shared account can use the image for a fleet.",
			},
			"allow_image_builder": schema.BoolAttribute{
				Required:    true,
				Description: "Whether the shared account can use the image for an image builder.",
			},
		},
	}
}

// Configure stores the provider-level AWS configuration on the resource.
func (r *AppstreamImagePermissionResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	config, ok := req.ProviderData.(aws.Config)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *aws.Config, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.config = config
}

// Create grants the image permissions for the shared account.
func (r *AppstreamImagePermissionResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data AppstreamImagePermissionResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if err := r.updatePermissions(ctx, &data); err != nil {
		resp.Diagnostics.AddError("Error sharing AppStream image",
			fmt.Sprintf("Could not share AppStream image %s with account %s, unexpected error: %s",
				data.ImageName.ValueString(), data.SharedAccountID.ValueString(), err))
		return
	}

	tflog.Trace(ctx, "shared appstream image")

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Read refreshes the permission flags from DescribeImagePermissions, removing
// the resource when the share no longer exists.
func (r *AppstreamImagePermissionResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data AppstreamImagePermissionResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := appstream.NewFromConfig(r.config)

	var found *appstreamtypes.SharedImagePermissions
	var nextToken *string

	for {
		output, err := conn.DescribeImagePermissions(ctx, &appstream.DescribeImagePermissionsInput{
			Name:      aws.String(data.ImageName.ValueString()),
			NextToken: nextToken,
		})

		if err != nil {
			var notFound *appstreamtypes.ResourceNotFoundException
			if errors.As(err, &notFound) {
				resp.State.RemoveResource(ctx)
				return
			}
			resp.Diagnostics.AddError("Error reading AppStream image permissions",
				fmt.Sprintf("Could not read permissions for AppStream image %s, unexpected error: %s",
					data.ImageName.ValueString(), err))
			return
		}

		for _, perm := range output.SharedImagePermissionsList {
			if aws.ToString(perm.SharedAccountId) == data.SharedAccountID.ValueString() {
				perm := perm
				found = &perm
				break
			}
		}

		if found != nil || output.NextToken == nil {
			break
		}
		nextToken = output.NextToken
	}

	if found == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	data.AllowFleet = types.BoolValue(aws.ToBool(found.ImagePermissions.AllowFleet))
	data.AllowImageBuilder = types.BoolValue(aws.ToBool(found.ImagePermissions.AllowImageBuilder))

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Update reapplies the permission flags; UpdateImagePermissions upserts per
// (image, account), so flag changes apply in place.
func (r *AppstreamImagePermissionResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data AppstreamImagePermissionResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if err := r.updatePermissions(ctx, &data); err != nil {
		resp.Diagnostics.AddError("Error updating AppStream image permissions",
			fmt.Sprintf("Could not update permissions for AppStream image %s and account %s, unexpected error: %s",
				data.ImageName.ValueString(), data.SharedAccountID.ValueString(), err))
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Delete revokes the image permissions for the shared account.
func (r *AppstreamImagePermissionResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data AppstreamImagePermissionResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := appstream.NewFromConfig(r.config)

	_, err := conn.DeleteImagePermissions(ctx, &appstream.DeleteImagePermissionsInput{
		Name:            aws.String(data.ImageName.ValueString()),
		SharedAccountId: aws.String(data.SharedAccountID.ValueString()),
	})

	if err != nil {
		var notFound *appstreamtypes.ResourceNotFoundException
		if errors.As(err, &notFound) {
			return
		}
		resp.Diagnostics.AddError("Error revoking AppStream image permission",
			fmt.Sprintf("Could not revoke permission for AppStream image %s from account %s, unexpected error: %s",
				data.ImageName.ValueString(), data.SharedAccountID.ValueString(), err))
		return
	}
}

// ImportState imports an existing share using image_name/shared_account_id.
func (r *AppstreamImagePermissionResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	imageName, accountID, err := parseImagePermissionImportID(req.ID)
	if err != nil {
		resp.Diagnostics.AddError("Unexpected Import Identifier", err.Error())
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("image_name"), imageName)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("shared_account_id"), accountID)...)
}

// parseImagePermissionImportID splits an import identifier of the form
// image_name/shared_account_id into its two parts.
func parseImagePermissionImportID(id string) (string, string, error) {
	idParts := strings.SplitN(id, "/", 2)
	if len(idParts) != 2 || idParts[0] == "" || idParts[1] == "" {
		return "", "", fmt.Errorf("expected import identifier with format: image_name/shared_account_id, got: %q", id)
	}
	return idParts[0], idParts[1], nil
}

// updatePermissions issues the UpdateImagePermissions upsert for the model's
// (image, account) pair.
func (r *AppstreamImagePermissionResource) updatePermissions(ctx context.Context, data *AppstreamImagePermissionResourceModel) error {
	conn := appstream.NewFromConfig(r.config)

	_, err := conn.UpdateImagePermissions(ctx, &appstream.UpdateImagePermissionsInput{
		Name:            aws.String(data.ImageName.ValueString()),
		SharedAccountId: aws.String(data.SharedAccountID.ValueString()),
		ImagePermissions: &appstreamtypes.ImagePermissions{
			AllowFleet:        aws.Bool(data.AllowFleet.ValueBool()),
			AllowImageBuilder: aws.Bool(data.AllowImageBuilder.ValueBool()),
		},
	})

	return err
}
