// Generated by Claude (claude.ai) | Date: 2026-05-18 | Model: claude-sonnet-4-6
// Re-generation prompt: Task 11 of awsext provider plan

package provider

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/connect"
	conntypes "github.com/aws/aws-sdk-go-v2/service/connect/types"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var _ resource.Resource = &ConnectIntegrationAssociationResource{}
var _ resource.ResourceWithImportState = &ConnectIntegrationAssociationResource{}

func NewConnectIntegrationAssociationResource() resource.Resource {
	return &ConnectIntegrationAssociationResource{}
}

type ConnectIntegrationAssociationResource struct {
	config aws.Config
}

// -------------------------------------------------------------------
// Model
// -------------------------------------------------------------------

type ConnectIntegrationAssociationResourceModel struct {
	InstanceID                 types.String `tfsdk:"instance_id"`
	IntegrationType            types.String `tfsdk:"integration_type"`
	IntegrationArn             types.String `tfsdk:"integration_arn"`
	SourceApplicationUrl       types.String `tfsdk:"source_application_url"`
	SourceApplicationName      types.String `tfsdk:"source_application_name"`
	SourceType                 types.String `tfsdk:"source_type"`
	Tags                       types.Map    `tfsdk:"tags"`
	IntegrationAssociationID   types.String `tfsdk:"integration_association_id"`
	IntegrationAssociationArn  types.String `tfsdk:"integration_association_arn"`
}

// -------------------------------------------------------------------
// Metadata / Schema
// -------------------------------------------------------------------

func (r *ConnectIntegrationAssociationResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_connect_integration_association"
}

func (r *ConnectIntegrationAssociationResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Creates and manages an Amazon Connect Integration Association " +
			"(connect:CreateIntegrationAssociation / ListIntegrationAssociations / DeleteIntegrationAssociation). " +
			"Fills the gap left by the official `aws_connect_integration_association` resource, which does not " +
			"support `APPLICATION` or `WISDOM_ASSISTANT` integration types.",

		Attributes: map[string]schema.Attribute{
			"instance_id": schema.StringAttribute{
				Required:    true,
				Description: "The identifier of the Amazon Connect instance to associate the integration with. Forces replacement.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"integration_type": schema.StringAttribute{
				Required:    true,
				Description: "The type of information to be ingested. Valid values: `EVENT`, `VOICE_ID`, `PINPOINT_APP`, `WISDOM_ASSISTANT`, `WISDOM_KNOWLEDGE_BASE`, `WISDOM_QUICK_RESPONSES`, `CASES_DOMAIN`, `APPLICATION`, `FILE_SCANNER`, `Q_MESSAGE_TEMPLATES`, `SES_IDENTITY`. Forces replacement.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.OneOf(
						"EVENT",
						"VOICE_ID",
						"PINPOINT_APP",
						"WISDOM_ASSISTANT",
						"WISDOM_KNOWLEDGE_BASE",
						"WISDOM_QUICK_RESPONSES",
						"CASES_DOMAIN",
						"APPLICATION",
						"FILE_SCANNER",
						"Q_MESSAGE_TEMPLATES",
						"SES_IDENTITY",
					),
				},
			},
			"integration_arn": schema.StringAttribute{
				Required:    true,
				Description: "The Amazon Resource Name (ARN) of the integration resource to associate. Forces replacement.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"source_application_url": schema.StringAttribute{
				Optional:    true,
				Description: "The URL for the external application. Required for the `EVENT` integration type. Forces replacement.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"source_application_name": schema.StringAttribute{
				Optional:    true,
				Description: "The name of the external application. Required for the `EVENT` integration type. Forces replacement.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"source_type": schema.StringAttribute{
				Optional:    true,
				Description: "The type of the data source. Required for the `EVENT` integration type. Valid values: `SALESFORCE`, `ZENDESK`, `CASES`. Forces replacement.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.OneOf("SALESFORCE", "ZENDESK", "CASES"),
				},
			},
			"tags": schema.MapAttribute{
				Optional:    true,
				Computed:    true,
				ElementType: types.StringType,
				Description: "Tags to assign to the integration association. Updatable in place.",
			},
			"integration_association_id": schema.StringAttribute{
				Computed:    true,
				Description: "The service-assigned identifier for the integration association.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"integration_association_arn": schema.StringAttribute{
				Computed:    true,
				Description: "The Amazon Resource Name (ARN) for the integration association.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

// -------------------------------------------------------------------
// Configure
// -------------------------------------------------------------------

func (r *ConnectIntegrationAssociationResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	cfg, ok := req.ProviderData.(aws.Config)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *aws.Config, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.config = cfg
}

// -------------------------------------------------------------------
// Create
// -------------------------------------------------------------------

func (r *ConnectIntegrationAssociationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data ConnectIntegrationAssociationResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := connect.NewFromConfig(r.config)

	in := &connect.CreateIntegrationAssociationInput{
		InstanceId:      aws.String(data.InstanceID.ValueString()),
		IntegrationArn:  aws.String(data.IntegrationArn.ValueString()),
		IntegrationType: conntypes.IntegrationType(data.IntegrationType.ValueString()),
	}

	if !data.SourceApplicationUrl.IsNull() && !data.SourceApplicationUrl.IsUnknown() {
		in.SourceApplicationUrl = aws.String(data.SourceApplicationUrl.ValueString())
	}
	if !data.SourceApplicationName.IsNull() && !data.SourceApplicationName.IsUnknown() {
		in.SourceApplicationName = aws.String(data.SourceApplicationName.ValueString())
	}
	if !data.SourceType.IsNull() && !data.SourceType.IsUnknown() {
		in.SourceType = conntypes.SourceType(data.SourceType.ValueString())
	}

	tagMap, err := connectTagsFromMap(ctx, data.Tags)
	if err != nil {
		resp.Diagnostics.AddError("Error reading tags", err.Error())
		return
	}
	if tagMap != nil {
		in.Tags = tagMap
	}

	out, err := conn.CreateIntegrationAssociation(ctx, in)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error creating Connect Integration Association",
			fmt.Sprintf("Could not create Connect Integration Association, unexpected error: %s", err),
		)
		return
	}

	tflog.Trace(ctx, "created connect integration association")

	data.IntegrationAssociationID = types.StringValue(aws.ToString(out.IntegrationAssociationId))
	data.IntegrationAssociationArn = types.StringValue(aws.ToString(out.IntegrationAssociationArn))

	tags, err := readConnectTags(ctx, conn, data.IntegrationAssociationArn.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading Connect Integration Association tags", fmt.Sprintf("Could not read tags: %s", err))
		return
	}
	data.Tags = tags

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// -------------------------------------------------------------------
// Read
// -------------------------------------------------------------------

func (r *ConnectIntegrationAssociationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data ConnectIntegrationAssociationResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := connect.NewFromConfig(r.config)

	var found *conntypes.IntegrationAssociationSummary
	var nextToken *string

	for {
		listInput := &connect.ListIntegrationAssociationsInput{
			InstanceId: aws.String(data.InstanceID.ValueString()),
			// Only filter by type if we have one (not present during post-import read)
			NextToken: nextToken,
		}
		if !data.IntegrationType.IsNull() && !data.IntegrationType.IsUnknown() && data.IntegrationType.ValueString() != "" {
			listInput.IntegrationType = conntypes.IntegrationType(data.IntegrationType.ValueString())
		}
		listOut, err := conn.ListIntegrationAssociations(ctx, listInput)
		if err != nil {
			resp.Diagnostics.AddError(
				"Error reading Connect Integration Associations",
				fmt.Sprintf("Could not list Connect Integration Associations for instance %s: %s", data.InstanceID.ValueString(), err),
			)
			return
		}

		for i := range listOut.IntegrationAssociationSummaryList {
			summary := &listOut.IntegrationAssociationSummaryList[i]
			if aws.ToString(summary.IntegrationAssociationId) == data.IntegrationAssociationID.ValueString() {
				found = summary
				break
			}
		}

		if found != nil {
			break
		}

		nextToken = listOut.NextToken
		if nextToken == nil {
			break
		}
	}

	if found == nil {
		tflog.Warn(ctx, "Connect Integration Association not found, removing from state",
			map[string]any{"integration_association_id": data.IntegrationAssociationID.ValueString()})
		resp.State.RemoveResource(ctx)
		return
	}

	data.IntegrationAssociationID = types.StringValue(aws.ToString(found.IntegrationAssociationId))
	data.IntegrationAssociationArn = types.StringValue(aws.ToString(found.IntegrationAssociationArn))
	data.IntegrationArn = types.StringValue(aws.ToString(found.IntegrationArn))
	data.IntegrationType = types.StringValue(string(found.IntegrationType))

	if found.SourceApplicationUrl != nil {
		data.SourceApplicationUrl = types.StringValue(aws.ToString(found.SourceApplicationUrl))
	} else {
		data.SourceApplicationUrl = types.StringNull()
	}
	if found.SourceApplicationName != nil {
		data.SourceApplicationName = types.StringValue(aws.ToString(found.SourceApplicationName))
	} else {
		data.SourceApplicationName = types.StringNull()
	}
	if found.SourceType != "" {
		data.SourceType = types.StringValue(string(found.SourceType))
	} else {
		data.SourceType = types.StringNull()
	}

	tags, err := readConnectTags(ctx, conn, data.IntegrationAssociationArn.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading Connect Integration Association tags", fmt.Sprintf("Could not read tags: %s", err))
		return
	}
	data.Tags = tags

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// -------------------------------------------------------------------
// Update (tags only)
// -------------------------------------------------------------------

func (r *ConnectIntegrationAssociationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state ConnectIntegrationAssociationResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := connect.NewFromConfig(r.config)

	if err := updateConnectTags(ctx, conn, state.IntegrationAssociationArn.ValueString(), state.Tags, plan.Tags); err != nil {
		resp.Diagnostics.AddError(
			"Error updating Connect Integration Association tags",
			fmt.Sprintf("Could not update tags for Integration Association %s: %s", state.IntegrationAssociationArn.ValueString(), err),
		)
		return
	}

	// Carry computed fields from state.
	plan.IntegrationAssociationID = state.IntegrationAssociationID
	plan.IntegrationAssociationArn = state.IntegrationAssociationArn

	tags, err := readConnectTags(ctx, conn, state.IntegrationAssociationArn.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading Connect Integration Association tags", fmt.Sprintf("Could not read tags: %s", err))
		return
	}
	plan.Tags = tags

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// -------------------------------------------------------------------
// Delete
// -------------------------------------------------------------------

func (r *ConnectIntegrationAssociationResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data ConnectIntegrationAssociationResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := connect.NewFromConfig(r.config)

	_, err := conn.DeleteIntegrationAssociation(ctx, &connect.DeleteIntegrationAssociationInput{
		InstanceId:               aws.String(data.InstanceID.ValueString()),
		IntegrationAssociationId: aws.String(data.IntegrationAssociationID.ValueString()),
	})
	if err != nil {
		var nf *conntypes.ResourceNotFoundException
		if errors.As(err, &nf) {
			return
		}
		resp.Diagnostics.AddError(
			"Error deleting Connect Integration Association",
			fmt.Sprintf("Could not delete Connect Integration Association %s: %s", data.IntegrationAssociationID.ValueString(), err),
		)
	}
}

// -------------------------------------------------------------------
// ImportState
// -------------------------------------------------------------------

// ImportState accepts the import ID in the format <instance_id>/<integration_association_id>.
//
// Import command:
//
//	terraform import awsext_connect_integration_association.example <instance_id>/<integration_association_id>
func (r *ConnectIntegrationAssociationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.SplitN(req.ID, "/", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid import ID",
			fmt.Sprintf("Import ID must be in the format <instance_id>/<integration_association_id>, got: %q", req.ID),
		)
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("instance_id"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("integration_association_id"), parts[1])...)
	// integration_type is intentionally left unset here; the subsequent Read will populate it
	// from the ListIntegrationAssociations API response, which now handles an absent type.
}
