// Generated by Claude (claude.ai) | Date: 2026-05-18 | Model: claude-sonnet-4-6
// Re-generation prompt: see Workspaces.ai in project root

package provider

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/connect"
	conntypes "github.com/aws/aws-sdk-go-v2/service/connect/types"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var _ resource.Resource = &ConnectSecurityProfileResource{}
var _ resource.ResourceWithImportState = &ConnectSecurityProfileResource{}

func NewConnectSecurityProfileResource() resource.Resource {
	return &ConnectSecurityProfileResource{}
}

type ConnectSecurityProfileResource struct {
	config aws.Config
}

// -------------------------------------------------------------------
// Model
// -------------------------------------------------------------------

type ConnectSecurityProfileResourceModel struct {
	InstanceID                 types.String `tfsdk:"instance_id"`
	Name                       types.String `tfsdk:"name"`
	Description                types.String `tfsdk:"description"`
	Permissions                types.List   `tfsdk:"permissions"`
	Applications               types.List   `tfsdk:"applications"`
	AllowedAccessControlTags   types.Map    `tfsdk:"allowed_access_control_tags"`
	TagRestrictedResources     types.List   `tfsdk:"tag_restricted_resources"`
	Tags                       types.Map    `tfsdk:"tags"`
	SecurityProfileID          types.String `tfsdk:"security_profile_id"`
	SecurityProfileArn         types.String `tfsdk:"security_profile_arn"`
}

// applicationAttrTypes is the element type for the applications list.
var applicationAttrTypes = map[string]attr.Type{
	"namespace":               types.StringType,
	"application_permissions": types.ListType{ElemType: types.StringType},
}

var applicationObjectType = types.ObjectType{AttrTypes: applicationAttrTypes}

// -------------------------------------------------------------------
// Metadata / Schema
// -------------------------------------------------------------------

func (r *ConnectSecurityProfileResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_connect_security_profile"
}

func (r *ConnectSecurityProfileResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Creates and manages an Amazon Connect Security Profile " +
			"(connect:CreateSecurityProfile / DescribeSecurityProfile / UpdateSecurityProfile / DeleteSecurityProfile). " +
			"Fills the gap left by the official `aws_connect_security_profile` resource, which does not expose the " +
			"`applications` field required for Amazon Q Connect MCP wiring.",

		Attributes: map[string]schema.Attribute{
			"instance_id": schema.StringAttribute{
				Required:    true,
				Description: "The identifier of the Amazon Connect instance. Forces replacement.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "The name of the security profile. Forces replacement.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"description": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "The description of the security profile. Updatable in place.",
			},
			"permissions": schema.ListAttribute{
				Optional:    true,
				ElementType: types.StringType,
				Description: "The list of permissions granted to agents assigned to this security profile. Updatable in place.",
			},
			"applications": schema.ListNestedAttribute{
				Optional:    true,
				Description: "The list of third-party applications and their permissions granted to agents assigned to this security profile. Updatable in place.",
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"namespace": schema.StringAttribute{
							Required:    true,
							Description: "The namespace of the third-party application.",
						},
						"application_permissions": schema.ListAttribute{
							Required:    true,
							ElementType: types.StringType,
							Description: "The permissions granted to the third-party application.",
						},
					},
				},
			},
			"allowed_access_control_tags": schema.MapAttribute{
				Optional:    true,
				ElementType: types.StringType,
				Description: "The list of tags that a security profile uses to restrict access to resources in Amazon Connect. Updatable in place.",
			},
			"tag_restricted_resources": schema.ListAttribute{
				Optional:    true,
				ElementType: types.StringType,
				Description: "The list of resources that a security profile applies tag restrictions to in Amazon Connect. Updatable in place.",
			},
			"tags": schema.MapAttribute{
				Optional:    true,
				Computed:    true,
				ElementType: types.StringType,
				Description: "Tags to assign to the security profile. Updatable in place.",
			},
			"security_profile_id": schema.StringAttribute{
				Computed:    true,
				Description: "The service-assigned identifier for the security profile.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"security_profile_arn": schema.StringAttribute{
				Computed:    true,
				Description: "The Amazon Resource Name (ARN) for the security profile.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

// -------------------------------------------------------------------
// Configure
// -------------------------------------------------------------------

func (r *ConnectSecurityProfileResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	cfg, ok := req.ProviderData.(aws.Config)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *aws.Config, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.config = cfg
}

// -------------------------------------------------------------------
// Create
// -------------------------------------------------------------------

func (r *ConnectSecurityProfileResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data ConnectSecurityProfileResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := connect.NewFromConfig(r.config)

	in := &connect.CreateSecurityProfileInput{
		InstanceId:          aws.String(data.InstanceID.ValueString()),
		SecurityProfileName: aws.String(data.Name.ValueString()),
	}

	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		in.Description = aws.String(data.Description.ValueString())
	}

	if !data.Permissions.IsNull() && !data.Permissions.IsUnknown() {
		var perms []string
		resp.Diagnostics.Append(data.Permissions.ElementsAs(ctx, &perms, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		in.Permissions = perms
	}

	if !data.Applications.IsNull() && !data.Applications.IsUnknown() {
		apps, err := expandApplications(ctx, data.Applications)
		if err != nil {
			resp.Diagnostics.AddError("Error expanding applications", err.Error())
			return
		}
		in.Applications = apps
	}

	if !data.AllowedAccessControlTags.IsNull() && !data.AllowedAccessControlTags.IsUnknown() {
		var tagMap map[string]string
		resp.Diagnostics.Append(data.AllowedAccessControlTags.ElementsAs(ctx, &tagMap, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		in.AllowedAccessControlTags = tagMap
	}

	if !data.TagRestrictedResources.IsNull() && !data.TagRestrictedResources.IsUnknown() {
		var resources []string
		resp.Diagnostics.Append(data.TagRestrictedResources.ElementsAs(ctx, &resources, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		in.TagRestrictedResources = resources
	}

	tagMap, err := connectTagsFromMap(ctx, data.Tags)
	if err != nil {
		resp.Diagnostics.AddError("Error reading tags", err.Error())
		return
	}
	if tagMap != nil {
		in.Tags = tagMap
	}

	out, err := conn.CreateSecurityProfile(ctx, in)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error creating Connect Security Profile",
			fmt.Sprintf("Could not create Connect Security Profile, unexpected error: %s", err),
		)
		return
	}

	tflog.Trace(ctx, "created connect security profile")

	data.SecurityProfileID = types.StringValue(aws.ToString(out.SecurityProfileId))
	data.SecurityProfileArn = types.StringValue(aws.ToString(out.SecurityProfileArn))

	// Read back to get computed fields (description, tags, etc.)
	if errs := r.readInto(ctx, conn, &data); len(errs) > 0 {
		resp.Diagnostics.AddError("Error reading back Connect Security Profile after create", errs[0])
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// -------------------------------------------------------------------
// Read
// -------------------------------------------------------------------

func (r *ConnectSecurityProfileResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data ConnectSecurityProfileResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := connect.NewFromConfig(r.config)

	descOut, err := conn.DescribeSecurityProfile(ctx, &connect.DescribeSecurityProfileInput{
		InstanceId:        aws.String(data.InstanceID.ValueString()),
		SecurityProfileId: aws.String(data.SecurityProfileID.ValueString()),
	})
	if err != nil {
		var nf *conntypes.ResourceNotFoundException
		if errors.As(err, &nf) {
			tflog.Warn(ctx, "Connect Security Profile not found, removing from state",
				map[string]any{"security_profile_id": data.SecurityProfileID.ValueString()})
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError(
			"Error reading Connect Security Profile",
			fmt.Sprintf("Could not describe Connect Security Profile %s: %s", data.SecurityProfileID.ValueString(), err),
		)
		return
	}

	sp := descOut.SecurityProfile
	data.SecurityProfileID = types.StringValue(aws.ToString(sp.Id))
	data.SecurityProfileArn = types.StringValue(aws.ToString(sp.Arn))
	data.Name = types.StringValue(aws.ToString(sp.SecurityProfileName))

	if sp.Description != nil {
		data.Description = types.StringValue(aws.ToString(sp.Description))
	} else {
		data.Description = types.StringNull()
	}

	// Paginate through ListSecurityProfilePermissions to get permissions.
	var allPerms []string
	var permsNextToken *string
	for {
		listPermsOut, err := conn.ListSecurityProfilePermissions(ctx, &connect.ListSecurityProfilePermissionsInput{
			InstanceId:        aws.String(data.InstanceID.ValueString()),
			SecurityProfileId: aws.String(data.SecurityProfileID.ValueString()),
			NextToken:         permsNextToken,
		})
		if err != nil {
			resp.Diagnostics.AddError(
				"Error listing Connect Security Profile Permissions",
				fmt.Sprintf("Could not list permissions for security profile %s: %s", data.SecurityProfileID.ValueString(), err),
			)
			return
		}
		allPerms = append(allPerms, listPermsOut.Permissions...)
		permsNextToken = listPermsOut.NextToken
		if permsNextToken == nil {
			break
		}
	}

	if len(allPerms) > 0 {
		perms, diags := types.ListValueFrom(ctx, types.StringType, allPerms)
		resp.Diagnostics.Append(diags...)
		if resp.Diagnostics.HasError() {
			return
		}
		data.Permissions = perms
	} else {
		data.Permissions = types.ListValueMust(types.StringType, []attr.Value{})
	}

	if len(sp.AllowedAccessControlTags) > 0 {
		aact, diags := types.MapValueFrom(ctx, types.StringType, sp.AllowedAccessControlTags)
		resp.Diagnostics.Append(diags...)
		if resp.Diagnostics.HasError() {
			return
		}
		data.AllowedAccessControlTags = aact
	} else {
		data.AllowedAccessControlTags = types.MapValueMust(types.StringType, map[string]attr.Value{})
	}

	if len(sp.TagRestrictedResources) > 0 {
		trr, diags := types.ListValueFrom(ctx, types.StringType, sp.TagRestrictedResources)
		resp.Diagnostics.Append(diags...)
		if resp.Diagnostics.HasError() {
			return
		}
		data.TagRestrictedResources = trr
	} else {
		data.TagRestrictedResources = types.ListValueMust(types.StringType, []attr.Value{})
	}

	// Paginate through ListSecurityProfileApplications
	var allApps []conntypes.Application
	var nextToken *string
	for {
		listAppsOut, err := conn.ListSecurityProfileApplications(ctx, &connect.ListSecurityProfileApplicationsInput{
			InstanceId:        aws.String(data.InstanceID.ValueString()),
			SecurityProfileId: aws.String(data.SecurityProfileID.ValueString()),
			NextToken:         nextToken,
		})
		if err != nil {
			resp.Diagnostics.AddError(
				"Error listing Connect Security Profile Applications",
				fmt.Sprintf("Could not list applications for security profile %s: %s", data.SecurityProfileID.ValueString(), err),
			)
			return
		}
		allApps = append(allApps, listAppsOut.Applications...)
		nextToken = listAppsOut.NextToken
		if nextToken == nil {
			break
		}
	}

	appsList, err := flattenApplications(ctx, allApps)
	if err != nil {
		resp.Diagnostics.AddError("Error flattening applications", err.Error())
		return
	}
	data.Applications = appsList

	tags, err := readConnectTags(ctx, conn, data.SecurityProfileArn.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading Connect Security Profile tags", fmt.Sprintf("Could not read tags: %s", err))
		return
	}
	data.Tags = tags

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// -------------------------------------------------------------------
// Update
// -------------------------------------------------------------------

func (r *ConnectSecurityProfileResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state ConnectSecurityProfileResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := connect.NewFromConfig(r.config)

	in := &connect.UpdateSecurityProfileInput{
		InstanceId:        aws.String(state.InstanceID.ValueString()),
		SecurityProfileId: aws.String(state.SecurityProfileID.ValueString()),
	}

	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		in.Description = aws.String(plan.Description.ValueString())
	}

	if !plan.Permissions.IsNull() && !plan.Permissions.IsUnknown() {
		var perms []string
		resp.Diagnostics.Append(plan.Permissions.ElementsAs(ctx, &perms, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		in.Permissions = perms
	}

	if !plan.Applications.IsNull() && !plan.Applications.IsUnknown() {
		apps, err := expandApplications(ctx, plan.Applications)
		if err != nil {
			resp.Diagnostics.AddError("Error expanding applications", err.Error())
			return
		}
		in.Applications = apps
	}

	if !plan.AllowedAccessControlTags.IsNull() && !plan.AllowedAccessControlTags.IsUnknown() {
		var tagMap map[string]string
		resp.Diagnostics.Append(plan.AllowedAccessControlTags.ElementsAs(ctx, &tagMap, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		in.AllowedAccessControlTags = tagMap
	}

	if !plan.TagRestrictedResources.IsNull() && !plan.TagRestrictedResources.IsUnknown() {
		var resources []string
		resp.Diagnostics.Append(plan.TagRestrictedResources.ElementsAs(ctx, &resources, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		in.TagRestrictedResources = resources
	}

	_, err := conn.UpdateSecurityProfile(ctx, in)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error updating Connect Security Profile",
			fmt.Sprintf("Could not update Connect Security Profile %s: %s", state.SecurityProfileID.ValueString(), err),
		)
		return
	}

	if err := updateConnectTags(ctx, conn, state.SecurityProfileArn.ValueString(), state.Tags, plan.Tags); err != nil {
		resp.Diagnostics.AddError(
			"Error updating Connect Security Profile tags",
			fmt.Sprintf("Could not update tags for Security Profile %s: %s", state.SecurityProfileArn.ValueString(), err),
		)
		return
	}

	// Carry computed fields from state.
	plan.SecurityProfileID = state.SecurityProfileID
	plan.SecurityProfileArn = state.SecurityProfileArn

	// Read back to get up-to-date state.
	if errs := r.readInto(ctx, conn, &plan); len(errs) > 0 {
		resp.Diagnostics.AddError("Error reading back Connect Security Profile after update", errs[0])
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// -------------------------------------------------------------------
// Delete
// -------------------------------------------------------------------

func (r *ConnectSecurityProfileResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data ConnectSecurityProfileResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := connect.NewFromConfig(r.config)

	_, err := conn.DeleteSecurityProfile(ctx, &connect.DeleteSecurityProfileInput{
		InstanceId:        aws.String(data.InstanceID.ValueString()),
		SecurityProfileId: aws.String(data.SecurityProfileID.ValueString()),
	})
	if err != nil {
		var nf *conntypes.ResourceNotFoundException
		if errors.As(err, &nf) {
			return
		}
		resp.Diagnostics.AddError(
			"Error deleting Connect Security Profile",
			fmt.Sprintf("Could not delete Connect Security Profile %s: %s", data.SecurityProfileID.ValueString(), err),
		)
	}
}

// -------------------------------------------------------------------
// ImportState
// -------------------------------------------------------------------

// ImportState accepts the import ID in the format <instance_id>/<security_profile_id>.
//
// Import command:
//
//	terraform import awsext_connect_security_profile.example <instance_id>/<security_profile_id>
func (r *ConnectSecurityProfileResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.SplitN(req.ID, "/", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid import ID",
			fmt.Sprintf("Import ID must be in the format <instance_id>/<security_profile_id>, got: %q", req.ID),
		)
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("instance_id"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("security_profile_id"), parts[1])...)
}

// -------------------------------------------------------------------
// Helpers
// -------------------------------------------------------------------

// readInto is a shared helper for Create and Update to read back state after mutation.
// It populates all computed/server-side fields of data in place and returns any diagnostics as a slice.
func (r *ConnectSecurityProfileResource) readInto(ctx context.Context, conn *connect.Client, data *ConnectSecurityProfileResourceModel) []string {
	descOut, err := conn.DescribeSecurityProfile(ctx, &connect.DescribeSecurityProfileInput{
		InstanceId:        aws.String(data.InstanceID.ValueString()),
		SecurityProfileId: aws.String(data.SecurityProfileID.ValueString()),
	})
	if err != nil {
		return []string{fmt.Sprintf("Could not describe Connect Security Profile %s: %s", data.SecurityProfileID.ValueString(), err)}
	}

	sp := descOut.SecurityProfile
	data.SecurityProfileID = types.StringValue(aws.ToString(sp.Id))
	data.SecurityProfileArn = types.StringValue(aws.ToString(sp.Arn))
	data.Name = types.StringValue(aws.ToString(sp.SecurityProfileName))

	if sp.Description != nil {
		data.Description = types.StringValue(aws.ToString(sp.Description))
	} else {
		data.Description = types.StringNull()
	}

	tags, err := readConnectTags(ctx, conn, data.SecurityProfileArn.ValueString())
	if err != nil {
		return []string{fmt.Sprintf("Could not read tags for Connect Security Profile %s: %s", data.SecurityProfileID.ValueString(), err)}
	}
	data.Tags = tags

	return nil
}

// expandApplications converts a types.List of application objects into []conntypes.Application.
func expandApplications(ctx context.Context, list types.List) ([]conntypes.Application, error) {
	if list.IsNull() || list.IsUnknown() {
		return nil, nil
	}

	type appModel struct {
		Namespace              types.String `tfsdk:"namespace"`
		ApplicationPermissions types.List   `tfsdk:"application_permissions"`
	}

	var models []appModel
	diags := list.ElementsAs(ctx, &models, false)
	if diags.HasError() {
		return nil, fmt.Errorf("error expanding applications list")
	}

	result := make([]conntypes.Application, 0, len(models))
	for _, m := range models {
		app := conntypes.Application{
			Namespace: aws.String(m.Namespace.ValueString()),
		}
		if !m.ApplicationPermissions.IsNull() && !m.ApplicationPermissions.IsUnknown() {
			var perms []string
			if d := m.ApplicationPermissions.ElementsAs(ctx, &perms, false); d.HasError() {
				return nil, fmt.Errorf("error expanding application_permissions")
			}
			app.ApplicationPermissions = perms
		}
		result = append(result, app)
	}
	return result, nil
}

// flattenApplications converts []conntypes.Application into a types.List of application objects.
func flattenApplications(ctx context.Context, apps []conntypes.Application) (types.List, error) {
	elemType := applicationObjectType

	if len(apps) == 0 {
		return types.ListValueMust(elemType, []attr.Value{}), nil
	}

	objs := make([]attr.Value, 0, len(apps))
	for _, app := range apps {
		ns := types.StringNull()
		if app.Namespace != nil {
			ns = types.StringValue(aws.ToString(app.Namespace))
		}

		var permValues []attr.Value
		for _, p := range app.ApplicationPermissions {
			permValues = append(permValues, types.StringValue(p))
		}
		permsList, diags := types.ListValue(types.StringType, permValues)
		if diags.HasError() {
			return types.ListNull(elemType), fmt.Errorf("error flattening application_permissions")
		}

		obj, diags := types.ObjectValue(applicationAttrTypes, map[string]attr.Value{
			"namespace":               ns,
			"application_permissions": permsList,
		})
		if diags.HasError() {
			return types.ListNull(elemType), fmt.Errorf("error flattening application object")
		}
		objs = append(objs, obj)
	}

	result, diags := types.ListValue(elemType, objs)
	if diags.HasError() {
		return types.ListNull(elemType), fmt.Errorf("error flattening applications list")
	}
	return result, nil
}
