// Generated by Claude (claude.ai) | Date: 2026-05-18 | Model: claude-sonnet-4-6
// Re-generation prompt: Task 11 of awsext provider plan

package provider

import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/connect"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// readConnectTags fetches tags for a Connect resource by ARN and returns them as a types.Map.
func readConnectTags(ctx context.Context, conn *connect.Client, resourceArn string) (types.Map, error) {
	output, err := conn.ListTagsForResource(ctx, &connect.ListTagsForResourceInput{
		ResourceArn: aws.String(resourceArn),
	})
	if err != nil {
		return types.MapNull(types.StringType), err
	}

	result, diags := types.MapValueFrom(ctx, types.StringType, output.Tags)
	if diags.HasError() {
		return types.MapNull(types.StringType), fmt.Errorf("error converting connect tags to map")
	}
	return result, nil
}

// updateConnectTags diffs old vs new tags and calls UntagResource / TagResource.
func updateConnectTags(ctx context.Context, conn *connect.Client, resourceArn string, oldTags, newTags types.Map) error {
	var oldTagMap, newTagMap map[string]string

	if !oldTags.IsNull() && !oldTags.IsUnknown() {
		oldTags.ElementsAs(ctx, &oldTagMap, false)
	}
	if !newTags.IsNull() && !newTags.IsUnknown() {
		newTags.ElementsAs(ctx, &newTagMap, false)
	}

	var keysToDelete []string
	for k := range oldTagMap {
		if _, exists := newTagMap[k]; !exists {
			keysToDelete = append(keysToDelete, k)
		}
	}

	if len(keysToDelete) > 0 {
		if _, err := conn.UntagResource(ctx, &connect.UntagResourceInput{
			ResourceArn: aws.String(resourceArn),
			TagKeys:     keysToDelete,
		}); err != nil {
			return err
		}
	}

	if len(newTagMap) > 0 {
		if _, err := conn.TagResource(ctx, &connect.TagResourceInput{
			ResourceArn: aws.String(resourceArn),
			Tags:        newTagMap,
		}); err != nil {
			return err
		}
	}

	return nil
}

// connectTagsFromMap turns a types.Map of tags into the map[string]string
// shape Connect Create* inputs expect.
func connectTagsFromMap(ctx context.Context, tags types.Map) (map[string]string, error) {
	if tags.IsNull() || tags.IsUnknown() {
		return nil, nil
	}
	var tagMap map[string]string
	if diags := tags.ElementsAs(ctx, &tagMap, false); diags.HasError() {
		return nil, fmt.Errorf("error reading connect tags")
	}
	return tagMap, nil
}
