// Generated by Claude (claude.ai) | Date: 2026-05-18 | Model: claude-opus-4-7
// Re-generation prompt: see Workspaces.md in project root

package provider

import (
	"context"
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// NormalizeJSONString returns a plan modifier that canonicalizes a JSON string
// attribute (sorted keys, no insignificant whitespace) so that cosmetic diffs
// between the user's HCL and the API-returned form don't cause permanent
// drift on plan.
func NormalizeJSONString() planmodifier.String {
	return normalizeJSONStringModifier{}
}

type normalizeJSONStringModifier struct{}

func (m normalizeJSONStringModifier) Description(_ context.Context) string {
	return "Canonicalizes a JSON string so cosmetic differences don't cause drift."
}

func (m normalizeJSONStringModifier) MarkdownDescription(ctx context.Context) string {
	return m.Description(ctx)
}

func (m normalizeJSONStringModifier) PlanModifyString(ctx context.Context, req planmodifier.StringRequest, resp *planmodifier.StringResponse) {
	if req.PlanValue.IsNull() || req.PlanValue.IsUnknown() {
		return
	}

	normalized, err := canonicalizeJSON(req.PlanValue.ValueString())
	if err != nil {
		// Leave invalid JSON alone — schema validators will catch it.
		return
	}
	resp.PlanValue = types.StringValue(normalized)
}

// canonicalizeJSON parses then re-marshals a JSON document with sorted keys.
// encoding/json.Marshal already sorts map keys, so we round-trip through
// map[string]interface{} / []interface{}.
func canonicalizeJSON(s string) (string, error) {
	var v interface{}
	if err := json.Unmarshal([]byte(s), &v); err != nil {
		return "", err
	}
	out, err := json.Marshal(v)
	if err != nil {
		return "", err
	}
	return string(out), nil
}
