// Generated by Claude (claude.ai) | Date: 2026-05-18 | Model: claude-sonnet-4-6
// Re-generation prompt: see Workspaces.ai in project root

package provider

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/lexmodelsv2"
	lextypes "github.com/aws/aws-sdk-go-v2/service/lexmodelsv2/types"
	"github.com/aws/aws-sdk-go-v2/service/sts"

	"github.com/hashicorp/terraform-plugin-framework-validators/resourcevalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var _ resource.Resource = &LexV2BotImportResource{}
var _ resource.ResourceWithImportState = &LexV2BotImportResource{}
var _ resource.ResourceWithConfigValidators = &LexV2BotImportResource{}

func NewLexV2BotImportResource() resource.Resource {
	return &LexV2BotImportResource{}
}

type LexV2BotImportResource struct {
	config aws.Config
}

// -------------------------------------------------------------------
// Model
// -------------------------------------------------------------------

type LexV2BotImportResourceModel struct {
	BotID                       types.String `tfsdk:"bot_id"`
	BotArn                      types.String `tfsdk:"bot_arn"`
	ZipFilePath                 types.String `tfsdk:"zip_file_path"`
	ZipContentBase64            types.String `tfsdk:"zip_content_base64"`
	ZipSHA256                   types.String `tfsdk:"zip_sha256"`
	RoleArn                     types.String `tfsdk:"role_arn"`
	MergeStrategy               types.String `tfsdk:"merge_strategy"`
	ImportResourceSpecification types.String `tfsdk:"import_resource_specification"`
	ImportOnExists              types.Bool   `tfsdk:"import_on_exists"`
	ImportStatus                types.String `tfsdk:"import_status"`
	ImportID                    types.String `tfsdk:"import_id"`
}

// -------------------------------------------------------------------
// Metadata / Schema
// -------------------------------------------------------------------

func (r *LexV2BotImportResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_lexv2_bot_import"
}

func (r *LexV2BotImportResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Imports an Amazon Lex V2 bot from a zip archive using the LexV2 import API " +
			"(CreateUploadUrl / StartImport / DescribeImport). Supports idempotent creation via `import_on_exists`.",

		Attributes: map[string]schema.Attribute{
			"bot_id": schema.StringAttribute{
				Computed:    true,
				Description: "The service-assigned identifier of the imported bot.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"bot_arn": schema.StringAttribute{
				Computed:    true,
				Description: "The Amazon Resource Name (ARN) of the imported bot.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"zip_file_path": schema.StringAttribute{
				Optional:    true,
				Sensitive:   true,
				Description: "Local path to the zip archive containing the bot definition. Exactly one of zip_file_path or zip_content_base64 must be set. Not stored in state.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"zip_content_base64": schema.StringAttribute{
				Optional:    true,
				Sensitive:   true,
				Description: "Base64-encoded zip archive containing the bot definition. Exactly one of zip_file_path or zip_content_base64 must be set. Not stored in state.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"zip_sha256": schema.StringAttribute{
				Optional:    true,
				Description: "SHA256 checksum of the zip archive. Stored in state; changing this value triggers replacement.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"role_arn": schema.StringAttribute{
				Required:    true,
				Description: "IAM role ARN that Amazon Lex assumes to build and run the bot. Forces replacement.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"merge_strategy": schema.StringAttribute{
				Required:    true,
				Description: "Determines how conflicts are resolved when the import already exists. Valid values: Overwrite, FailOnConflict, Append. Forces replacement.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"import_resource_specification": schema.StringAttribute{
				Required:    true,
				Description: "JSON-encoded ImportResourceSpecification for the StartImport call. Forces replacement.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					NormalizeJSONString(),
				},
			},
			"import_on_exists": schema.BoolAttribute{
				Optional:    true,
				Sensitive:   true,
				Description: "When true, if a bot matching the name in import_resource_specification already exists, adopt it into state instead of running the import. Not stored in state.",
			},
			"import_status": schema.StringAttribute{
				Computed:    true,
				Description: "The final import status returned by DescribeImport (Completed, Failed, etc.).",
			},
			"import_id": schema.StringAttribute{
				Computed:    true,
				Description: "The import job identifier returned by CreateUploadUrl.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

// -------------------------------------------------------------------
// ConfigValidators
// -------------------------------------------------------------------

func (r *LexV2BotImportResource) ConfigValidators(_ context.Context) []resource.ConfigValidator {
	return []resource.ConfigValidator{
		resourcevalidator.ExactlyOneOf(
			path.MatchRoot("zip_file_path"),
			path.MatchRoot("zip_content_base64"),
		),
	}
}

// -------------------------------------------------------------------
// Configure
// -------------------------------------------------------------------

func (r *LexV2BotImportResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	cfg, ok := req.ProviderData.(aws.Config)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *aws.Config, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.config = cfg
}

// -------------------------------------------------------------------
// Create
// -------------------------------------------------------------------

func (r *LexV2BotImportResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data LexV2BotImportResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	lexClient := lexmodelsv2.NewFromConfig(r.config)

	// Step 2: if import_on_exists, check for existing bot by name.
	if !data.ImportOnExists.IsNull() && !data.ImportOnExists.IsUnknown() && data.ImportOnExists.ValueBool() {
		botName, err := extractBotNameFromSpec(data.ImportResourceSpecification.ValueString())
		if err == nil && botName != "" {
			botID, found, findErr := r.findBotByName(ctx, lexClient, botName)
			if findErr != nil {
				resp.Diagnostics.AddError("Error searching for existing bot", findErr.Error())
				return
			}
			if found {
				tflog.Info(ctx, "import_on_exists: found existing bot, adopting into state", map[string]any{"bot_id": botID})
				data.BotID = types.StringValue(botID)
				botArn, arnErr := r.buildBotArn(ctx, botID)
				if arnErr != nil {
					resp.Diagnostics.AddError("Error constructing bot ARN", arnErr.Error())
					return
				}
				data.BotArn = types.StringValue(botArn)
				data.ImportStatus = types.StringValue("Adopted")
				data.ImportID = types.StringValue("")
				resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
				return
			}
		}
	}

	// Step 3: CreateUploadUrl.
	uploadOut, err := lexClient.CreateUploadUrl(ctx, &lexmodelsv2.CreateUploadUrlInput{})
	if err != nil {
		resp.Diagnostics.AddError("Error creating LexV2 upload URL", err.Error())
		return
	}
	importID := aws.ToString(uploadOut.ImportId)
	uploadURL := aws.ToString(uploadOut.UploadUrl)
	data.ImportID = types.StringValue(importID)

	// Step 4: Read zip bytes.
	var zipBytes []byte
	if !data.ZipFilePath.IsNull() && !data.ZipFilePath.IsUnknown() && data.ZipFilePath.ValueString() != "" {
		zipBytes, err = os.ReadFile(data.ZipFilePath.ValueString())
		if err != nil {
			resp.Diagnostics.AddError("Error reading zip file", fmt.Sprintf("Could not read %s: %s", data.ZipFilePath.ValueString(), err))
			return
		}
	} else {
		zipBytes, err = base64.StdEncoding.DecodeString(data.ZipContentBase64.ValueString())
		if err != nil {
			resp.Diagnostics.AddError("Error decoding zip_content_base64", err.Error())
			return
		}
	}

	// Step 5: HTTP PUT zip bytes to UploadUrl.
	putReq, err := http.NewRequestWithContext(ctx, http.MethodPut, uploadURL, bytes.NewReader(zipBytes))
	if err != nil {
		resp.Diagnostics.AddError("Error creating upload HTTP request", err.Error())
		return
	}
	putReq.Header.Set("Content-Type", "application/zip")
	httpClient := &http.Client{Timeout: 5 * time.Minute}
	putResp, err := httpClient.Do(putReq)
	if err != nil {
		resp.Diagnostics.AddError("Error uploading zip to S3", err.Error())
		return
	}
	defer putResp.Body.Close()
	if putResp.StatusCode < 200 || putResp.StatusCode >= 300 {
		body, _ := io.ReadAll(putResp.Body)
		resp.Diagnostics.AddError("Error uploading zip to S3", fmt.Sprintf("HTTP %d: %s", putResp.StatusCode, string(body)))
		return
	}

	// Step 6: StartImport.
	var resourceSpec lextypes.ImportResourceSpecification
	if err := json.Unmarshal([]byte(data.ImportResourceSpecification.ValueString()), &resourceSpec); err != nil {
		resp.Diagnostics.AddError("Error decoding import_resource_specification", err.Error())
		return
	}

	_, err = lexClient.StartImport(ctx, &lexmodelsv2.StartImportInput{
		ImportId:              aws.String(importID),
		ResourceSpecification: &resourceSpec,
		MergeStrategy:         lextypes.MergeStrategy(data.MergeStrategy.ValueString()),
	})
	if err != nil {
		resp.Diagnostics.AddError("Error starting LexV2 import", err.Error())
		return
	}

	// Step 7: Poll DescribeImport until Completed or Failed.
	botID, finalStatus, failReasons, pollErr := r.pollImport(ctx, lexClient, importID)
	if pollErr != nil {
		resp.Diagnostics.AddError("Error polling LexV2 import status", pollErr.Error())
		return
	}
	data.ImportStatus = types.StringValue(string(finalStatus))

	if finalStatus != lextypes.ImportStatusCompleted {
		resp.Diagnostics.AddError(
			"LexV2 import failed",
			fmt.Sprintf("Import %s ended with status %s. Reasons: %v", importID, finalStatus, failReasons),
		)
		return
	}

	// Step 8: Set bot_id.
	data.BotID = types.StringValue(botID)

	// Step 9: Construct bot_arn.
	botArn, arnErr := r.buildBotArn(ctx, botID)
	if arnErr != nil {
		resp.Diagnostics.AddError("Error constructing bot ARN", arnErr.Error())
		return
	}
	data.BotArn = types.StringValue(botArn)

	tflog.Trace(ctx, "lexv2 bot import completed", map[string]any{"bot_id": botID, "import_id": importID})

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// -------------------------------------------------------------------
// Read
// -------------------------------------------------------------------

func (r *LexV2BotImportResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data LexV2BotImportResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if data.BotID.IsNull() || data.BotID.IsUnknown() || data.BotID.ValueString() == "" {
		return
	}

	lexClient := lexmodelsv2.NewFromConfig(r.config)

	_, err := lexClient.DescribeBot(ctx, &lexmodelsv2.DescribeBotInput{
		BotId: aws.String(data.BotID.ValueString()),
	})
	if err != nil {
		var nf *lextypes.ResourceNotFoundException
		if errors.As(err, &nf) {
			tflog.Warn(ctx, "LexV2 bot not found, removing from state", map[string]any{"bot_id": data.BotID.ValueString()})
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError(
			"Error reading LexV2 bot",
			fmt.Sprintf("Could not describe bot %s: %s", data.BotID.ValueString(), err),
		)
		return
	}

	// bot_arn is computed; rebuild it if missing (e.g. after terraform import).
	if data.BotArn.IsNull() || data.BotArn.IsUnknown() || data.BotArn.ValueString() == "" {
		botArn, arnErr := r.buildBotArn(ctx, data.BotID.ValueString())
		if arnErr == nil {
			data.BotArn = types.StringValue(botArn)
		}
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// -------------------------------------------------------------------
// Update (no in-place updates; all attributes are ForceNew)
// -------------------------------------------------------------------

func (r *LexV2BotImportResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// All mutable attributes either force replacement or are WriteOnly/Computed.
	// This method should never be called in normal operation.
	resp.Diagnostics.AddError("Update not supported", "awsext_lexv2_bot_import does not support in-place updates; all attributes force replacement.")
}

// -------------------------------------------------------------------
// Delete
// -------------------------------------------------------------------

func (r *LexV2BotImportResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data LexV2BotImportResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if data.BotID.IsNull() || data.BotID.IsUnknown() || data.BotID.ValueString() == "" {
		return
	}

	lexClient := lexmodelsv2.NewFromConfig(r.config)

	_, err := lexClient.DeleteBot(ctx, &lexmodelsv2.DeleteBotInput{
		BotId:                  aws.String(data.BotID.ValueString()),
		SkipResourceInUseCheck: false,
	})
	if err != nil {
		var nf *lextypes.ResourceNotFoundException
		if errors.As(err, &nf) {
			return
		}
		resp.Diagnostics.AddError(
			"Error deleting LexV2 bot",
			fmt.Sprintf("Could not delete bot %s: %s", data.BotID.ValueString(), err),
		)
		return
	}

	// Poll until bot is gone (up to 2 minutes).
	deadline := time.Now().Add(2 * time.Minute)
	for time.Now().Before(deadline) {
		time.Sleep(5 * time.Second)
		_, descErr := lexClient.DescribeBot(ctx, &lexmodelsv2.DescribeBotInput{
			BotId: aws.String(data.BotID.ValueString()),
		})
		if descErr != nil {
			var nf *lextypes.ResourceNotFoundException
			if errors.As(descErr, &nf) {
				return
			}
		}
	}
	tflog.Warn(ctx, "timed out waiting for LexV2 bot deletion", map[string]any{"bot_id": data.BotID.ValueString()})
}

// -------------------------------------------------------------------
// ImportState
// -------------------------------------------------------------------

func (r *LexV2BotImportResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("bot_id"), req, resp)
}

// -------------------------------------------------------------------
// Helpers
// -------------------------------------------------------------------

// pollImport polls DescribeImport until the status is Completed or Failed (or timeout).
func (r *LexV2BotImportResource) pollImport(ctx context.Context, client *lexmodelsv2.Client, importID string) (botID string, status lextypes.ImportStatus, failReasons []string, err error) {
	const maxIterations = 60
	const sleepDuration = 5 * time.Second

	for i := 0; i < maxIterations; i++ {
		time.Sleep(sleepDuration)

		out, descErr := client.DescribeImport(ctx, &lexmodelsv2.DescribeImportInput{
			ImportId: aws.String(importID),
		})
		if descErr != nil {
			return "", "", nil, fmt.Errorf("DescribeImport error: %w", descErr)
		}

		switch out.ImportStatus {
		case lextypes.ImportStatusCompleted:
			return aws.ToString(out.ImportedResourceId), out.ImportStatus, nil, nil
		case lextypes.ImportStatusFailed:
			return "", out.ImportStatus, out.FailureReasons, nil
		case lextypes.ImportStatusInProgress, lextypes.ImportStatusDeleting:
			// continue polling
		}
	}
	return "", lextypes.ImportStatusInProgress, nil, fmt.Errorf("timed out waiting for import %s to complete", importID)
}

// buildBotArn constructs an ARN for the bot using the current AWS region and account ID.
func (r *LexV2BotImportResource) buildBotArn(ctx context.Context, botID string) (string, error) {
	stsClient := sts.NewFromConfig(r.config)
	identity, err := stsClient.GetCallerIdentity(ctx, &sts.GetCallerIdentityInput{})
	if err != nil {
		return "", fmt.Errorf("GetCallerIdentity error: %w", err)
	}
	return fmt.Sprintf("arn:aws:lex:%s:%s:bot/%s", r.config.Region, aws.ToString(identity.Account), botID), nil
}

// findBotByName searches ListBots for a bot with the given name and returns its ID.
func (r *LexV2BotImportResource) findBotByName(ctx context.Context, client *lexmodelsv2.Client, botName string) (botID string, found bool, err error) {
	var nextToken *string
	for {
		out, listErr := client.ListBots(ctx, &lexmodelsv2.ListBotsInput{
			Filters: []lextypes.BotFilter{
				{
					Name:     lextypes.BotFilterNameBotName,
					Values:   []string{botName},
					Operator: lextypes.BotFilterOperatorEquals,
				},
			},
			NextToken: nextToken,
		})
		if listErr != nil {
			return "", false, fmt.Errorf("ListBots error: %w", listErr)
		}
		for _, summary := range out.BotSummaries {
			return aws.ToString(summary.BotId), true, nil
		}
		nextToken = out.NextToken
		if nextToken == nil {
			break
		}
	}
	return "", false, nil
}

// extractBotNameFromSpec extracts the botName from the import_resource_specification JSON.
// It handles the JSON representation of ImportResourceSpecification.
func extractBotNameFromSpec(specJSON string) (string, error) {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal([]byte(specJSON), &raw); err != nil {
		return "", err
	}

	// Try botImportSpecification (camelCase from jsonencode HCL).
	for _, key := range []string{"botImportSpecification", "BotImportSpecification"} {
		if v, ok := raw[key]; ok {
			var botSpec struct {
				BotName string `json:"botName"`
			}
			if err := json.Unmarshal(v, &botSpec); err == nil && botSpec.BotName != "" {
				return botSpec.BotName, nil
			}
			// Try PascalCase.
			var botSpecPascal struct {
				BotName string `json:"BotName"`
			}
			if err := json.Unmarshal(v, &botSpecPascal); err == nil && botSpecPascal.BotName != "" {
				return botSpecPascal.BotName, nil
			}
		}
	}
	return "", fmt.Errorf("botName not found in import_resource_specification")
}
