// Generated by Claude (claude.ai) | Date: 2026-05-18 | Model: claude-sonnet-4-6
// Re-generation prompt: see Workspaces.ai in project root

package provider

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/lexmodelsv2"
	lextypes "github.com/aws/aws-sdk-go-v2/service/lexmodelsv2/types"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var _ resource.Resource = &LexV2BotLocaleBuildResource{}
var _ resource.ResourceWithImportState = &LexV2BotLocaleBuildResource{}

func NewLexV2BotLocaleBuildResource() resource.Resource {
	return &LexV2BotLocaleBuildResource{}
}

type LexV2BotLocaleBuildResource struct {
	config aws.Config
}

// -------------------------------------------------------------------
// Model
// -------------------------------------------------------------------

type LexV2BotLocaleBuildResourceModel struct {
	BotID      types.String `tfsdk:"bot_id"`
	BotVersion types.String `tfsdk:"bot_version"`
	LocaleID   types.String `tfsdk:"locale_id"`
	SourceHash types.String `tfsdk:"source_hash"`
	BuildID    types.String `tfsdk:"build_id"`
}

// -------------------------------------------------------------------
// Metadata / Schema
// -------------------------------------------------------------------

func (r *LexV2BotLocaleBuildResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_lexv2_bot_locale_build"
}

func (r *LexV2BotLocaleBuildResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Triggers a build of an Amazon Lex V2 bot locale using the `BuildBotLocale` API. " +
			"Polls until the locale status reaches `Built` or fails. Changing any attribute forces replacement. " +
			"Delete is a no-op — the bot owns the locale lifecycle.",

		Attributes: map[string]schema.Attribute{
			"bot_id": schema.StringAttribute{
				Required:    true,
				Description: "The identifier of the Amazon Lex V2 bot that owns the locale. Forces replacement.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"bot_version": schema.StringAttribute{
				Required:    true,
				Description: "The version of the bot to build. Typically \"DRAFT\". Forces replacement.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"locale_id": schema.StringAttribute{
				Required:    true,
				Description: "The identifier of the locale to build (e.g. \"en_US\"). Forces replacement.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"source_hash": schema.StringAttribute{
				Required:    true,
				Description: "A hash of the bot locale source (intents, slots, etc.). Changing this value triggers a rebuild via replacement.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"build_id": schema.StringAttribute{
				Computed:    true,
				Description: "A synthesized identifier for the build, formatted as \"<bot_id>/<bot_version>/<locale_id>/<source_hash>\".",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

// -------------------------------------------------------------------
// Configure
// -------------------------------------------------------------------

func (r *LexV2BotLocaleBuildResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	cfg, ok := req.ProviderData.(aws.Config)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *aws.Config, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.config = cfg
}

// -------------------------------------------------------------------
// Create
// -------------------------------------------------------------------

func (r *LexV2BotLocaleBuildResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data LexV2BotLocaleBuildResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	lexClient := lexmodelsv2.NewFromConfig(r.config)

	botID := data.BotID.ValueString()
	botVersion := data.BotVersion.ValueString()
	localeID := data.LocaleID.ValueString()
	sourceHash := data.SourceHash.ValueString()

	// Step 1: Call BuildBotLocale.
	_, err := lexClient.BuildBotLocale(ctx, &lexmodelsv2.BuildBotLocaleInput{
		BotId:      aws.String(botID),
		BotVersion: aws.String(botVersion),
		LocaleId:   aws.String(localeID),
	})
	if err != nil {
		resp.Diagnostics.AddError("Error building LexV2 bot locale", err.Error())
		return
	}

	// Step 2: Poll DescribeBotLocale until Built or failed.
	if pollErr := r.pollBotLocale(ctx, lexClient, botID, botVersion, localeID); pollErr != nil {
		resp.Diagnostics.AddError("Error waiting for LexV2 bot locale build", pollErr.Error())
		return
	}

	// Step 3: Set build_id.
	data.BuildID = types.StringValue(fmt.Sprintf("%s/%s/%s/%s", botID, botVersion, localeID, sourceHash))

	tflog.Trace(ctx, "created a resource")

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// -------------------------------------------------------------------
// Read
// -------------------------------------------------------------------

func (r *LexV2BotLocaleBuildResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data LexV2BotLocaleBuildResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	lexClient := lexmodelsv2.NewFromConfig(r.config)

	_, err := lexClient.DescribeBotLocale(ctx, &lexmodelsv2.DescribeBotLocaleInput{
		BotId:      aws.String(data.BotID.ValueString()),
		BotVersion: aws.String(data.BotVersion.ValueString()),
		LocaleId:   aws.String(data.LocaleID.ValueString()),
	})
	if err != nil {
		var nf *lextypes.ResourceNotFoundException
		if errors.As(err, &nf) {
			tflog.Warn(ctx, "LexV2 bot locale not found, removing from state", map[string]any{
				"bot_id":     data.BotID.ValueString(),
				"locale_id":  data.LocaleID.ValueString(),
			})
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError(
			"Error reading LexV2 bot locale",
			fmt.Sprintf("Could not describe bot locale %s/%s/%s: %s",
				data.BotID.ValueString(), data.BotVersion.ValueString(), data.LocaleID.ValueString(), err),
		)
		return
	}

	// Keep state as-is; do not change build_id.
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// -------------------------------------------------------------------
// Update (no in-place updates; all attributes are ForceNew)
// -------------------------------------------------------------------

func (r *LexV2BotLocaleBuildResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError("Update not supported", "awsext_lexv2_bot_locale_build does not support in-place updates; all attributes force replacement.")
}

// -------------------------------------------------------------------
// Delete (no-op)
// -------------------------------------------------------------------

func (r *LexV2BotLocaleBuildResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// No-op: the bot owns the locale lifecycle. Terraform simply removes from state.
}

// -------------------------------------------------------------------
// ImportState
// -------------------------------------------------------------------

func (r *LexV2BotLocaleBuildResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import ID format: <bot_id>/<bot_version>/<locale_id>/<source_hash>
	// SplitN into exactly 4 parts to handle bot_version like "DRAFT" (no slash),
	// locale_id like "en_US", and arbitrary source_hash with no slashes.
	parts := strings.SplitN(req.ID, "/", 4)
	if len(parts) != 4 {
		resp.Diagnostics.AddError(
			"Invalid import ID",
			fmt.Sprintf("Expected format: <bot_id>/<bot_version>/<locale_id>/<source_hash>, got: %q", req.ID),
		)
		return
	}

	var data LexV2BotLocaleBuildResourceModel
	data.BotID = types.StringValue(parts[0])
	data.BotVersion = types.StringValue(parts[1])
	data.LocaleID = types.StringValue(parts[2])
	data.SourceHash = types.StringValue(parts[3])
	data.BuildID = types.StringValue(req.ID)

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// -------------------------------------------------------------------
// Helpers
// -------------------------------------------------------------------

// pollBotLocale polls DescribeBotLocale until the status is Built or a failure is detected.
func (r *LexV2BotLocaleBuildResource) pollBotLocale(ctx context.Context, client *lexmodelsv2.Client, botID, botVersion, localeID string) error {
	const maxIterations = 24
	const sleepDuration = 5 * time.Second

	prevStatus := lextypes.BotLocaleStatus("")

	for i := 0; i < maxIterations; i++ {
		time.Sleep(sleepDuration)

		out, err := client.DescribeBotLocale(ctx, &lexmodelsv2.DescribeBotLocaleInput{
			BotId:      aws.String(botID),
			BotVersion: aws.String(botVersion),
			LocaleId:   aws.String(localeID),
		})
		if err != nil {
			return fmt.Errorf("DescribeBotLocale error: %w", err)
		}

		status := out.BotLocaleStatus
		switch status {
		case lextypes.BotLocaleStatusBuilt:
			return nil
		case lextypes.BotLocaleStatusFailed:
			return fmt.Errorf("bot locale build failed with status %s", status)
		case lextypes.BotLocaleStatusNotBuilt:
			// NotBuilt after a Building transition means the build did not succeed.
			if prevStatus == lextypes.BotLocaleStatusBuilding {
				return fmt.Errorf("bot locale transitioned from Building to NotBuilt; build did not succeed")
			}
		}

		prevStatus = status
	}

	return fmt.Errorf("timed out waiting for bot locale %s/%s/%s to reach Built status", botID, botVersion, localeID)
}
