// Generated by Claude (claude.ai) | Date: 2026-05-18 | Model: claude-sonnet-4-6
// Re-generation prompt: see Workspaces.md in project root

package provider

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/qconnect"
	qconnecttypes "github.com/aws/aws-sdk-go-v2/service/qconnect/types"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var _ resource.Resource = &QConnectAIAgentResource{}
var _ resource.ResourceWithImportState = &QConnectAIAgentResource{}

func NewQConnectAIAgentResource() resource.Resource { return &QConnectAIAgentResource{} }

type QConnectAIAgentResource struct{ config aws.Config }

type QConnectAIAgentResourceModel struct {
	AiAgentId        types.String `tfsdk:"ai_agent_id"`
	AiAgentArn       types.String `tfsdk:"ai_agent_arn"`
	AssistantId      types.String `tfsdk:"assistant_id"`
	Name             types.String `tfsdk:"name"`
	Type             types.String `tfsdk:"type"`
	Configuration    types.String `tfsdk:"configuration"`
	VisibilityStatus types.String `tfsdk:"visibility_status"`
	Description      types.String `tfsdk:"description"`
	Tags             types.Map    `tfsdk:"tags"`
}

func (r *QConnectAIAgentResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_qconnect_ai_agent"
}

func (r *QConnectAIAgentResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Creates and manages an Amazon Q in Connect AI Agent (`qconnect:CreateAIAgent`). Fields other than `configuration`, `visibility_status`, and `tags` force replacement when changed.",
		Attributes: map[string]schema.Attribute{
			"ai_agent_id": schema.StringAttribute{
				Computed:      true,
				Description:   "Service-assigned UUID of the AI Agent.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"ai_agent_arn": schema.StringAttribute{
				Computed:      true,
				Description:   "ARN of the AI Agent.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"assistant_id": schema.StringAttribute{
				Required:      true,
				Description:   "Identifier of the parent Amazon Q in Connect assistant.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required:      true,
				Description:   "Name of the AI Agent.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"type": schema.StringAttribute{
				Required:    true,
				Description: "Type of the AI Agent. One of ANSWER_RECOMMENDATION, MANUAL_SEARCH, SELF_SERVICE, EMAIL_OVERVIEW, EMAIL_RESPONSE, EMAIL_GENERATIVE_ANSWER, NOTE_TAKING, ORCHESTRATION, CASE_SUMMARIZATION.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators: []validator.String{
					stringvalidator.OneOf(
						"ANSWER_RECOMMENDATION",
						"MANUAL_SEARCH",
						"SELF_SERVICE",
						"EMAIL_OVERVIEW",
						"EMAIL_RESPONSE",
						"EMAIL_GENERATIVE_ANSWER",
						"NOTE_TAKING",
						"ORCHESTRATION",
						"CASE_SUMMARIZATION",
					),
				},
			},
			"configuration": schema.StringAttribute{
				Required: true,
				MarkdownDescription: "JSON string containing the AIAgentConfiguration payload for the chosen `type`. " +
					"The shape of the JSON varies by agent type; see the " +
					"[AWS Q in Connect API Reference](https://docs.aws.amazon.com/amazon-q-connect/latest/APIReference/) " +
					"for the fields applicable to each type. " +
					"Use `jsonencode({...})` in Terraform to avoid whitespace drift.",
				PlanModifiers: []planmodifier.String{NormalizeJSONString()},
			},
			"visibility_status": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Visibility status of the AI Agent. One of PUBLISHED or SAVED. Defaults to SAVED when omitted.",
				Validators:  []validator.String{stringvalidator.OneOf("PUBLISHED", "SAVED")},
			},
			"description": schema.StringAttribute{
				Optional:      true,
				Description:   "Description of the AI Agent.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"tags": schema.MapAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Tags to assign to the AI Agent.",
				ElementType: types.StringType,
			},
		},
	}
}

func (r *QConnectAIAgentResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	cfg, ok := req.ProviderData.(aws.Config)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *aws.Config, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.config = cfg
}

func (r *QConnectAIAgentResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data QConnectAIAgentResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := qconnect.NewFromConfig(r.config)

	agentCfg, err := aiAgentConfigFromJSON(data.Type.ValueString(), data.Configuration.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error building AI Agent configuration", err.Error())
		return
	}

	visibilityStatus := resolveVisibilityStatus(data.VisibilityStatus)

	in := &qconnect.CreateAIAgentInput{
		AssistantId:      aws.String(data.AssistantId.ValueString()),
		Name:             aws.String(data.Name.ValueString()),
		Type:             qconnecttypes.AIAgentType(data.Type.ValueString()),
		Configuration:    agentCfg,
		VisibilityStatus: visibilityStatus,
	}
	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		in.Description = aws.String(data.Description.ValueString())
	}

	tagMap, err := qconnectTagsFromMap(ctx, data.Tags)
	if err != nil {
		resp.Diagnostics.AddError("Error reading tags", err.Error())
		return
	}
	if tagMap != nil {
		in.Tags = tagMap
	}

	out, err := conn.CreateAIAgent(ctx, in)
	if err != nil {
		resp.Diagnostics.AddError("Error creating Q in Connect AI Agent", err.Error())
		return
	}

	tflog.Trace(ctx, "created qconnect AI agent")

	data.AiAgentId = types.StringValue(aws.ToString(out.AiAgent.AiAgentId))
	data.AiAgentArn = types.StringValue(aws.ToString(out.AiAgent.AiAgentArn))
	data.VisibilityStatus = types.StringValue(string(out.AiAgent.VisibilityStatus))

	cfgJSON, err := aiAgentConfigToJSON(out.AiAgent.Configuration)
	if err != nil {
		resp.Diagnostics.AddError("Error reading AI Agent configuration", err.Error())
		return
	}
	data.Configuration = types.StringValue(cfgJSON)

	if tags, err := readQConnectTags(ctx, conn, data.AiAgentArn.ValueString()); err == nil {
		data.Tags = tags
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *QConnectAIAgentResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data QConnectAIAgentResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := qconnect.NewFromConfig(r.config)

	out, err := conn.GetAIAgent(ctx, &qconnect.GetAIAgentInput{
		AssistantId: aws.String(data.AssistantId.ValueString()),
		AiAgentId:   aws.String(data.AiAgentId.ValueString()),
	})
	if err != nil {
		var nf *qconnecttypes.ResourceNotFoundException
		if errors.As(err, &nf) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading Q in Connect AI Agent", err.Error())
		return
	}
	if out == nil || out.AiAgent == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	data.AiAgentId = types.StringValue(aws.ToString(out.AiAgent.AiAgentId))
	data.AiAgentArn = types.StringValue(aws.ToString(out.AiAgent.AiAgentArn))
	data.AssistantId = types.StringValue(aws.ToString(out.AiAgent.AssistantId))
	data.Name = types.StringValue(aws.ToString(out.AiAgent.Name))
	data.Type = types.StringValue(string(out.AiAgent.Type))
	data.VisibilityStatus = types.StringValue(string(out.AiAgent.VisibilityStatus))

	if out.AiAgent.Description != nil {
		data.Description = types.StringValue(aws.ToString(out.AiAgent.Description))
	} else {
		data.Description = types.StringNull()
	}

	cfgJSON, err := aiAgentConfigToJSON(out.AiAgent.Configuration)
	if err != nil {
		resp.Diagnostics.AddError("Error reading AI Agent configuration", err.Error())
		return
	}
	data.Configuration = types.StringValue(cfgJSON)

	if tags, err := readQConnectTags(ctx, conn, data.AiAgentArn.ValueString()); err == nil {
		data.Tags = tags
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *QConnectAIAgentResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state QConnectAIAgentResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := qconnect.NewFromConfig(r.config)

	agentCfg, err := aiAgentConfigFromJSON(state.Type.ValueString(), plan.Configuration.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error building AI Agent configuration", err.Error())
		return
	}

	visibilityStatus := resolveVisibilityStatus(plan.VisibilityStatus)

	in := &qconnect.UpdateAIAgentInput{
		AssistantId:      aws.String(state.AssistantId.ValueString()),
		AiAgentId:        aws.String(state.AiAgentId.ValueString()),
		VisibilityStatus: visibilityStatus,
		Configuration:    agentCfg,
	}

	out, err := conn.UpdateAIAgent(ctx, in)
	if err != nil {
		resp.Diagnostics.AddError("Error updating Q in Connect AI Agent", err.Error())
		return
	}

	plan.VisibilityStatus = types.StringValue(string(out.AiAgent.VisibilityStatus))

	updatedCfgJSON, err := aiAgentConfigToJSON(out.AiAgent.Configuration)
	if err != nil {
		resp.Diagnostics.AddError("Error reading AI Agent configuration", err.Error())
		return
	}
	plan.Configuration = types.StringValue(updatedCfgJSON)

	if err := updateQConnectTags(ctx, conn, state.AiAgentArn.ValueString(), state.Tags, plan.Tags); err != nil {
		resp.Diagnostics.AddError("Error updating Q in Connect AI Agent tags", err.Error())
		return
	}

	if tags, err := readQConnectTags(ctx, conn, state.AiAgentArn.ValueString()); err == nil {
		plan.Tags = tags
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *QConnectAIAgentResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data QConnectAIAgentResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := qconnect.NewFromConfig(r.config)

	_, err := conn.DeleteAIAgent(ctx, &qconnect.DeleteAIAgentInput{
		AssistantId: aws.String(data.AssistantId.ValueString()),
		AiAgentId:   aws.String(data.AiAgentId.ValueString()),
	})
	if err != nil {
		var nf *qconnecttypes.ResourceNotFoundException
		if errors.As(err, &nf) {
			return
		}
		resp.Diagnostics.AddError("Error deleting Q in Connect AI Agent", err.Error())
	}
}

func (r *QConnectAIAgentResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError("Invalid import ID", "Expected <assistant_id>/<ai_agent_id>")
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("assistant_id"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("ai_agent_id"), parts[1])...)
}

// aiAgentConfigFromJSON unmarshals a JSON string into the appropriate SDK union member
// for the given agentType, then wraps it in the matching AIAgentConfiguration union member.
func aiAgentConfigFromJSON(agentType string, j string) (qconnecttypes.AIAgentConfiguration, error) {
	switch agentType {
	case "ANSWER_RECOMMENDATION":
		var v qconnecttypes.AnswerRecommendationAIAgentConfiguration
		if err := json.Unmarshal([]byte(j), &v); err != nil {
			return nil, fmt.Errorf("unmarshaling ANSWER_RECOMMENDATION configuration: %w", err)
		}
		return &qconnecttypes.AIAgentConfigurationMemberAnswerRecommendationAIAgentConfiguration{Value: v}, nil
	case "MANUAL_SEARCH":
		var v qconnecttypes.ManualSearchAIAgentConfiguration
		if err := json.Unmarshal([]byte(j), &v); err != nil {
			return nil, fmt.Errorf("unmarshaling MANUAL_SEARCH configuration: %w", err)
		}
		return &qconnecttypes.AIAgentConfigurationMemberManualSearchAIAgentConfiguration{Value: v}, nil
	case "SELF_SERVICE":
		var v qconnecttypes.SelfServiceAIAgentConfiguration
		if err := json.Unmarshal([]byte(j), &v); err != nil {
			return nil, fmt.Errorf("unmarshaling SELF_SERVICE configuration: %w", err)
		}
		return &qconnecttypes.AIAgentConfigurationMemberSelfServiceAIAgentConfiguration{Value: v}, nil
	case "EMAIL_OVERVIEW":
		var v qconnecttypes.EmailOverviewAIAgentConfiguration
		if err := json.Unmarshal([]byte(j), &v); err != nil {
			return nil, fmt.Errorf("unmarshaling EMAIL_OVERVIEW configuration: %w", err)
		}
		return &qconnecttypes.AIAgentConfigurationMemberEmailOverviewAIAgentConfiguration{Value: v}, nil
	case "EMAIL_RESPONSE":
		var v qconnecttypes.EmailResponseAIAgentConfiguration
		if err := json.Unmarshal([]byte(j), &v); err != nil {
			return nil, fmt.Errorf("unmarshaling EMAIL_RESPONSE configuration: %w", err)
		}
		return &qconnecttypes.AIAgentConfigurationMemberEmailResponseAIAgentConfiguration{Value: v}, nil
	case "EMAIL_GENERATIVE_ANSWER":
		var v qconnecttypes.EmailGenerativeAnswerAIAgentConfiguration
		if err := json.Unmarshal([]byte(j), &v); err != nil {
			return nil, fmt.Errorf("unmarshaling EMAIL_GENERATIVE_ANSWER configuration: %w", err)
		}
		return &qconnecttypes.AIAgentConfigurationMemberEmailGenerativeAnswerAIAgentConfiguration{Value: v}, nil
	case "NOTE_TAKING":
		var v qconnecttypes.NoteTakingAIAgentConfiguration
		if err := json.Unmarshal([]byte(j), &v); err != nil {
			return nil, fmt.Errorf("unmarshaling NOTE_TAKING configuration: %w", err)
		}
		return &qconnecttypes.AIAgentConfigurationMemberNoteTakingAIAgentConfiguration{Value: v}, nil
	case "ORCHESTRATION":
		var v qconnecttypes.OrchestrationAIAgentConfiguration
		if err := json.Unmarshal([]byte(j), &v); err != nil {
			return nil, fmt.Errorf("unmarshaling ORCHESTRATION configuration: %w", err)
		}
		return &qconnecttypes.AIAgentConfigurationMemberOrchestrationAIAgentConfiguration{Value: v}, nil
	case "CASE_SUMMARIZATION":
		var v qconnecttypes.CaseSummarizationAIAgentConfiguration
		if err := json.Unmarshal([]byte(j), &v); err != nil {
			return nil, fmt.Errorf("unmarshaling CASE_SUMMARIZATION configuration: %w", err)
		}
		return &qconnecttypes.AIAgentConfigurationMemberCaseSummarizationAIAgentConfiguration{Value: v}, nil
	default:
		return nil, fmt.Errorf("unsupported AI Agent type: %s", agentType)
	}
}

// aiAgentConfigToJSON serializes the SDK AIAgentConfiguration union back to a JSON string.
func aiAgentConfigToJSON(cfg qconnecttypes.AIAgentConfiguration) (string, error) {
	if cfg == nil {
		return "{}", nil
	}
	var v any
	switch c := cfg.(type) {
	case *qconnecttypes.AIAgentConfigurationMemberAnswerRecommendationAIAgentConfiguration:
		v = c.Value
	case *qconnecttypes.AIAgentConfigurationMemberManualSearchAIAgentConfiguration:
		v = c.Value
	case *qconnecttypes.AIAgentConfigurationMemberSelfServiceAIAgentConfiguration:
		v = c.Value
	case *qconnecttypes.AIAgentConfigurationMemberEmailOverviewAIAgentConfiguration:
		v = c.Value
	case *qconnecttypes.AIAgentConfigurationMemberEmailResponseAIAgentConfiguration:
		v = c.Value
	case *qconnecttypes.AIAgentConfigurationMemberEmailGenerativeAnswerAIAgentConfiguration:
		v = c.Value
	case *qconnecttypes.AIAgentConfigurationMemberNoteTakingAIAgentConfiguration:
		v = c.Value
	case *qconnecttypes.AIAgentConfigurationMemberOrchestrationAIAgentConfiguration:
		v = c.Value
	case *qconnecttypes.AIAgentConfigurationMemberCaseSummarizationAIAgentConfiguration:
		v = c.Value
	default:
		return "", fmt.Errorf("unsupported AI Agent configuration type: %T", cfg)
	}
	b, err := json.Marshal(v)
	if err != nil {
		return "", fmt.Errorf("marshaling AI Agent configuration: %w", err)
	}
	return string(b), nil
}
