// Generated by Claude (claude.ai) | Date: 2026-05-18 | Model: claude-sonnet-4-6
// Re-generation prompt: see Workspaces.md in project root

package provider

import (
	qconnecttypes "github.com/aws/aws-sdk-go-v2/service/qconnect/types"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// objectAsOptions returns the framework's no-op object decode options.
// Centralized so future resources can adjust (e.g. IgnoreNull) in one place.
func objectAsOptions() basetypes.ObjectAsOptions {
	return basetypes.ObjectAsOptions{}
}

// resolveVisibilityStatus returns the VisibilityStatus from the given string value,
// defaulting to VisibilityStatusSaved when the value is null, unknown, or empty.
func resolveVisibilityStatus(v types.String) qconnecttypes.VisibilityStatus {
	if !v.IsNull() && !v.IsUnknown() && v.ValueString() != "" {
		return qconnecttypes.VisibilityStatus(v.ValueString())
	}
	return qconnecttypes.VisibilityStatusSaved
}
