// Generated by Claude (claude.ai) | Date: 2026-05-18 | Model: claude-sonnet-4-6
// Re-generation prompt: see Workspaces.ai in project root

package provider

import (
	"context"
	"errors"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/qconnect"
	qconnecttypes "github.com/aws/aws-sdk-go-v2/service/qconnect/types"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var _ resource.Resource = &QConnectAssistantResource{}
var _ resource.ResourceWithImportState = &QConnectAssistantResource{}

func NewQConnectAssistantResource() resource.Resource { return &QConnectAssistantResource{} }

type QConnectAssistantResource struct{ config aws.Config }

type QConnectAssistantResourceModel struct {
	AssistantId  types.String `tfsdk:"assistant_id"`
	AssistantArn types.String `tfsdk:"assistant_arn"`
	Name         types.String `tfsdk:"name"`
	Type         types.String `tfsdk:"type"`
	Description  types.String `tfsdk:"description"`
	Tags         types.Map    `tfsdk:"tags"`
}

func (r *QConnectAssistantResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_qconnect_assistant"
}

func (r *QConnectAssistantResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Creates and manages an Amazon Q in Connect assistant (qconnect:CreateAssistant). No update API exists for non-tag fields, so most attributes force replacement.",
		Attributes: map[string]schema.Attribute{
			"assistant_id": schema.StringAttribute{
				Computed:      true,
				Description:   "Service-assigned UUID of the assistant.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"assistant_arn": schema.StringAttribute{
				Computed:      true,
				Description:   "ARN of the assistant.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"name": schema.StringAttribute{
				Required:      true,
				Description:   "Friendly name of the assistant.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators:    []validator.String{stringvalidator.LengthBetween(1, 255)},
			},
			"type": schema.StringAttribute{
				Required:      true,
				Description:   "Currently the only supported value is AGENT.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators:    []validator.String{stringvalidator.OneOf("AGENT")},
			},
			"description": schema.StringAttribute{
				Optional:      true,
				Description:   "Description of the assistant.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"tags": schema.MapAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Tags to assign to the assistant.",
				ElementType: types.StringType,
			},
		},
	}
}

func (r *QConnectAssistantResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	cfg, ok := req.ProviderData.(aws.Config)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *aws.Config, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.config = cfg
}

func (r *QConnectAssistantResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data QConnectAssistantResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := qconnect.NewFromConfig(r.config)

	in := &qconnect.CreateAssistantInput{
		Name: aws.String(data.Name.ValueString()),
		Type: qconnecttypes.AssistantType(data.Type.ValueString()),
	}
	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		in.Description = aws.String(data.Description.ValueString())
	}
	tagMap, err := qconnectTagsFromMap(ctx, data.Tags)
	if err != nil {
		resp.Diagnostics.AddError("Error reading tags", err.Error())
		return
	}
	if tagMap != nil {
		in.Tags = tagMap
	}

	out, err := conn.CreateAssistant(ctx, in)
	if err != nil {
		resp.Diagnostics.AddError("Error creating Q in Connect assistant", err.Error())
		return
	}

	tflog.Trace(ctx, "created qconnect assistant")

	data.AssistantId = types.StringValue(aws.ToString(out.Assistant.AssistantId))
	data.AssistantArn = types.StringValue(aws.ToString(out.Assistant.AssistantArn))

	if tags, err := readQConnectTags(ctx, conn, data.AssistantArn.ValueString()); err == nil {
		data.Tags = tags
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *QConnectAssistantResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data QConnectAssistantResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := qconnect.NewFromConfig(r.config)

	out, err := conn.GetAssistant(ctx, &qconnect.GetAssistantInput{
		AssistantId: aws.String(data.AssistantId.ValueString()),
	})
	if err != nil {
		var nf *qconnecttypes.ResourceNotFoundException
		if errors.As(err, &nf) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading Q in Connect assistant", err.Error())
		return
	}
	if out == nil || out.Assistant == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	data.AssistantId = types.StringValue(aws.ToString(out.Assistant.AssistantId))
	data.AssistantArn = types.StringValue(aws.ToString(out.Assistant.AssistantArn))
	data.Name = types.StringValue(aws.ToString(out.Assistant.Name))
	data.Type = types.StringValue(string(out.Assistant.Type))
	if out.Assistant.Description != nil {
		data.Description = types.StringValue(aws.ToString(out.Assistant.Description))
	} else {
		data.Description = types.StringNull()
	}

	if tags, err := readQConnectTags(ctx, conn, data.AssistantArn.ValueString()); err == nil {
		data.Tags = tags
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *QConnectAssistantResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state QConnectAssistantResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := qconnect.NewFromConfig(r.config)

	if err := updateQConnectTags(ctx, conn, state.AssistantArn.ValueString(), state.Tags, plan.Tags); err != nil {
		resp.Diagnostics.AddError("Error updating Q in Connect assistant tags", err.Error())
		return
	}

	if tags, err := readQConnectTags(ctx, conn, state.AssistantArn.ValueString()); err == nil {
		plan.Tags = tags
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *QConnectAssistantResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data QConnectAssistantResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := qconnect.NewFromConfig(r.config)

	_, err := conn.DeleteAssistant(ctx, &qconnect.DeleteAssistantInput{
		AssistantId: aws.String(data.AssistantId.ValueString()),
	})
	if err != nil {
		var nf *qconnecttypes.ResourceNotFoundException
		if errors.As(err, &nf) {
			return
		}
		resp.Diagnostics.AddError("Error deleting Q in Connect assistant", err.Error())
	}
}

func (r *QConnectAssistantResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("assistant_id"), req, resp)
}
