// Generated by Claude (claude.ai) | Date: 2026-05-18 | Model: claude-sonnet-4-6
// Re-generation prompt: see Workspaces.md in project root

package provider

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/qconnect"
	qconnecttypes "github.com/aws/aws-sdk-go-v2/service/qconnect/types"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var _ resource.Resource = &QConnectAIGuardrailVersionResource{}
var _ resource.ResourceWithImportState = &QConnectAIGuardrailVersionResource{}

func NewQConnectAIGuardrailVersionResource() resource.Resource {
	return &QConnectAIGuardrailVersionResource{}
}

type QConnectAIGuardrailVersionResource struct{ config aws.Config }

type QConnectAIGuardrailVersionResourceModel struct {
	AssistantId            types.String `tfsdk:"assistant_id"`
	AiGuardrailId          types.String `tfsdk:"ai_guardrail_id"`
	ModifiedTimeSeconds    types.Int64  `tfsdk:"modified_time_seconds"`
	VersionNumber          types.Int64  `tfsdk:"version_number"`
	GuardrailArnWithVersion types.String `tfsdk:"guardrail_arn_with_version"`
}

// ── Metadata ─────────────────────────────────────────────────────────────────

func (r *QConnectAIGuardrailVersionResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_qconnect_ai_guardrail_version"
}

// ── Schema ────────────────────────────────────────────────────────────────────

func (r *QConnectAIGuardrailVersionResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Creates a version snapshot of an Amazon Q in Connect AI Guardrail (qconnect:CreateAIGuardrailVersion). Versions are immutable; all inputs are ForceNew. No update API exists.",
		Attributes: map[string]schema.Attribute{
			"assistant_id": schema.StringAttribute{
				Required:      true,
				Description:   "Identifier of the parent Amazon Q in Connect assistant.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"ai_guardrail_id": schema.StringAttribute{
				Required:      true,
				Description:   "Identifier of the AI Guardrail to version.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"modified_time_seconds": schema.Int64Attribute{
				Optional:    true,
				Description: "Unix epoch seconds of the last-known modification time of the guardrail. When set, the API rejects the version create if the guardrail has been modified more recently, preventing accidental version creation on stale configs.",
				PlanModifiers: []planmodifier.Int64{int64planmodifier.RequiresReplace()},
			},
			"version_number": schema.Int64Attribute{
				Computed:      true,
				Description:   "Service-assigned version number of the AI Guardrail version.",
				PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()},
			},
			"guardrail_arn_with_version": schema.StringAttribute{
				Computed:      true,
				Description:   "ARN of the AI Guardrail qualified with the version number (<ai_guardrail_arn>:<version_number>). Use this in AI agent configurations that require a specific guardrail version.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
		},
	}
}

// ── Configure ─────────────────────────────────────────────────────────────────

func (r *QConnectAIGuardrailVersionResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	cfg, ok := req.ProviderData.(aws.Config)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *aws.Config, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.config = cfg
}

// ── Create ────────────────────────────────────────────────────────────────────

func (r *QConnectAIGuardrailVersionResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data QConnectAIGuardrailVersionResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := qconnect.NewFromConfig(r.config)

	in := &qconnect.CreateAIGuardrailVersionInput{
		AssistantId:   aws.String(data.AssistantId.ValueString()),
		AiGuardrailId: aws.String(data.AiGuardrailId.ValueString()),
	}
	if !data.ModifiedTimeSeconds.IsNull() && !data.ModifiedTimeSeconds.IsUnknown() {
		t := time.Unix(data.ModifiedTimeSeconds.ValueInt64(), 0)
		in.ModifiedTime = &t
	}

	out, err := conn.CreateAIGuardrailVersion(ctx, in)
	if err != nil {
		resp.Diagnostics.AddError("Error creating Q in Connect AI Guardrail version", err.Error())
		return
	}

	tflog.Trace(ctx, "created qconnect AI guardrail version")

	versionNumber := aws.ToInt64(out.VersionNumber)
	data.VersionNumber = types.Int64Value(versionNumber)

	guardrailArn := ""
	if out.AiGuardrail != nil {
		guardrailArn = aws.ToString(out.AiGuardrail.AiGuardrailArn)
	}
	data.GuardrailArnWithVersion = types.StringValue(fmt.Sprintf("%s:%d", guardrailArn, versionNumber))

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// ── Read ──────────────────────────────────────────────────────────────────────

func (r *QConnectAIGuardrailVersionResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data QConnectAIGuardrailVersionResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := qconnect.NewFromConfig(r.config)

	// The SDK's GetAIGuardrailInput does not have a dedicated version field.
	// Versions are addressed by appending :<version_number> to the AiGuardrailId.
	versionedId := fmt.Sprintf("%s:%d", data.AiGuardrailId.ValueString(), data.VersionNumber.ValueInt64())

	out, err := conn.GetAIGuardrail(ctx, &qconnect.GetAIGuardrailInput{
		AssistantId:   aws.String(data.AssistantId.ValueString()),
		AiGuardrailId: aws.String(versionedId),
	})
	if err != nil {
		var nf *qconnecttypes.ResourceNotFoundException
		if errors.As(err, &nf) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading Q in Connect AI Guardrail version", err.Error())
		return
	}
	if out == nil || out.AiGuardrail == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	versionNumber := data.VersionNumber.ValueInt64()
	if out.VersionNumber != nil {
		versionNumber = aws.ToInt64(out.VersionNumber)
	}
	data.VersionNumber = types.Int64Value(versionNumber)
	data.GuardrailArnWithVersion = types.StringValue(
		fmt.Sprintf("%s:%d", aws.ToString(out.AiGuardrail.AiGuardrailArn), versionNumber),
	)

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// ── Update ────────────────────────────────────────────────────────────────────
// All user-facing attributes are ForceNew or Computed; Terraform handles
// replacement automatically. This method is required by the resource.Resource
// interface but will never be called in practice.

func (r *QConnectAIGuardrailVersionResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// No-op: all attributes are ForceNew or Computed.
	resp.Diagnostics.AddError(
		"Update not supported",
		"awsext_qconnect_ai_guardrail_version does not support in-place updates. All changes force resource replacement.",
	)
}

// ── Delete ────────────────────────────────────────────────────────────────────

func (r *QConnectAIGuardrailVersionResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data QConnectAIGuardrailVersionResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := qconnect.NewFromConfig(r.config)

	_, err := conn.DeleteAIGuardrailVersion(ctx, &qconnect.DeleteAIGuardrailVersionInput{
		AssistantId:   aws.String(data.AssistantId.ValueString()),
		AiGuardrailId: aws.String(data.AiGuardrailId.ValueString()),
		VersionNumber: aws.Int64(data.VersionNumber.ValueInt64()),
	})
	if err != nil {
		var nf *qconnecttypes.ResourceNotFoundException
		if errors.As(err, &nf) {
			return
		}
		resp.Diagnostics.AddError("Error deleting Q in Connect AI Guardrail version", err.Error())
	}
}

// ── ImportState ───────────────────────────────────────────────────────────────

func (r *QConnectAIGuardrailVersionResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, "/")
	if len(parts) != 3 || parts[0] == "" || parts[1] == "" || parts[2] == "" {
		resp.Diagnostics.AddError(
			"Invalid import ID",
			"Expected <assistant_id>/<ai_guardrail_id>/<version_number>",
		)
		return
	}

	versionNumber, err := strconv.ParseInt(parts[2], 10, 64)
	if err != nil {
		resp.Diagnostics.AddError(
			"Invalid version_number in import ID",
			fmt.Sprintf("Could not parse %q as an integer: %s", parts[2], err),
		)
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("assistant_id"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("ai_guardrail_id"), parts[1])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("version_number"), versionNumber)...)
}
