// Generated by Claude (claude.ai) | Date: 2026-05-18 | Model: claude-sonnet-4-6
// Re-generation prompt: see Workspaces.md in project root

package provider

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/qconnect"
	qconnecttypes "github.com/aws/aws-sdk-go-v2/service/qconnect/types"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var _ resource.Resource = &QConnectAIPromptResource{}
var _ resource.ResourceWithImportState = &QConnectAIPromptResource{}

func NewQConnectAiPromptResource() resource.Resource { return &QConnectAIPromptResource{} }

type QConnectAIPromptResource struct{ config aws.Config }

type QConnectAIPromptResourceModel struct {
	AiPromptId            types.String `tfsdk:"ai_prompt_id"`
	AiPromptArn           types.String `tfsdk:"ai_prompt_arn"`
	AssistantId           types.String `tfsdk:"assistant_id"`
	Name                  types.String `tfsdk:"name"`
	Type                  types.String `tfsdk:"type"`
	ApiFormat             types.String `tfsdk:"api_format"`
	ModelId               types.String `tfsdk:"model_id"`
	TemplateType          types.String `tfsdk:"template_type"`
	TemplateConfiguration types.String `tfsdk:"template_configuration"`
	VisibilityStatus      types.String `tfsdk:"visibility_status"`
	Description           types.String `tfsdk:"description"`
	Tags                  types.Map    `tfsdk:"tags"`
}

func (r *QConnectAIPromptResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_qconnect_ai_prompt"
}

func (r *QConnectAIPromptResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Creates and manages an Amazon Q in Connect AI Prompt (qconnect:CreateAIPrompt). Fields other than `template_configuration`, `visibility_status`, and `tags` force replacement when changed.",
		Attributes: map[string]schema.Attribute{
			"ai_prompt_id": schema.StringAttribute{
				Computed:      true,
				Description:   "Service-assigned UUID of the AI Prompt.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"ai_prompt_arn": schema.StringAttribute{
				Computed:      true,
				Description:   "ARN of the AI Prompt.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"assistant_id": schema.StringAttribute{
				Required:      true,
				Description:   "Identifier of the parent Amazon Q in Connect assistant.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required:      true,
				Description:   "Name of the AI Prompt.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators:    []validator.String{stringvalidator.LengthBetween(1, 255)},
			},
			"type": schema.StringAttribute{
				Required:    true,
				Description: "Type of the AI Prompt, indicating its purpose. Examples: ANSWER_GENERATION, QUERY_REFORMULATION, INTENT_LABELING_GENERATION, SELF_SERVICE_PRE_PROCESSING, SELF_SERVICE_ANSWER_GENERATION, ORCHESTRATION, NOTE_TAKING.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"api_format": schema.StringAttribute{
				Required:    true,
				Description: "API format for the AI Prompt. One of ANTHROPIC_CLAUDE_MESSAGES, ANTHROPIC_CLAUDE_TEXT_COMPLETIONS, MESSAGES, TEXT_COMPLETIONS. The ANTHROPIC_CLAUDE_* variants are deprecated; prefer MESSAGES or TEXT_COMPLETIONS.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators: []validator.String{
					stringvalidator.OneOf(
						"ANTHROPIC_CLAUDE_MESSAGES",
						"ANTHROPIC_CLAUDE_TEXT_COMPLETIONS",
						"MESSAGES",
						"TEXT_COMPLETIONS",
					),
				},
			},
			"model_id": schema.StringAttribute{
				Required:      true,
				Description:   "Identifier of the model used for this AI Prompt (e.g. anthropic.claude-3-5-sonnet-20240620-v1:0).",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"template_type": schema.StringAttribute{
				Required:      true,
				Description:   "Type of the prompt template. Currently the only supported value is TEXT.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators:    []validator.String{stringvalidator.OneOf("TEXT")},
			},
			"template_configuration": schema.StringAttribute{
				Required: true,
				MarkdownDescription: "JSON document representing the template configuration for this AI Prompt. " +
					"For `template_type = \"TEXT\"` this is a JSON object with a `text` key containing the YAML prompt. " +
					"Whitespace and key-order differences between the plan and the API-returned form are suppressed.",
				PlanModifiers: []planmodifier.String{NormalizeJSONString()},
			},
			"visibility_status": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Visibility status of the AI Prompt. One of PUBLISHED or SAVED. Defaults to SAVED when omitted.",
				Validators:  []validator.String{stringvalidator.OneOf("PUBLISHED", "SAVED")},
			},
			"description": schema.StringAttribute{
				Optional:      true,
				Description:   "Description of the AI Prompt.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"tags": schema.MapAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Tags to assign to the AI Prompt.",
				ElementType: types.StringType,
			},
		},
	}
}

func (r *QConnectAIPromptResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	cfg, ok := req.ProviderData.(aws.Config)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *aws.Config, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.config = cfg
}

func (r *QConnectAIPromptResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data QConnectAIPromptResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := qconnect.NewFromConfig(r.config)

	templateConfig, err := buildTemplateConfiguration(data.TemplateType.ValueString(), data.TemplateConfiguration.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error building template configuration", err.Error())
		return
	}

	visibilityStatus := qconnecttypes.VisibilityStatusSaved
	if !data.VisibilityStatus.IsNull() && !data.VisibilityStatus.IsUnknown() && data.VisibilityStatus.ValueString() != "" {
		visibilityStatus = qconnecttypes.VisibilityStatus(data.VisibilityStatus.ValueString())
	}

	in := &qconnect.CreateAIPromptInput{
		AssistantId:           aws.String(data.AssistantId.ValueString()),
		Name:                  aws.String(data.Name.ValueString()),
		Type:                  qconnecttypes.AIPromptType(data.Type.ValueString()),
		ApiFormat:             qconnecttypes.AIPromptAPIFormat(data.ApiFormat.ValueString()),
		ModelId:               aws.String(data.ModelId.ValueString()),
		TemplateType:          qconnecttypes.AIPromptTemplateType(data.TemplateType.ValueString()),
		TemplateConfiguration: templateConfig,
		VisibilityStatus:      visibilityStatus,
	}
	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		in.Description = aws.String(data.Description.ValueString())
	}

	tagMap, err := qconnectTagsFromMap(ctx, data.Tags)
	if err != nil {
		resp.Diagnostics.AddError("Error reading tags", err.Error())
		return
	}
	if tagMap != nil {
		in.Tags = tagMap
	}

	out, err := conn.CreateAIPrompt(ctx, in)
	if err != nil {
		resp.Diagnostics.AddError("Error creating Q in Connect AI Prompt", err.Error())
		return
	}

	tflog.Trace(ctx, "created qconnect AI prompt")

	data.AiPromptId = types.StringValue(aws.ToString(out.AiPrompt.AiPromptId))
	data.AiPromptArn = types.StringValue(aws.ToString(out.AiPrompt.AiPromptArn))
	data.VisibilityStatus = types.StringValue(string(out.AiPrompt.VisibilityStatus))

	// Normalize the template_configuration JSON from the API response.
	if normalized, err := flattenTemplateConfiguration(out.AiPrompt.TemplateConfiguration); err == nil {
		data.TemplateConfiguration = types.StringValue(normalized)
	}

	if tags, err := readQConnectTags(ctx, conn, data.AiPromptArn.ValueString()); err == nil {
		data.Tags = tags
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *QConnectAIPromptResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data QConnectAIPromptResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := qconnect.NewFromConfig(r.config)

	out, err := conn.GetAIPrompt(ctx, &qconnect.GetAIPromptInput{
		AssistantId: aws.String(data.AssistantId.ValueString()),
		AiPromptId:  aws.String(data.AiPromptId.ValueString()),
	})
	if err != nil {
		var nf *qconnecttypes.ResourceNotFoundException
		if errors.As(err, &nf) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading Q in Connect AI Prompt", err.Error())
		return
	}
	if out == nil || out.AiPrompt == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	data.AiPromptId = types.StringValue(aws.ToString(out.AiPrompt.AiPromptId))
	data.AiPromptArn = types.StringValue(aws.ToString(out.AiPrompt.AiPromptArn))
	data.AssistantId = types.StringValue(aws.ToString(out.AiPrompt.AssistantId))
	data.Name = types.StringValue(aws.ToString(out.AiPrompt.Name))
	data.Type = types.StringValue(string(out.AiPrompt.Type))
	data.ApiFormat = types.StringValue(string(out.AiPrompt.ApiFormat))
	data.ModelId = types.StringValue(aws.ToString(out.AiPrompt.ModelId))
	data.TemplateType = types.StringValue(string(out.AiPrompt.TemplateType))
	data.VisibilityStatus = types.StringValue(string(out.AiPrompt.VisibilityStatus))

	if out.AiPrompt.Description != nil {
		data.Description = types.StringValue(aws.ToString(out.AiPrompt.Description))
	} else {
		data.Description = types.StringNull()
	}

	if normalized, err := flattenTemplateConfiguration(out.AiPrompt.TemplateConfiguration); err == nil {
		data.TemplateConfiguration = types.StringValue(normalized)
	}

	if tags, err := readQConnectTags(ctx, conn, data.AiPromptArn.ValueString()); err == nil {
		data.Tags = tags
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *QConnectAIPromptResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state QConnectAIPromptResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := qconnect.NewFromConfig(r.config)

	templateConfig, err := buildTemplateConfiguration(plan.TemplateType.ValueString(), plan.TemplateConfiguration.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error building template configuration", err.Error())
		return
	}

	visibilityStatus := qconnecttypes.VisibilityStatusSaved
	if !plan.VisibilityStatus.IsNull() && !plan.VisibilityStatus.IsUnknown() && plan.VisibilityStatus.ValueString() != "" {
		visibilityStatus = qconnecttypes.VisibilityStatus(plan.VisibilityStatus.ValueString())
	}

	in := &qconnect.UpdateAIPromptInput{
		AssistantId:           aws.String(state.AssistantId.ValueString()),
		AiPromptId:            aws.String(state.AiPromptId.ValueString()),
		VisibilityStatus:      visibilityStatus,
		TemplateConfiguration: templateConfig,
	}

	out, err := conn.UpdateAIPrompt(ctx, in)
	if err != nil {
		resp.Diagnostics.AddError("Error updating Q in Connect AI Prompt", err.Error())
		return
	}

	plan.VisibilityStatus = types.StringValue(string(out.AiPrompt.VisibilityStatus))

	if normalized, err := flattenTemplateConfiguration(out.AiPrompt.TemplateConfiguration); err == nil {
		plan.TemplateConfiguration = types.StringValue(normalized)
	}

	if err := updateQConnectTags(ctx, conn, state.AiPromptArn.ValueString(), state.Tags, plan.Tags); err != nil {
		resp.Diagnostics.AddError("Error updating Q in Connect AI Prompt tags", err.Error())
		return
	}

	if tags, err := readQConnectTags(ctx, conn, state.AiPromptArn.ValueString()); err == nil {
		plan.Tags = tags
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *QConnectAIPromptResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data QConnectAIPromptResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := qconnect.NewFromConfig(r.config)

	_, err := conn.DeleteAIPrompt(ctx, &qconnect.DeleteAIPromptInput{
		AssistantId: aws.String(data.AssistantId.ValueString()),
		AiPromptId:  aws.String(data.AiPromptId.ValueString()),
	})
	if err != nil {
		var nf *qconnecttypes.ResourceNotFoundException
		if errors.As(err, &nf) {
			return
		}
		resp.Diagnostics.AddError("Error deleting Q in Connect AI Prompt", err.Error())
	}
}

func (r *QConnectAIPromptResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, "/")
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid import ID", "Expected <assistant_id>/<ai_prompt_id>")
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("assistant_id"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("ai_prompt_id"), parts[1])...)
}

// buildTemplateConfiguration constructs the SDK union type for TemplateConfiguration.
// Currently only "TEXT" template type is supported.
func buildTemplateConfiguration(templateType, jsonStr string) (qconnecttypes.AIPromptTemplateConfiguration, error) {
	switch templateType {
	case "TEXT":
		// The JSON string represents the content; we store/pass the raw JSON as the text.
		return &qconnecttypes.AIPromptTemplateConfigurationMemberTextFullAIPromptEditTemplateConfiguration{
			Value: qconnecttypes.TextFullAIPromptEditTemplateConfiguration{
				Text: aws.String(jsonStr),
			},
		}, nil
	default:
		return nil, fmt.Errorf("unsupported template_type %q", templateType)
	}
}

// flattenTemplateConfiguration extracts a JSON string from the SDK union type.
func flattenTemplateConfiguration(cfg qconnecttypes.AIPromptTemplateConfiguration) (string, error) {
	if cfg == nil {
		return "", fmt.Errorf("template configuration is nil")
	}
	switch v := cfg.(type) {
	case *qconnecttypes.AIPromptTemplateConfigurationMemberTextFullAIPromptEditTemplateConfiguration:
		text := aws.ToString(v.Value.Text)
		// If the text is already valid JSON, return it normalized.
		if normalized, err := canonicalizeJSON(text); err == nil {
			return normalized, nil
		}
		// Otherwise treat as a plain string and marshal it to JSON.
		raw, err := json.Marshal(text)
		if err != nil {
			return "", err
		}
		return string(raw), nil
	default:
		return "", fmt.Errorf("unsupported template configuration type %T", cfg)
	}
}
