// Generated by Claude (claude.ai) | Date: 2026-05-18 | Model: claude-sonnet-4-6
// Re-generation prompt: see Workspaces.md in project root

package provider

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/qconnect"
	qconnecttypes "github.com/aws/aws-sdk-go-v2/service/qconnect/types"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var _ resource.Resource = &QConnectAIGuardrailResource{}
var _ resource.ResourceWithImportState = &QConnectAIGuardrailResource{}

func NewQConnectAIGuardrailResource() resource.Resource { return &QConnectAIGuardrailResource{} }

type QConnectAIGuardrailResource struct{ config aws.Config }

// ── top-level model ──────────────────────────────────────────────────────────

type QConnectAIGuardrailResourceModel struct {
	AiGuardrailId                    types.String `tfsdk:"ai_guardrail_id"`
	AiGuardrailArn                   types.String `tfsdk:"ai_guardrail_arn"`
	AssistantId                      types.String `tfsdk:"assistant_id"`
	Name                             types.String `tfsdk:"name"`
	BlockedInputMessaging            types.String `tfsdk:"blocked_input_messaging"`
	BlockedOutputsMessaging          types.String `tfsdk:"blocked_outputs_messaging"`
	VisibilityStatus                 types.String `tfsdk:"visibility_status"`
	Description                      types.String `tfsdk:"description"`
	Tags                             types.Map    `tfsdk:"tags"`
	ContentPolicyConfig              types.Object `tfsdk:"content_policy_config"`
	TopicPolicyConfig                types.Object `tfsdk:"topic_policy_config"`
	WordPolicyConfig                 types.Object `tfsdk:"word_policy_config"`
	SensitiveInformationPolicyConfig types.Object `tfsdk:"sensitive_information_policy_config"`
	ContextualGroundingPolicyConfig  types.Object `tfsdk:"contextual_grounding_policy_config"`
}

// ── nested model structs ─────────────────────────────────────────────────────

type contentPolicyConfigModel struct {
	FiltersConfig types.List `tfsdk:"filters_config"`
}

type contentFilterConfigModel struct {
	InputStrength  types.String `tfsdk:"input_strength"`
	OutputStrength types.String `tfsdk:"output_strength"`
	Type           types.String `tfsdk:"type"`
}

type topicPolicyConfigModel struct {
	TopicsConfig types.List `tfsdk:"topics_config"`
}

type topicConfigModel struct {
	Name       types.String `tfsdk:"name"`
	Definition types.String `tfsdk:"definition"`
	Type       types.String `tfsdk:"type"`
	Examples   types.List   `tfsdk:"examples"`
}

type wordPolicyConfigModel struct {
	WordsConfig            types.List `tfsdk:"words_config"`
	ManagedWordListsConfig types.List `tfsdk:"managed_word_lists_config"`
}

type wordConfigModel struct {
	Text types.String `tfsdk:"text"`
}

type managedWordsConfigModel struct {
	Type types.String `tfsdk:"type"`
}

type sensitiveInformationPolicyConfigModel struct {
	PiiEntitiesConfig types.List `tfsdk:"pii_entities_config"`
	RegexesConfig     types.List `tfsdk:"regexes_config"`
}

type piiEntityConfigModel struct {
	Type   types.String `tfsdk:"type"`
	Action types.String `tfsdk:"action"`
}

type regexConfigModel struct {
	Name        types.String `tfsdk:"name"`
	Pattern     types.String `tfsdk:"pattern"`
	Action      types.String `tfsdk:"action"`
	Description types.String `tfsdk:"description"`
}

type contextualGroundingPolicyConfigModel struct {
	FiltersConfig types.List `tfsdk:"filters_config"`
}

type contextualGroundingFilterConfigModel struct {
	Threshold types.Float64 `tfsdk:"threshold"`
	Type      types.String  `tfsdk:"type"`
}

// ── attribute-type maps (used for null types.Object construction) ─────────────

var contentFilterConfigAttrTypes = map[string]attr.Type{
	"input_strength":  types.StringType,
	"output_strength": types.StringType,
	"type":            types.StringType,
}

var contentPolicyConfigAttrTypes = map[string]attr.Type{
	"filters_config": types.ListType{ElemType: types.ObjectType{AttrTypes: contentFilterConfigAttrTypes}},
}

var topicConfigAttrTypes = map[string]attr.Type{
	"name":       types.StringType,
	"definition": types.StringType,
	"type":       types.StringType,
	"examples":   types.ListType{ElemType: types.StringType},
}

var topicPolicyConfigAttrTypes = map[string]attr.Type{
	"topics_config": types.ListType{ElemType: types.ObjectType{AttrTypes: topicConfigAttrTypes}},
}

var wordConfigAttrTypes = map[string]attr.Type{
	"text": types.StringType,
}

var managedWordsConfigAttrTypes = map[string]attr.Type{
	"type": types.StringType,
}

var wordPolicyConfigAttrTypes = map[string]attr.Type{
	"words_config":             types.ListType{ElemType: types.ObjectType{AttrTypes: wordConfigAttrTypes}},
	"managed_word_lists_config": types.ListType{ElemType: types.ObjectType{AttrTypes: managedWordsConfigAttrTypes}},
}

var piiEntityConfigAttrTypes = map[string]attr.Type{
	"type":   types.StringType,
	"action": types.StringType,
}

var regexConfigAttrTypes = map[string]attr.Type{
	"name":        types.StringType,
	"pattern":     types.StringType,
	"action":      types.StringType,
	"description": types.StringType,
}

var sensitiveInformationPolicyConfigAttrTypes = map[string]attr.Type{
	"pii_entities_config": types.ListType{ElemType: types.ObjectType{AttrTypes: piiEntityConfigAttrTypes}},
	"regexes_config":      types.ListType{ElemType: types.ObjectType{AttrTypes: regexConfigAttrTypes}},
}

var contextualGroundingFilterConfigAttrTypes = map[string]attr.Type{
	"threshold": types.Float64Type,
	"type":      types.StringType,
}

var contextualGroundingPolicyConfigAttrTypes = map[string]attr.Type{
	"filters_config": types.ListType{ElemType: types.ObjectType{AttrTypes: contextualGroundingFilterConfigAttrTypes}},
}

// ── Metadata ─────────────────────────────────────────────────────────────────

func (r *QConnectAIGuardrailResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_qconnect_ai_guardrail"
}

// ── Schema ────────────────────────────────────────────────────────────────────

func (r *QConnectAIGuardrailResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Creates and manages an Amazon Q in Connect AI Guardrail (qconnect:CreateAIGuardrail). `name` and `description` force replacement when changed. Policy configs and messaging are updatable in-place.",
		Attributes: map[string]schema.Attribute{
			"ai_guardrail_id": schema.StringAttribute{
				Computed:      true,
				Description:   "Service-assigned UUID of the AI Guardrail.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"ai_guardrail_arn": schema.StringAttribute{
				Computed:      true,
				Description:   "ARN of the AI Guardrail.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"assistant_id": schema.StringAttribute{
				Required:      true,
				Description:   "Identifier of the parent Amazon Q in Connect assistant.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required:      true,
				Description:   "Name of the AI Guardrail.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"blocked_input_messaging": schema.StringAttribute{
				Required:    true,
				Description: "Message returned to the user when the AI Guardrail blocks an input prompt.",
			},
			"blocked_outputs_messaging": schema.StringAttribute{
				Required:    true,
				Description: "Message returned to the user when the AI Guardrail blocks a model response.",
			},
			"visibility_status": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Visibility status of the AI Guardrail. One of PUBLISHED or SAVED. Defaults to SAVED when omitted.",
			},
			"description": schema.StringAttribute{
				Optional:      true,
				Description:   "Description of the AI Guardrail.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"tags": schema.MapAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Tags to assign to the AI Guardrail.",
				ElementType: types.StringType,
			},
			"content_policy_config": schema.SingleNestedAttribute{
				Optional:    true,
				Description: "Content filter policy configuration for the AI Guardrail.",
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"filters_config": schema.ListNestedAttribute{
						Required:    true,
						Description: "List of content filter configurations.",
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"input_strength": schema.StringAttribute{
									Required:    true,
									Description: "Filter strength applied to input prompts. One of NONE, LOW, MEDIUM, HIGH.",
								},
								"output_strength": schema.StringAttribute{
									Required:    true,
									Description: "Filter strength applied to model responses. One of NONE, LOW, MEDIUM, HIGH.",
								},
								"type": schema.StringAttribute{
									Required:    true,
									Description: "Content category to filter. Examples: SEXUAL, VIOLENCE, HATE, INSULTS.",
								},
							},
						},
					},
				},
			},
			"topic_policy_config": schema.SingleNestedAttribute{
				Optional:    true,
				Description: "Topic denial policy configuration for the AI Guardrail.",
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"topics_config": schema.ListNestedAttribute{
						Required:    true,
						Description: "List of topic configurations to deny.",
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									Required:    true,
									Description: "Name of the topic to deny.",
								},
								"definition": schema.StringAttribute{
									Required:    true,
									Description: "Definition of the topic to deny.",
								},
								"type": schema.StringAttribute{
									Required:    true,
									Description: "Topic type. Currently only DENY is supported.",
								},
								"examples": schema.ListAttribute{
									Optional:    true,
									Description: "Example prompts that belong to this topic.",
									ElementType: types.StringType,
								},
							},
						},
					},
				},
			},
			"word_policy_config": schema.SingleNestedAttribute{
				Optional:    true,
				Description: "Word block policy configuration for the AI Guardrail.",
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"words_config": schema.ListNestedAttribute{
						Optional:    true,
						Description: "List of custom words to block.",
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"text": schema.StringAttribute{
									Required:    true,
									Description: "Word text to block.",
								},
							},
						},
					},
					"managed_word_lists_config": schema.ListNestedAttribute{
						Optional:    true,
						Description: "List of managed word list configurations.",
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"type": schema.StringAttribute{
									Required:    true,
									Description: "Managed word list type. Currently only PROFANITY is supported.",
								},
							},
						},
					},
				},
			},
			"sensitive_information_policy_config": schema.SingleNestedAttribute{
				Optional:    true,
				Description: "Sensitive information (PII and regex) policy configuration for the AI Guardrail.",
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"pii_entities_config": schema.ListNestedAttribute{
						Optional:    true,
						Description: "List of PII entity configurations.",
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"type": schema.StringAttribute{
									Required:    true,
									Description: "PII entity type (e.g. NAME, EMAIL, US_SOCIAL_SECURITY_NUMBER).",
								},
								"action": schema.StringAttribute{
									Required:    true,
									Description: "Action when PII is detected. One of BLOCK or ANONYMIZE.",
								},
							},
						},
					},
					"regexes_config": schema.ListNestedAttribute{
						Optional:    true,
						Description: "List of regular expression filter configurations.",
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									Required:    true,
									Description: "Name of the regex filter.",
								},
								"pattern": schema.StringAttribute{
									Required:    true,
									Description: "Regular expression pattern.",
								},
								"action": schema.StringAttribute{
									Required:    true,
									Description: "Action when the regex matches. One of BLOCK or ANONYMIZE.",
								},
								"description": schema.StringAttribute{
									Optional:    true,
									Description: "Description of the regex filter.",
								},
							},
						},
					},
				},
			},
			"contextual_grounding_policy_config": schema.SingleNestedAttribute{
				Optional:    true,
				Description: "Contextual grounding policy configuration for the AI Guardrail.",
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"filters_config": schema.ListNestedAttribute{
						Required:    true,
						Description: "List of contextual grounding filter configurations.",
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"threshold": schema.Float64Attribute{
									Required:    true,
									Description: "Threshold score (0.0–1.0) below which responses are blocked.",
								},
								"type": schema.StringAttribute{
									Required:    true,
									Description: "Grounding filter type. One of GROUNDING or RELEVANCE.",
								},
							},
						},
					},
				},
			},
		},
	}
}

// ── Configure ─────────────────────────────────────────────────────────────────

func (r *QConnectAIGuardrailResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	cfg, ok := req.ProviderData.(aws.Config)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *aws.Config, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.config = cfg
}

// ── Create ────────────────────────────────────────────────────────────────────

func (r *QConnectAIGuardrailResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data QConnectAIGuardrailResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := qconnect.NewFromConfig(r.config)

	visibilityStatus := qconnecttypes.VisibilityStatusSaved
	if !data.VisibilityStatus.IsNull() && !data.VisibilityStatus.IsUnknown() && data.VisibilityStatus.ValueString() != "" {
		visibilityStatus = qconnecttypes.VisibilityStatus(data.VisibilityStatus.ValueString())
	}

	in := &qconnect.CreateAIGuardrailInput{
		AssistantId:             aws.String(data.AssistantId.ValueString()),
		Name:                    aws.String(data.Name.ValueString()),
		BlockedInputMessaging:   aws.String(data.BlockedInputMessaging.ValueString()),
		BlockedOutputsMessaging: aws.String(data.BlockedOutputsMessaging.ValueString()),
		VisibilityStatus:        visibilityStatus,
	}
	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		in.Description = aws.String(data.Description.ValueString())
	}

	contentPolicy, diags := expandContentPolicyConfig(ctx, data.ContentPolicyConfig)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	in.ContentPolicyConfig = contentPolicy

	topicPolicy, diags := expandTopicPolicyConfig(ctx, data.TopicPolicyConfig)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	in.TopicPolicyConfig = topicPolicy

	wordPolicy, diags := expandWordPolicyConfig(ctx, data.WordPolicyConfig)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	in.WordPolicyConfig = wordPolicy

	sensitivePolicy, diags := expandSensitiveInformationPolicyConfig(ctx, data.SensitiveInformationPolicyConfig)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	in.SensitiveInformationPolicyConfig = sensitivePolicy

	groundingPolicy, diags := expandContextualGroundingPolicyConfig(ctx, data.ContextualGroundingPolicyConfig)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	in.ContextualGroundingPolicyConfig = groundingPolicy

	tagMap, err := qconnectTagsFromMap(ctx, data.Tags)
	if err != nil {
		resp.Diagnostics.AddError("Error reading tags", err.Error())
		return
	}
	if tagMap != nil {
		in.Tags = tagMap
	}

	out, err := conn.CreateAIGuardrail(ctx, in)
	if err != nil {
		resp.Diagnostics.AddError("Error creating Q in Connect AI Guardrail", err.Error())
		return
	}

	tflog.Trace(ctx, "created qconnect AI guardrail")

	data.AiGuardrailId = types.StringValue(aws.ToString(out.AiGuardrail.AiGuardrailId))
	data.AiGuardrailArn = types.StringValue(aws.ToString(out.AiGuardrail.AiGuardrailArn))
	data.VisibilityStatus = types.StringValue(string(out.AiGuardrail.VisibilityStatus))

	resp.Diagnostics.Append(flattenAllPolicies(ctx, out.AiGuardrail, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if tags, err := readQConnectTags(ctx, conn, data.AiGuardrailArn.ValueString()); err == nil {
		data.Tags = tags
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// ── Read ──────────────────────────────────────────────────────────────────────

func (r *QConnectAIGuardrailResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data QConnectAIGuardrailResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := qconnect.NewFromConfig(r.config)

	out, err := conn.GetAIGuardrail(ctx, &qconnect.GetAIGuardrailInput{
		AssistantId:   aws.String(data.AssistantId.ValueString()),
		AiGuardrailId: aws.String(data.AiGuardrailId.ValueString()),
	})
	if err != nil {
		var nf *qconnecttypes.ResourceNotFoundException
		if errors.As(err, &nf) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading Q in Connect AI Guardrail", err.Error())
		return
	}
	if out == nil || out.AiGuardrail == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	g := out.AiGuardrail
	data.AiGuardrailId = types.StringValue(aws.ToString(g.AiGuardrailId))
	data.AiGuardrailArn = types.StringValue(aws.ToString(g.AiGuardrailArn))
	data.AssistantId = types.StringValue(aws.ToString(g.AssistantId))
	data.Name = types.StringValue(aws.ToString(g.Name))
	data.BlockedInputMessaging = types.StringValue(aws.ToString(g.BlockedInputMessaging))
	data.BlockedOutputsMessaging = types.StringValue(aws.ToString(g.BlockedOutputsMessaging))
	data.VisibilityStatus = types.StringValue(string(g.VisibilityStatus))

	if g.Description != nil {
		data.Description = types.StringValue(aws.ToString(g.Description))
	} else {
		data.Description = types.StringNull()
	}

	resp.Diagnostics.Append(flattenAllPolicies(ctx, g, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if tags, err := readQConnectTags(ctx, conn, data.AiGuardrailArn.ValueString()); err == nil {
		data.Tags = tags
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// ── Update ────────────────────────────────────────────────────────────────────

func (r *QConnectAIGuardrailResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state QConnectAIGuardrailResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := qconnect.NewFromConfig(r.config)

	visibilityStatus := qconnecttypes.VisibilityStatusSaved
	if !plan.VisibilityStatus.IsNull() && !plan.VisibilityStatus.IsUnknown() && plan.VisibilityStatus.ValueString() != "" {
		visibilityStatus = qconnecttypes.VisibilityStatus(plan.VisibilityStatus.ValueString())
	}

	in := &qconnect.UpdateAIGuardrailInput{
		AssistantId:             aws.String(state.AssistantId.ValueString()),
		AiGuardrailId:           aws.String(state.AiGuardrailId.ValueString()),
		BlockedInputMessaging:   aws.String(plan.BlockedInputMessaging.ValueString()),
		BlockedOutputsMessaging: aws.String(plan.BlockedOutputsMessaging.ValueString()),
		VisibilityStatus:        visibilityStatus,
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		in.Description = aws.String(plan.Description.ValueString())
	}

	contentPolicy, diags := expandContentPolicyConfig(ctx, plan.ContentPolicyConfig)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	in.ContentPolicyConfig = contentPolicy

	topicPolicy, diags := expandTopicPolicyConfig(ctx, plan.TopicPolicyConfig)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	in.TopicPolicyConfig = topicPolicy

	wordPolicy, diags := expandWordPolicyConfig(ctx, plan.WordPolicyConfig)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	in.WordPolicyConfig = wordPolicy

	sensitivePolicy, diags := expandSensitiveInformationPolicyConfig(ctx, plan.SensitiveInformationPolicyConfig)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	in.SensitiveInformationPolicyConfig = sensitivePolicy

	groundingPolicy, diags := expandContextualGroundingPolicyConfig(ctx, plan.ContextualGroundingPolicyConfig)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	in.ContextualGroundingPolicyConfig = groundingPolicy

	out, err := conn.UpdateAIGuardrail(ctx, in)
	if err != nil {
		resp.Diagnostics.AddError("Error updating Q in Connect AI Guardrail", err.Error())
		return
	}

	plan.VisibilityStatus = types.StringValue(string(out.AiGuardrail.VisibilityStatus))

	resp.Diagnostics.Append(flattenAllPolicies(ctx, out.AiGuardrail, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if err := updateQConnectTags(ctx, conn, state.AiGuardrailArn.ValueString(), state.Tags, plan.Tags); err != nil {
		resp.Diagnostics.AddError("Error updating Q in Connect AI Guardrail tags", err.Error())
		return
	}

	if tags, err := readQConnectTags(ctx, conn, state.AiGuardrailArn.ValueString()); err == nil {
		plan.Tags = tags
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// ── Delete ────────────────────────────────────────────────────────────────────

func (r *QConnectAIGuardrailResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data QConnectAIGuardrailResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := qconnect.NewFromConfig(r.config)

	_, err := conn.DeleteAIGuardrail(ctx, &qconnect.DeleteAIGuardrailInput{
		AssistantId:   aws.String(data.AssistantId.ValueString()),
		AiGuardrailId: aws.String(data.AiGuardrailId.ValueString()),
	})
	if err != nil {
		var nf *qconnecttypes.ResourceNotFoundException
		if errors.As(err, &nf) {
			return
		}
		resp.Diagnostics.AddError("Error deleting Q in Connect AI Guardrail", err.Error())
	}
}

// ── ImportState ───────────────────────────────────────────────────────────────

func (r *QConnectAIGuardrailResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError("Invalid import ID", "Expected <assistant_id>/<ai_guardrail_id>")
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("assistant_id"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("ai_guardrail_id"), parts[1])...)
}

// ── flattenAllPolicies (shared by Create, Read, Update) ───────────────────────

func flattenAllPolicies(ctx context.Context, g *qconnecttypes.AIGuardrailData, data *QConnectAIGuardrailResourceModel) diag.Diagnostics {
	var diags diag.Diagnostics

	contentObj, d := flattenContentPolicyConfig(ctx, g.ContentPolicyConfig)
	diags.Append(d...)
	data.ContentPolicyConfig = contentObj

	topicObj, d := flattenTopicPolicyConfig(ctx, g.TopicPolicyConfig)
	diags.Append(d...)
	data.TopicPolicyConfig = topicObj

	wordObj, d := flattenWordPolicyConfig(ctx, g.WordPolicyConfig)
	diags.Append(d...)
	data.WordPolicyConfig = wordObj

	sensitiveObj, d := flattenSensitiveInformationPolicyConfig(ctx, g.SensitiveInformationPolicyConfig)
	diags.Append(d...)
	data.SensitiveInformationPolicyConfig = sensitiveObj

	groundingObj, d := flattenContextualGroundingPolicyConfig(ctx, g.ContextualGroundingPolicyConfig)
	diags.Append(d...)
	data.ContextualGroundingPolicyConfig = groundingObj

	return diags
}

// ─────────────────────────────────────────────────────────────────────────────
// expand helpers
// ─────────────────────────────────────────────────────────────────────────────

func expandContentPolicyConfig(ctx context.Context, obj types.Object) (*qconnecttypes.AIGuardrailContentPolicyConfig, diag.Diagnostics) {
	var diags diag.Diagnostics
	if obj.IsNull() || obj.IsUnknown() {
		return nil, diags
	}

	var m contentPolicyConfigModel
	diags.Append(obj.As(ctx, &m, objectAsOptions())...)
	if diags.HasError() {
		return nil, diags
	}

	var items []contentFilterConfigModel
	diags.Append(m.FiltersConfig.ElementsAs(ctx, &items, false)...)
	if diags.HasError() {
		return nil, diags
	}

	filters := make([]qconnecttypes.GuardrailContentFilterConfig, 0, len(items))
	for _, item := range items {
		filters = append(filters, qconnecttypes.GuardrailContentFilterConfig{
			InputStrength:  qconnecttypes.GuardrailFilterStrength(item.InputStrength.ValueString()),
			OutputStrength: qconnecttypes.GuardrailFilterStrength(item.OutputStrength.ValueString()),
			Type:           qconnecttypes.GuardrailContentFilterType(item.Type.ValueString()),
		})
	}

	return &qconnecttypes.AIGuardrailContentPolicyConfig{FiltersConfig: filters}, diags
}

func expandTopicPolicyConfig(ctx context.Context, obj types.Object) (*qconnecttypes.AIGuardrailTopicPolicyConfig, diag.Diagnostics) {
	var diags diag.Diagnostics
	if obj.IsNull() || obj.IsUnknown() {
		return nil, diags
	}

	var m topicPolicyConfigModel
	diags.Append(obj.As(ctx, &m, objectAsOptions())...)
	if diags.HasError() {
		return nil, diags
	}

	var items []topicConfigModel
	diags.Append(m.TopicsConfig.ElementsAs(ctx, &items, false)...)
	if diags.HasError() {
		return nil, diags
	}

	topics := make([]qconnecttypes.GuardrailTopicConfig, 0, len(items))
	for _, item := range items {
		tc := qconnecttypes.GuardrailTopicConfig{
			Name:       aws.String(item.Name.ValueString()),
			Definition: aws.String(item.Definition.ValueString()),
			Type:       qconnecttypes.GuardrailTopicType(item.Type.ValueString()),
		}
		if !item.Examples.IsNull() && !item.Examples.IsUnknown() {
			var examples []string
			diags.Append(item.Examples.ElementsAs(ctx, &examples, false)...)
			if diags.HasError() {
				return nil, diags
			}
			tc.Examples = examples
		}
		topics = append(topics, tc)
	}

	return &qconnecttypes.AIGuardrailTopicPolicyConfig{TopicsConfig: topics}, diags
}

func expandWordPolicyConfig(ctx context.Context, obj types.Object) (*qconnecttypes.AIGuardrailWordPolicyConfig, diag.Diagnostics) {
	var diags diag.Diagnostics
	if obj.IsNull() || obj.IsUnknown() {
		return nil, diags
	}

	var m wordPolicyConfigModel
	diags.Append(obj.As(ctx, &m, objectAsOptions())...)
	if diags.HasError() {
		return nil, diags
	}

	result := &qconnecttypes.AIGuardrailWordPolicyConfig{}

	if !m.WordsConfig.IsNull() && !m.WordsConfig.IsUnknown() {
		var items []wordConfigModel
		diags.Append(m.WordsConfig.ElementsAs(ctx, &items, false)...)
		if diags.HasError() {
			return nil, diags
		}
		words := make([]qconnecttypes.GuardrailWordConfig, 0, len(items))
		for _, item := range items {
			words = append(words, qconnecttypes.GuardrailWordConfig{
				Text: aws.String(item.Text.ValueString()),
			})
		}
		result.WordsConfig = words
	}

	if !m.ManagedWordListsConfig.IsNull() && !m.ManagedWordListsConfig.IsUnknown() {
		var items []managedWordsConfigModel
		diags.Append(m.ManagedWordListsConfig.ElementsAs(ctx, &items, false)...)
		if diags.HasError() {
			return nil, diags
		}
		managed := make([]qconnecttypes.GuardrailManagedWordsConfig, 0, len(items))
		for _, item := range items {
			managed = append(managed, qconnecttypes.GuardrailManagedWordsConfig{
				Type: qconnecttypes.GuardrailManagedWordsType(item.Type.ValueString()),
			})
		}
		result.ManagedWordListsConfig = managed
	}

	return result, diags
}

func expandSensitiveInformationPolicyConfig(ctx context.Context, obj types.Object) (*qconnecttypes.AIGuardrailSensitiveInformationPolicyConfig, diag.Diagnostics) {
	var diags diag.Diagnostics
	if obj.IsNull() || obj.IsUnknown() {
		return nil, diags
	}

	var m sensitiveInformationPolicyConfigModel
	diags.Append(obj.As(ctx, &m, objectAsOptions())...)
	if diags.HasError() {
		return nil, diags
	}

	result := &qconnecttypes.AIGuardrailSensitiveInformationPolicyConfig{}

	if !m.PiiEntitiesConfig.IsNull() && !m.PiiEntitiesConfig.IsUnknown() {
		var items []piiEntityConfigModel
		diags.Append(m.PiiEntitiesConfig.ElementsAs(ctx, &items, false)...)
		if diags.HasError() {
			return nil, diags
		}
		pii := make([]qconnecttypes.GuardrailPiiEntityConfig, 0, len(items))
		for _, item := range items {
			pii = append(pii, qconnecttypes.GuardrailPiiEntityConfig{
				Type:   qconnecttypes.GuardrailPiiEntityType(item.Type.ValueString()),
				Action: qconnecttypes.GuardrailSensitiveInformationAction(item.Action.ValueString()),
			})
		}
		result.PiiEntitiesConfig = pii
	}

	if !m.RegexesConfig.IsNull() && !m.RegexesConfig.IsUnknown() {
		var items []regexConfigModel
		diags.Append(m.RegexesConfig.ElementsAs(ctx, &items, false)...)
		if diags.HasError() {
			return nil, diags
		}
		regexes := make([]qconnecttypes.GuardrailRegexConfig, 0, len(items))
		for _, item := range items {
			rc := qconnecttypes.GuardrailRegexConfig{
				Name:    aws.String(item.Name.ValueString()),
				Pattern: aws.String(item.Pattern.ValueString()),
				Action:  qconnecttypes.GuardrailSensitiveInformationAction(item.Action.ValueString()),
			}
			if !item.Description.IsNull() && !item.Description.IsUnknown() {
				rc.Description = aws.String(item.Description.ValueString())
			}
			regexes = append(regexes, rc)
		}
		result.RegexesConfig = regexes
	}

	return result, diags
}

func expandContextualGroundingPolicyConfig(ctx context.Context, obj types.Object) (*qconnecttypes.AIGuardrailContextualGroundingPolicyConfig, diag.Diagnostics) {
	var diags diag.Diagnostics
	if obj.IsNull() || obj.IsUnknown() {
		return nil, diags
	}

	var m contextualGroundingPolicyConfigModel
	diags.Append(obj.As(ctx, &m, objectAsOptions())...)
	if diags.HasError() {
		return nil, diags
	}

	var items []contextualGroundingFilterConfigModel
	diags.Append(m.FiltersConfig.ElementsAs(ctx, &items, false)...)
	if diags.HasError() {
		return nil, diags
	}

	filters := make([]qconnecttypes.GuardrailContextualGroundingFilterConfig, 0, len(items))
	for _, item := range items {
		filters = append(filters, qconnecttypes.GuardrailContextualGroundingFilterConfig{
			Threshold: item.Threshold.ValueFloat64(),
			Type:      qconnecttypes.GuardrailContextualGroundingFilterType(item.Type.ValueString()),
		})
	}

	return &qconnecttypes.AIGuardrailContextualGroundingPolicyConfig{FiltersConfig: filters}, diags
}

// ─────────────────────────────────────────────────────────────────────────────
// flatten helpers
// ─────────────────────────────────────────────────────────────────────────────

func flattenContentPolicyConfig(ctx context.Context, cfg *qconnecttypes.AIGuardrailContentPolicyConfig) (types.Object, diag.Diagnostics) {
	var diags diag.Diagnostics
	if cfg == nil {
		return types.ObjectNull(contentPolicyConfigAttrTypes), diags
	}

	filterObjs := make([]attr.Value, 0, len(cfg.FiltersConfig))
	for _, f := range cfg.FiltersConfig {
		obj, d := types.ObjectValue(contentFilterConfigAttrTypes, map[string]attr.Value{
			"input_strength":  types.StringValue(string(f.InputStrength)),
			"output_strength": types.StringValue(string(f.OutputStrength)),
			"type":            types.StringValue(string(f.Type)),
		})
		diags.Append(d...)
		filterObjs = append(filterObjs, obj)
	}

	filtersList, d := types.ListValue(types.ObjectType{AttrTypes: contentFilterConfigAttrTypes}, filterObjs)
	diags.Append(d...)

	result, d := types.ObjectValue(contentPolicyConfigAttrTypes, map[string]attr.Value{
		"filters_config": filtersList,
	})
	diags.Append(d...)
	return result, diags
}

func flattenTopicPolicyConfig(ctx context.Context, cfg *qconnecttypes.AIGuardrailTopicPolicyConfig) (types.Object, diag.Diagnostics) {
	var diags diag.Diagnostics
	if cfg == nil {
		return types.ObjectNull(topicPolicyConfigAttrTypes), diags
	}

	topicObjs := make([]attr.Value, 0, len(cfg.TopicsConfig))
	for _, t := range cfg.TopicsConfig {
		var examplesList types.List
		if len(t.Examples) > 0 {
			exVals := make([]attr.Value, 0, len(t.Examples))
			for _, ex := range t.Examples {
				exVals = append(exVals, types.StringValue(ex))
			}
			l, d := types.ListValue(types.StringType, exVals)
			diags.Append(d...)
			examplesList = l
		} else {
			examplesList = types.ListValueMust(types.StringType, []attr.Value{})
		}

		obj, d := types.ObjectValue(topicConfigAttrTypes, map[string]attr.Value{
			"name":       types.StringValue(aws.ToString(t.Name)),
			"definition": types.StringValue(aws.ToString(t.Definition)),
			"type":       types.StringValue(string(t.Type)),
			"examples":   examplesList,
		})
		diags.Append(d...)
		topicObjs = append(topicObjs, obj)
	}

	topicsList, d := types.ListValue(types.ObjectType{AttrTypes: topicConfigAttrTypes}, topicObjs)
	diags.Append(d...)

	result, d := types.ObjectValue(topicPolicyConfigAttrTypes, map[string]attr.Value{
		"topics_config": topicsList,
	})
	diags.Append(d...)
	return result, diags
}

func flattenWordPolicyConfig(ctx context.Context, cfg *qconnecttypes.AIGuardrailWordPolicyConfig) (types.Object, diag.Diagnostics) {
	var diags diag.Diagnostics
	if cfg == nil {
		return types.ObjectNull(wordPolicyConfigAttrTypes), diags
	}

	// words_config
	wordObjs := make([]attr.Value, 0, len(cfg.WordsConfig))
	for _, w := range cfg.WordsConfig {
		obj, d := types.ObjectValue(wordConfigAttrTypes, map[string]attr.Value{
			"text": types.StringValue(aws.ToString(w.Text)),
		})
		diags.Append(d...)
		wordObjs = append(wordObjs, obj)
	}
	wordsList, d := types.ListValue(types.ObjectType{AttrTypes: wordConfigAttrTypes}, wordObjs)
	diags.Append(d...)

	// managed_word_lists_config
	managedObjs := make([]attr.Value, 0, len(cfg.ManagedWordListsConfig))
	for _, m := range cfg.ManagedWordListsConfig {
		obj, d := types.ObjectValue(managedWordsConfigAttrTypes, map[string]attr.Value{
			"type": types.StringValue(string(m.Type)),
		})
		diags.Append(d...)
		managedObjs = append(managedObjs, obj)
	}
	managedList, d := types.ListValue(types.ObjectType{AttrTypes: managedWordsConfigAttrTypes}, managedObjs)
	diags.Append(d...)

	result, d := types.ObjectValue(wordPolicyConfigAttrTypes, map[string]attr.Value{
		"words_config":              wordsList,
		"managed_word_lists_config": managedList,
	})
	diags.Append(d...)
	return result, diags
}

func flattenSensitiveInformationPolicyConfig(ctx context.Context, cfg *qconnecttypes.AIGuardrailSensitiveInformationPolicyConfig) (types.Object, diag.Diagnostics) {
	var diags diag.Diagnostics
	if cfg == nil {
		return types.ObjectNull(sensitiveInformationPolicyConfigAttrTypes), diags
	}

	// pii_entities_config
	piiObjs := make([]attr.Value, 0, len(cfg.PiiEntitiesConfig))
	for _, p := range cfg.PiiEntitiesConfig {
		obj, d := types.ObjectValue(piiEntityConfigAttrTypes, map[string]attr.Value{
			"type":   types.StringValue(string(p.Type)),
			"action": types.StringValue(string(p.Action)),
		})
		diags.Append(d...)
		piiObjs = append(piiObjs, obj)
	}
	piiList, d := types.ListValue(types.ObjectType{AttrTypes: piiEntityConfigAttrTypes}, piiObjs)
	diags.Append(d...)

	// regexes_config
	regexObjs := make([]attr.Value, 0, len(cfg.RegexesConfig))
	for _, rx := range cfg.RegexesConfig {
		descVal := types.StringNull()
		if rx.Description != nil {
			descVal = types.StringValue(aws.ToString(rx.Description))
		}
		obj, d := types.ObjectValue(regexConfigAttrTypes, map[string]attr.Value{
			"name":        types.StringValue(aws.ToString(rx.Name)),
			"pattern":     types.StringValue(aws.ToString(rx.Pattern)),
			"action":      types.StringValue(string(rx.Action)),
			"description": descVal,
		})
		diags.Append(d...)
		regexObjs = append(regexObjs, obj)
	}
	regexList, d := types.ListValue(types.ObjectType{AttrTypes: regexConfigAttrTypes}, regexObjs)
	diags.Append(d...)

	result, d := types.ObjectValue(sensitiveInformationPolicyConfigAttrTypes, map[string]attr.Value{
		"pii_entities_config": piiList,
		"regexes_config":      regexList,
	})
	diags.Append(d...)
	return result, diags
}

func flattenContextualGroundingPolicyConfig(ctx context.Context, cfg *qconnecttypes.AIGuardrailContextualGroundingPolicyConfig) (types.Object, diag.Diagnostics) {
	var diags diag.Diagnostics
	if cfg == nil {
		return types.ObjectNull(contextualGroundingPolicyConfigAttrTypes), diags
	}

	filterObjs := make([]attr.Value, 0, len(cfg.FiltersConfig))
	for _, f := range cfg.FiltersConfig {
		obj, d := types.ObjectValue(contextualGroundingFilterConfigAttrTypes, map[string]attr.Value{
			"threshold": types.Float64Value(f.Threshold),
			"type":      types.StringValue(string(f.Type)),
		})
		diags.Append(d...)
		filterObjs = append(filterObjs, obj)
	}

	filtersList, d := types.ListValue(types.ObjectType{AttrTypes: contextualGroundingFilterConfigAttrTypes}, filterObjs)
	diags.Append(d...)

	result, d := types.ObjectValue(contextualGroundingPolicyConfigAttrTypes, map[string]attr.Value{
		"filters_config": filtersList,
	})
	diags.Append(d...)
	return result, diags
}

// ── helpers ───────────────────────────────────────────────────────────────────

// objectAsOptions returns the options for types.Object.As calls.
func objectAsOptions() basetypes.ObjectAsOptions {
	return basetypes.ObjectAsOptions{}
}
