// Generated by Claude (claude.ai) | Date: 2026-05-18 | Model: claude-sonnet-4-6
// Re-generation prompt: see Workspaces.md in project root

package provider

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/qconnect"
	qconnecttypes "github.com/aws/aws-sdk-go-v2/service/qconnect/types"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var _ resource.Resource = &QConnectAssistantAssociationResource{}
var _ resource.ResourceWithImportState = &QConnectAssistantAssociationResource{}

func NewQConnectAssistantAssociationResource() resource.Resource {
	return &QConnectAssistantAssociationResource{}
}

type QConnectAssistantAssociationResource struct{ config aws.Config }

// bedrockKnowledgeBaseModel holds the nested bedrock_knowledge_base block.
type bedrockKnowledgeBaseModel struct {
	KnowledgeBaseArn types.String `tfsdk:"knowledge_base_arn"`
	AccessRoleArn    types.String `tfsdk:"access_role_arn"`
}

// assistantAssociationModel holds the association block.
type assistantAssociationModel struct {
	KnowledgeBaseId     types.String `tfsdk:"knowledge_base_id"`
	BedrockKnowledgeBase types.Object `tfsdk:"bedrock_knowledge_base"`
}

// QConnectAssistantAssociationResourceModel is the top-level model.
type QConnectAssistantAssociationResourceModel struct {
	AssistantId              types.String `tfsdk:"assistant_id"`
	AssociationType          types.String `tfsdk:"association_type"`
	Association              types.Object `tfsdk:"association"`
	AssistantAssociationId   types.String `tfsdk:"assistant_association_id"`
	AssistantAssociationArn  types.String `tfsdk:"assistant_association_arn"`
	Tags                     types.Map    `tfsdk:"tags"`
}

// Package-level attr-type maps.
var bedrockKnowledgeBaseAttrTypes = map[string]attr.Type{
	"knowledge_base_arn": types.StringType,
	"access_role_arn":    types.StringType,
}

var assistantAssociationAttrTypes = map[string]attr.Type{
	"knowledge_base_id":     types.StringType,
	"bedrock_knowledge_base": types.ObjectType{AttrTypes: bedrockKnowledgeBaseAttrTypes},
}

func (r *QConnectAssistantAssociationResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_qconnect_assistant_association"
}

func (r *QConnectAssistantAssociationResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Creates and manages an Amazon Q in Connect assistant association (`qconnect:CreateAssistantAssociation`). " +
			"An association wires an external knowledge base (or a native Q in Connect knowledge base) to an assistant. " +
			"No update API exists; all structural fields force replacement. Only `tags` can be updated in place.",
		Attributes: map[string]schema.Attribute{
			"assistant_id": schema.StringAttribute{
				Required:      true,
				Description:   "Identifier of the Amazon Q in Connect assistant to associate.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"association_type": schema.StringAttribute{
				Required:    true,
				Description: "Type of the association. One of KNOWLEDGE_BASE or EXTERNAL_BEDROCK_KNOWLEDGE_BASE. Controls which sub-field of `association` is used.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators: []validator.String{
					stringvalidator.OneOf("KNOWLEDGE_BASE", "EXTERNAL_BEDROCK_KNOWLEDGE_BASE"),
				},
			},
			"association": schema.SingleNestedAttribute{
				Required:      true,
				Description:   "The associated resource. Use `knowledge_base_id` when `association_type` is KNOWLEDGE_BASE; use `bedrock_knowledge_base` when `association_type` is EXTERNAL_BEDROCK_KNOWLEDGE_BASE.",
				PlanModifiers: []planmodifier.Object{objectplanmodifier.RequiresReplace()},
				Attributes: map[string]schema.Attribute{
					"knowledge_base_id": schema.StringAttribute{
						Optional:    true,
						Description: "Identifier of the Q in Connect knowledge base. Used when association_type is KNOWLEDGE_BASE.",
					},
					"bedrock_knowledge_base": schema.SingleNestedAttribute{
						Optional:    true,
						Description: "Configuration for the external Bedrock knowledge base. Used when association_type is EXTERNAL_BEDROCK_KNOWLEDGE_BASE.",
						Attributes: map[string]schema.Attribute{
							"knowledge_base_arn": schema.StringAttribute{
								Required:    true,
								Description: "ARN of the external Bedrock knowledge base.",
							},
							"access_role_arn": schema.StringAttribute{
								Required:    true,
								Description: "ARN of the IAM role used to access the external Bedrock knowledge base.",
							},
						},
					},
				},
			},
			"assistant_association_id": schema.StringAttribute{
				Computed:      true,
				Description:   "Service-assigned UUID of the assistant association.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"assistant_association_arn": schema.StringAttribute{
				Computed:      true,
				Description:   "ARN of the assistant association.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"tags": schema.MapAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Tags to assign to the assistant association.",
				ElementType: types.StringType,
			},
		},
	}
}

func (r *QConnectAssistantAssociationResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	cfg, ok := req.ProviderData.(aws.Config)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *aws.Config, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.config = cfg
}

func (r *QConnectAssistantAssociationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data QConnectAssistantAssociationResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := qconnect.NewFromConfig(r.config)

	// Expand the association block.
	assocInput, err := expandAssistantAssociationInput(ctx, data.AssociationType.ValueString(), data.Association)
	if err != nil {
		resp.Diagnostics.AddError("Error building association input", err.Error())
		return
	}

	in := &qconnect.CreateAssistantAssociationInput{
		AssistantId:     aws.String(data.AssistantId.ValueString()),
		AssociationType: qconnecttypes.AssociationType(data.AssociationType.ValueString()),
		Association:     assocInput,
	}

	tagMap, err := qconnectTagsFromMap(ctx, data.Tags)
	if err != nil {
		resp.Diagnostics.AddError("Error reading tags", err.Error())
		return
	}
	if tagMap != nil {
		in.Tags = tagMap
	}

	out, err := conn.CreateAssistantAssociation(ctx, in)
	if err != nil {
		resp.Diagnostics.AddError("Error creating Q in Connect assistant association", err.Error())
		return
	}

	tflog.Trace(ctx, "created qconnect assistant association")

	data.AssistantAssociationId = types.StringValue(aws.ToString(out.AssistantAssociation.AssistantAssociationId))
	data.AssistantAssociationArn = types.StringValue(aws.ToString(out.AssistantAssociation.AssistantAssociationArn))

	if tags, err := readQConnectTags(ctx, conn, data.AssistantAssociationArn.ValueString()); err == nil {
		data.Tags = tags
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *QConnectAssistantAssociationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data QConnectAssistantAssociationResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := qconnect.NewFromConfig(r.config)

	out, err := conn.GetAssistantAssociation(ctx, &qconnect.GetAssistantAssociationInput{
		AssistantId:            aws.String(data.AssistantId.ValueString()),
		AssistantAssociationId: aws.String(data.AssistantAssociationId.ValueString()),
	})
	if err != nil {
		var nf *qconnecttypes.ResourceNotFoundException
		if errors.As(err, &nf) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading Q in Connect assistant association", err.Error())
		return
	}
	if out == nil || out.AssistantAssociation == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	aa := out.AssistantAssociation
	data.AssistantAssociationId = types.StringValue(aws.ToString(aa.AssistantAssociationId))
	data.AssistantAssociationArn = types.StringValue(aws.ToString(aa.AssistantAssociationArn))
	data.AssistantId = types.StringValue(aws.ToString(aa.AssistantId))
	data.AssociationType = types.StringValue(string(aa.AssociationType))

	assocObj, err := flattenAssistantAssociationOutputData(ctx, aa.AssociationData)
	if err != nil {
		resp.Diagnostics.AddError("Error reading association data", err.Error())
		return
	}
	data.Association = assocObj

	if tags, err := readQConnectTags(ctx, conn, data.AssistantAssociationArn.ValueString()); err == nil {
		data.Tags = tags
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *QConnectAssistantAssociationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state QConnectAssistantAssociationResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := qconnect.NewFromConfig(r.config)

	if err := updateQConnectTags(ctx, conn, state.AssistantAssociationArn.ValueString(), state.Tags, plan.Tags); err != nil {
		resp.Diagnostics.AddError("Error updating Q in Connect assistant association tags", err.Error())
		return
	}

	if tags, err := readQConnectTags(ctx, conn, state.AssistantAssociationArn.ValueString()); err == nil {
		plan.Tags = tags
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *QConnectAssistantAssociationResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data QConnectAssistantAssociationResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := qconnect.NewFromConfig(r.config)

	_, err := conn.DeleteAssistantAssociation(ctx, &qconnect.DeleteAssistantAssociationInput{
		AssistantId:            aws.String(data.AssistantId.ValueString()),
		AssistantAssociationId: aws.String(data.AssistantAssociationId.ValueString()),
	})
	if err != nil {
		var nf *qconnecttypes.ResourceNotFoundException
		if errors.As(err, &nf) {
			return
		}
		resp.Diagnostics.AddError("Error deleting Q in Connect assistant association", err.Error())
	}
}

func (r *QConnectAssistantAssociationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError("Invalid import ID", "Expected <assistant_id>/<assistant_association_id>")
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("assistant_id"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("assistant_association_id"), parts[1])...)
}

// expandAssistantAssociationInput converts the Terraform association object into the SDK union type.
func expandAssistantAssociationInput(ctx context.Context, associationType string, assocObj types.Object) (qconnecttypes.AssistantAssociationInputData, error) {
	var assoc assistantAssociationModel
	if diags := assocObj.As(ctx, &assoc, basetypes.ObjectAsOptions{UnhandledNullAsEmpty: true, UnhandledUnknownAsEmpty: true}); diags.HasError() {
		return nil, fmt.Errorf("expanding association: %s", diags)
	}

	switch associationType {
	case "KNOWLEDGE_BASE":
		if assoc.KnowledgeBaseId.IsNull() || assoc.KnowledgeBaseId.IsUnknown() || assoc.KnowledgeBaseId.ValueString() == "" {
			return nil, fmt.Errorf("association.knowledge_base_id is required when association_type is KNOWLEDGE_BASE")
		}
		return &qconnecttypes.AssistantAssociationInputDataMemberKnowledgeBaseId{
			Value: assoc.KnowledgeBaseId.ValueString(),
		}, nil

	case "EXTERNAL_BEDROCK_KNOWLEDGE_BASE":
		if assoc.BedrockKnowledgeBase.IsNull() || assoc.BedrockKnowledgeBase.IsUnknown() {
			return nil, fmt.Errorf("association.bedrock_knowledge_base is required when association_type is EXTERNAL_BEDROCK_KNOWLEDGE_BASE")
		}
		var bkb bedrockKnowledgeBaseModel
		if diags := assoc.BedrockKnowledgeBase.As(ctx, &bkb, basetypes.ObjectAsOptions{}); diags.HasError() {
			return nil, fmt.Errorf("expanding bedrock_knowledge_base: %s", diags)
		}
		return &qconnecttypes.AssistantAssociationInputDataMemberExternalBedrockKnowledgeBaseConfig{
			Value: qconnecttypes.ExternalBedrockKnowledgeBaseConfig{
				BedrockKnowledgeBaseArn: aws.String(bkb.KnowledgeBaseArn.ValueString()),
				AccessRoleArn:           aws.String(bkb.AccessRoleArn.ValueString()),
			},
		}, nil

	default:
		return nil, fmt.Errorf("unsupported association_type: %s", associationType)
	}
}

// flattenAssistantAssociationOutputData converts the SDK union type back to a Terraform object.
func flattenAssistantAssociationOutputData(ctx context.Context, outputData qconnecttypes.AssistantAssociationOutputData) (types.Object, error) {
	nullBedrockObj := types.ObjectNull(bedrockKnowledgeBaseAttrTypes)

	switch v := outputData.(type) {
	case *qconnecttypes.AssistantAssociationOutputDataMemberKnowledgeBaseAssociation:
		return types.ObjectValueMust(
			assistantAssociationAttrTypes,
			map[string]attr.Value{
				"knowledge_base_id":      types.StringValue(aws.ToString(v.Value.KnowledgeBaseId)),
				"bedrock_knowledge_base": nullBedrockObj,
			},
		), nil

	case *qconnecttypes.AssistantAssociationOutputDataMemberExternalBedrockKnowledgeBaseConfig:
		bedrockObj, diags := types.ObjectValue(
			bedrockKnowledgeBaseAttrTypes,
			map[string]attr.Value{
				"knowledge_base_arn": types.StringValue(aws.ToString(v.Value.BedrockKnowledgeBaseArn)),
				"access_role_arn":    types.StringValue(aws.ToString(v.Value.AccessRoleArn)),
			},
		)
		if diags.HasError() {
			return types.ObjectNull(assistantAssociationAttrTypes), fmt.Errorf("building bedrock_knowledge_base object: %s", diags)
		}
		return types.ObjectValueMust(
			assistantAssociationAttrTypes,
			map[string]attr.Value{
				"knowledge_base_id":      types.StringNull(),
				"bedrock_knowledge_base": bedrockObj,
			},
		), nil

	default:
		return types.ObjectNull(assistantAssociationAttrTypes), fmt.Errorf("unsupported AssistantAssociationOutputData type: %T", outputData)
	}
}
