// Generated by Claude (claude.ai) | Date: 2026-04-17 | Model: claude-sonnet-4-6
// Re-generation prompt: see Workspaces.ai in project root

package provider

import (
	"context"
	"errors"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/workspaces"
	workspacestypes "github.com/aws/aws-sdk-go-v2/service/workspaces/types"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var _ resource.Resource = &WorkspacesImageCopyResource{}
var _ resource.ResourceWithImportState = &WorkspacesImageCopyResource{}

func NewWorkspacesImageCopyResource() resource.Resource {
	return &WorkspacesImageCopyResource{}
}

type WorkspacesImageCopyResource struct {
	config aws.Config
}

type WorkspacesImageCopyResourceModel struct {
	ImageId        types.String `tfsdk:"image_id"`
	Name           types.String `tfsdk:"name"`
	Description    types.String `tfsdk:"description"`
	SourceImageId  types.String `tfsdk:"source_image_id"`
	SourceRegion   types.String `tfsdk:"source_region"`
	State          types.String `tfsdk:"state"`
	OwnerAccountId types.String `tfsdk:"owner_account_id"`
	Tags           types.Map    `tfsdk:"tags"`
}

func (r *WorkspacesImageCopyResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_workspaces_image_copy"
}

func (r *WorkspacesImageCopyResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Copies a WorkSpace image from a source region into the provider's region via CopyWorkspaceImage.",

		Attributes: map[string]schema.Attribute{
			"image_id": schema.StringAttribute{
				Computed:    true,
				Description: "The identifier of the new (copied) WorkSpace image in the destination region.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "The name for the copied image.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"description": schema.StringAttribute{
				Optional:    true,
				Description: "A description for the copied image.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"source_image_id": schema.StringAttribute{
				Required:    true,
				Description: "The identifier of the source image to copy.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"source_region": schema.StringAttribute{
				Required:    true,
				Description: "The AWS Region identifier where the source image resides.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"state": schema.StringAttribute{
				Computed:    true,
				Description: "The availability status of the image (AVAILABLE, PENDING, ERROR).",
			},
			"owner_account_id": schema.StringAttribute{
				Computed:    true,
				Description: "The identifier of the AWS account that owns the image.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"tags": schema.MapAttribute{
				Optional:    true,
				Computed:    true,
				ElementType: types.StringType,
				Description: "Tags to assign to the image.",
			},
		},
	}
}

func (r *WorkspacesImageCopyResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	config, ok := req.ProviderData.(aws.Config)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *aws.Config, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.config = config
}

func (r *WorkspacesImageCopyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data WorkspacesImageCopyResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := workspaces.NewFromConfig(r.config)

	input := &workspaces.CopyWorkspaceImageInput{
		Name:          aws.String(data.Name.ValueString()),
		SourceImageId: aws.String(data.SourceImageId.ValueString()),
		SourceRegion:  aws.String(data.SourceRegion.ValueString()),
	}

	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		input.Description = aws.String(data.Description.ValueString())
	}

	if tagList, err := tagsToList(ctx, data.Tags); err == nil {
		input.Tags = tagList
	}

	output, err := conn.CopyWorkspaceImage(ctx, input)

	if err != nil {
		resp.Diagnostics.AddError("Error copying WorkSpace image",
			fmt.Sprintf("Could not copy WorkSpace image from region %s, unexpected error: %s", data.SourceRegion.ValueString(), err))
		return
	}

	tflog.Trace(ctx, "copied workspaces image resource")

	data.ImageId = types.StringValue(aws.ToString(output.ImageId))

	// CopyWorkspaceImage only returns ImageId; describe to populate remaining computed fields.
	descOutput, err := conn.DescribeWorkspaceImages(ctx, &workspaces.DescribeWorkspaceImagesInput{
		ImageIds: []string{data.ImageId.ValueString()},
	})
	if err == nil && len(descOutput.Images) > 0 {
		img := descOutput.Images[0]
		data.State = types.StringValue(string(img.State))
		data.OwnerAccountId = types.StringValue(aws.ToString(img.OwnerAccountId))
	} else {
		data.State = types.StringValue("PENDING")
		data.OwnerAccountId = types.StringValue("")
	}

	if tags, err := readResourceTags(ctx, conn, data.ImageId.ValueString()); err == nil {
		data.Tags = tags
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *WorkspacesImageCopyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data WorkspacesImageCopyResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := workspaces.NewFromConfig(r.config)

	output, err := conn.DescribeWorkspaceImages(ctx, &workspaces.DescribeWorkspaceImagesInput{
		ImageIds: []string{data.ImageId.ValueString()},
	})

	if err != nil {
		var notFound *workspacestypes.ResourceNotFoundException
		if errors.As(err, &notFound) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading WorkSpace image copy",
			fmt.Sprintf("Could not read WorkSpace image %s, unexpected error: %s", data.ImageId.ValueString(), err))
		return
	}

	if len(output.Images) == 0 {
		resp.State.RemoveResource(ctx)
		return
	}

	img := output.Images[0]
	data.ImageId = types.StringValue(aws.ToString(img.ImageId))
	data.Name = types.StringValue(aws.ToString(img.Name))
	if img.Description != nil {
		data.Description = types.StringValue(*img.Description)
	} else {
		data.Description = types.StringNull()
	}
	data.State = types.StringValue(string(img.State))
	data.OwnerAccountId = types.StringValue(aws.ToString(img.OwnerAccountId))

	if tags, err := readResourceTags(ctx, conn, data.ImageId.ValueString()); err == nil {
		data.Tags = tags
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *WorkspacesImageCopyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state WorkspacesImageCopyResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := workspaces.NewFromConfig(r.config)

	if err := updateResourceTags(ctx, conn, state.ImageId.ValueString(), state.Tags, plan.Tags); err != nil {
		resp.Diagnostics.AddError("Error updating WorkSpace image tags",
			fmt.Sprintf("Could not update tags for WorkSpace image %s, unexpected error: %s", state.ImageId.ValueString(), err))
		return
	}

	if tags, err := readResourceTags(ctx, conn, plan.ImageId.ValueString()); err == nil {
		plan.Tags = tags
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *WorkspacesImageCopyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data WorkspacesImageCopyResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := workspaces.NewFromConfig(r.config)

	_, err := conn.DeleteWorkspaceImage(ctx, &workspaces.DeleteWorkspaceImageInput{
		ImageId: aws.String(data.ImageId.ValueString()),
	})

	if err != nil {
		var notFound *workspacestypes.ResourceNotFoundException
		if errors.As(err, &notFound) {
			return
		}
		resp.Diagnostics.AddError("Error deleting WorkSpace image copy",
			fmt.Sprintf("Could not delete WorkSpace image %s, unexpected error: %s", data.ImageId.ValueString(), err))
		return
	}
}

func (r *WorkspacesImageCopyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("image_id"), req, resp)
}
