// Generated by Claude (claude.ai) | Date: 2026-04-21 | Model: claude-sonnet-4-6
// Re-generation prompt: see Workspaces.ai in project root

package provider

import (
	"context"
	"errors"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/workspaces"
	workspacestypes "github.com/aws/aws-sdk-go-v2/service/workspaces/types"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var _ resource.Resource = &WorkspacesPoolResource{}
var _ resource.ResourceWithImportState = &WorkspacesPoolResource{}

func NewWorkspacesPoolResource() resource.Resource {
	return &WorkspacesPoolResource{}
}

type WorkspacesPoolResource struct {
	config aws.Config
}

type PoolApplicationSettingsModel struct {
	Status        types.String `tfsdk:"status"`
	SettingsGroup types.String `tfsdk:"settings_group"`
}

type PoolTimeoutSettingsModel struct {
	DisconnectTimeoutInSeconds     types.Int32 `tfsdk:"disconnect_timeout_in_seconds"`
	IdleDisconnectTimeoutInSeconds types.Int32 `tfsdk:"idle_disconnect_timeout_in_seconds"`
	MaxUserDurationInSeconds       types.Int32 `tfsdk:"max_user_duration_in_seconds"`
}

type WorkspacesPoolResourceModel struct {
	PoolId              types.String                  `tfsdk:"pool_id"`
	PoolArn             types.String                  `tfsdk:"pool_arn"`
	PoolName            types.String                  `tfsdk:"pool_name"`
	Description         types.String                  `tfsdk:"description"`
	BundleId            types.String                  `tfsdk:"bundle_id"`
	DirectoryId         types.String                  `tfsdk:"directory_id"`
	DesiredUserSessions types.Int32                   `tfsdk:"desired_user_sessions"`
	RunningMode         types.String                  `tfsdk:"running_mode"`
	ApplicationSettings *PoolApplicationSettingsModel `tfsdk:"application_settings"`
	TimeoutSettings     *PoolTimeoutSettingsModel     `tfsdk:"timeout_settings"`
	State               types.String                  `tfsdk:"state"`
	Tags                types.Map                     `tfsdk:"tags"`
}

func (r *WorkspacesPoolResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_workspaces_pool"
}

func (r *WorkspacesPoolResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Creates and manages a WorkSpaces pool via CreateWorkspacesPool / UpdateWorkspacesPool / TerminateWorkspacesPool.",

		Attributes: map[string]schema.Attribute{
			"pool_id": schema.StringAttribute{
				Computed:    true,
				Description: "The identifier of the pool.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"pool_arn": schema.StringAttribute{
				Computed:    true,
				Description: "The ARN of the pool.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"pool_name": schema.StringAttribute{
				Required:    true,
				Description: "The name of the pool. Cannot be changed after creation.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"description": schema.StringAttribute{
				Required:    true,
				Description: "The description of the pool.",
			},
			"bundle_id": schema.StringAttribute{
				Required:    true,
				Description: "The identifier of the bundle to use for the pool.",
			},
			"directory_id": schema.StringAttribute{
				Required:    true,
				Description: "The identifier of the directory to use for the pool.",
			},
			"desired_user_sessions": schema.Int32Attribute{
				Required:    true,
				Description: "The desired number of user sessions for the pool.",
			},
			"running_mode": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "The running mode for the pool. Valid values: AUTO_STOP, ALWAYS_ON.",
				Validators: []validator.String{
					stringvalidator.OneOf("AUTO_STOP", "ALWAYS_ON"),
				},
			},
			"state": schema.StringAttribute{
				Computed:    true,
				Description: "The current state of the pool.",
			},
			"tags": schema.MapAttribute{
				Optional:    true,
				Computed:    true,
				ElementType: types.StringType,
				Description: "Tags to assign to the pool.",
			},
		},
		Blocks: map[string]schema.Block{
			"application_settings": schema.SingleNestedBlock{
				Description: "Persistent application settings for users of the pool.",
				Attributes: map[string]schema.Attribute{
					"status": schema.StringAttribute{
						Required:    true,
						Description: "Whether persistent application settings are enabled. Valid values: ENABLED, DISABLED.",
						Validators: []validator.String{
							stringvalidator.OneOf("ENABLED", "DISABLED"),
						},
					},
					"settings_group": schema.StringAttribute{
						Optional:    true,
						Description: "The path prefix for the S3 bucket where persistent application settings are stored.",
					},
				},
			},
			"timeout_settings": schema.SingleNestedBlock{
				Description: "Timeout settings for streaming sessions in the pool.",
				Attributes: map[string]schema.Attribute{
					"disconnect_timeout_in_seconds": schema.Int32Attribute{
						Optional:    true,
						Description: "Seconds a session stays active after users disconnect.",
					},
					"idle_disconnect_timeout_in_seconds": schema.Int32Attribute{
						Optional:    true,
						Description: "Seconds a connection stays active while idle.",
					},
					"max_user_duration_in_seconds": schema.Int32Attribute{
						Optional:    true,
						Description: "Maximum seconds a streaming session can remain active.",
					},
				},
			},
		},
	}
}

func (r *WorkspacesPoolResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	config, ok := req.ProviderData.(aws.Config)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *aws.Config, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.config = config
}

func (r *WorkspacesPoolResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data WorkspacesPoolResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := workspaces.NewFromConfig(r.config)

	input := &workspaces.CreateWorkspacesPoolInput{
		PoolName:    aws.String(data.PoolName.ValueString()),
		Description: aws.String(data.Description.ValueString()),
		BundleId:    aws.String(data.BundleId.ValueString()),
		DirectoryId: aws.String(data.DirectoryId.ValueString()),
		Capacity: &workspacestypes.Capacity{
			DesiredUserSessions: data.DesiredUserSessions.ValueInt32Pointer(),
		},
	}

	if !data.RunningMode.IsNull() && !data.RunningMode.IsUnknown() {
		input.RunningMode = workspacestypes.PoolsRunningMode(data.RunningMode.ValueString())
	}

	if data.ApplicationSettings != nil {
		input.ApplicationSettings = buildApplicationSettingsRequest(data.ApplicationSettings)
	}

	if data.TimeoutSettings != nil {
		input.TimeoutSettings = buildTimeoutSettings(data.TimeoutSettings)
	}

	if tagList, err := tagsToList(ctx, data.Tags); err == nil {
		input.Tags = tagList
	}

	output, err := conn.CreateWorkspacesPool(ctx, input)

	if err != nil {
		resp.Diagnostics.AddError("Error creating WorkSpaces pool",
			fmt.Sprintf("Could not create WorkSpaces pool, unexpected error: %s", err))
		return
	}

	tflog.Trace(ctx, "created workspaces pool resource")

	pool := output.WorkspacesPool
	data.PoolId = types.StringValue(aws.ToString(pool.PoolId))
	data.PoolArn = types.StringValue(aws.ToString(pool.PoolArn))
	data.State = types.StringValue(string(pool.State))
	data.RunningMode = types.StringValue(string(pool.RunningMode))

	if pool.ApplicationSettings != nil {
		data.ApplicationSettings = flattenApplicationSettings(pool.ApplicationSettings)
	}

	if tags, err := readResourceTags(ctx, conn, data.PoolId.ValueString()); err == nil {
		data.Tags = tags
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *WorkspacesPoolResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data WorkspacesPoolResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := workspaces.NewFromConfig(r.config)

	output, err := conn.DescribeWorkspacesPools(ctx, &workspaces.DescribeWorkspacesPoolsInput{
		PoolIds: []string{data.PoolId.ValueString()},
	})

	if err != nil {
		var notFound *workspacestypes.ResourceNotFoundException
		if errors.As(err, &notFound) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading WorkSpaces pool",
			fmt.Sprintf("Could not read WorkSpaces pool %s, unexpected error: %s", data.PoolId.ValueString(), err))
		return
	}

	if len(output.WorkspacesPools) == 0 {
		resp.State.RemoveResource(ctx)
		return
	}

	pool := output.WorkspacesPools[0]

	if pool.State == workspacestypes.WorkspacesPoolStateDeleting {
		resp.State.RemoveResource(ctx)
		return
	}

	data.PoolId = types.StringValue(aws.ToString(pool.PoolId))
	data.PoolArn = types.StringValue(aws.ToString(pool.PoolArn))
	data.PoolName = types.StringValue(aws.ToString(pool.PoolName))
	data.Description = types.StringValue(aws.ToString(pool.Description))
	data.BundleId = types.StringValue(aws.ToString(pool.BundleId))
	data.DirectoryId = types.StringValue(aws.ToString(pool.DirectoryId))
	data.RunningMode = types.StringValue(string(pool.RunningMode))
	data.State = types.StringValue(string(pool.State))

	if pool.CapacityStatus != nil {
		data.DesiredUserSessions = types.Int32Value(aws.ToInt32(pool.CapacityStatus.DesiredUserSessions))
	}

	if pool.ApplicationSettings != nil {
		data.ApplicationSettings = flattenApplicationSettings(pool.ApplicationSettings)
	} else {
		data.ApplicationSettings = nil
	}

	if pool.TimeoutSettings != nil {
		data.TimeoutSettings = flattenTimeoutSettings(pool.TimeoutSettings)
	} else {
		data.TimeoutSettings = nil
	}

	if tags, err := readResourceTags(ctx, conn, data.PoolId.ValueString()); err == nil {
		data.Tags = tags
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *WorkspacesPoolResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state WorkspacesPoolResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := workspaces.NewFromConfig(r.config)

	input := &workspaces.UpdateWorkspacesPoolInput{
		PoolId:      aws.String(state.PoolId.ValueString()),
		Description: aws.String(plan.Description.ValueString()),
		BundleId:    aws.String(plan.BundleId.ValueString()),
		DirectoryId: aws.String(plan.DirectoryId.ValueString()),
		Capacity: &workspacestypes.Capacity{
			DesiredUserSessions: plan.DesiredUserSessions.ValueInt32Pointer(),
		},
	}

	if !plan.RunningMode.IsNull() && !plan.RunningMode.IsUnknown() {
		input.RunningMode = workspacestypes.PoolsRunningMode(plan.RunningMode.ValueString())
	}

	if plan.ApplicationSettings != nil {
		input.ApplicationSettings = buildApplicationSettingsRequest(plan.ApplicationSettings)
	}

	if plan.TimeoutSettings != nil {
		input.TimeoutSettings = buildTimeoutSettings(plan.TimeoutSettings)
	}

	output, err := conn.UpdateWorkspacesPool(ctx, input)

	if err != nil {
		resp.Diagnostics.AddError("Error updating WorkSpaces pool",
			fmt.Sprintf("Could not update WorkSpaces pool %s, unexpected error: %s", state.PoolId.ValueString(), err))
		return
	}

	pool := output.WorkspacesPool
	plan.PoolId = types.StringValue(aws.ToString(pool.PoolId))
	plan.PoolArn = types.StringValue(aws.ToString(pool.PoolArn))
	plan.State = types.StringValue(string(pool.State))
	plan.RunningMode = types.StringValue(string(pool.RunningMode))

	if pool.ApplicationSettings != nil {
		plan.ApplicationSettings = flattenApplicationSettings(pool.ApplicationSettings)
	}

	if err := updateResourceTags(ctx, conn, state.PoolId.ValueString(), state.Tags, plan.Tags); err != nil {
		resp.Diagnostics.AddError("Error updating WorkSpaces pool tags",
			fmt.Sprintf("Could not update tags for WorkSpaces pool %s, unexpected error: %s", state.PoolId.ValueString(), err))
		return
	}

	if tags, err := readResourceTags(ctx, conn, plan.PoolId.ValueString()); err == nil {
		plan.Tags = tags
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *WorkspacesPoolResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data WorkspacesPoolResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := workspaces.NewFromConfig(r.config)

	_, err := conn.TerminateWorkspacesPool(ctx, &workspaces.TerminateWorkspacesPoolInput{
		PoolId: aws.String(data.PoolId.ValueString()),
	})

	if err != nil {
		var notFound *workspacestypes.ResourceNotFoundException
		if errors.As(err, &notFound) {
			return
		}
		resp.Diagnostics.AddError("Error deleting WorkSpaces pool",
			fmt.Sprintf("Could not terminate WorkSpaces pool %s, unexpected error: %s", data.PoolId.ValueString(), err))
		return
	}
}

func (r *WorkspacesPoolResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("pool_id"), req, resp)
}

func buildApplicationSettingsRequest(m *PoolApplicationSettingsModel) *workspacestypes.ApplicationSettingsRequest {
	req := &workspacestypes.ApplicationSettingsRequest{
		Status: workspacestypes.ApplicationSettingsStatusEnum(m.Status.ValueString()),
	}
	if !m.SettingsGroup.IsNull() && !m.SettingsGroup.IsUnknown() {
		req.SettingsGroup = aws.String(m.SettingsGroup.ValueString())
	}
	return req
}

func buildTimeoutSettings(m *PoolTimeoutSettingsModel) *workspacestypes.TimeoutSettings {
	ts := &workspacestypes.TimeoutSettings{}
	if !m.DisconnectTimeoutInSeconds.IsNull() && !m.DisconnectTimeoutInSeconds.IsUnknown() {
		ts.DisconnectTimeoutInSeconds = m.DisconnectTimeoutInSeconds.ValueInt32Pointer()
	}
	if !m.IdleDisconnectTimeoutInSeconds.IsNull() && !m.IdleDisconnectTimeoutInSeconds.IsUnknown() {
		ts.IdleDisconnectTimeoutInSeconds = m.IdleDisconnectTimeoutInSeconds.ValueInt32Pointer()
	}
	if !m.MaxUserDurationInSeconds.IsNull() && !m.MaxUserDurationInSeconds.IsUnknown() {
		ts.MaxUserDurationInSeconds = m.MaxUserDurationInSeconds.ValueInt32Pointer()
	}
	return ts
}

func flattenApplicationSettings(r *workspacestypes.ApplicationSettingsResponse) *PoolApplicationSettingsModel {
	m := &PoolApplicationSettingsModel{
		Status: types.StringValue(string(r.Status)),
	}
	if r.SettingsGroup != nil {
		m.SettingsGroup = types.StringValue(*r.SettingsGroup)
	} else {
		m.SettingsGroup = types.StringNull()
	}
	return m
}

func flattenTimeoutSettings(t *workspacestypes.TimeoutSettings) *PoolTimeoutSettingsModel {
	m := &PoolTimeoutSettingsModel{}
	if t.DisconnectTimeoutInSeconds != nil {
		m.DisconnectTimeoutInSeconds = types.Int32Value(*t.DisconnectTimeoutInSeconds)
	} else {
		m.DisconnectTimeoutInSeconds = types.Int32Null()
	}
	if t.IdleDisconnectTimeoutInSeconds != nil {
		m.IdleDisconnectTimeoutInSeconds = types.Int32Value(*t.IdleDisconnectTimeoutInSeconds)
	} else {
		m.IdleDisconnectTimeoutInSeconds = types.Int32Null()
	}
	if t.MaxUserDurationInSeconds != nil {
		m.MaxUserDurationInSeconds = types.Int32Value(*t.MaxUserDurationInSeconds)
	} else {
		m.MaxUserDurationInSeconds = types.Int32Null()
	}
	return m
}
