// Generated by Claude (claude.ai) | Date: 2026-04-17 | Model: claude-sonnet-4-6
// Re-generation prompt: see Workspaces.ai in project root

package provider

import (
	"context"
	"errors"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/workspaces"
	workspacestypes "github.com/aws/aws-sdk-go-v2/service/workspaces/types"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var _ resource.Resource = &WorkspacesPoolRunningResource{}
var _ resource.ResourceWithImportState = &WorkspacesPoolRunningResource{}

func NewWorkspacesPoolRunningResource() resource.Resource {
	return &WorkspacesPoolRunningResource{}
}

type WorkspacesPoolRunningResource struct {
	config aws.Config
}

type WorkspacesPoolRunningResourceModel struct {
	PoolId types.String `tfsdk:"pool_id"`
	State  types.String `tfsdk:"state"`
}

func (r *WorkspacesPoolRunningResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_workspaces_pool_running"
}

func (r *WorkspacesPoolRunningResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages the running state of an existing WorkSpaces pool. " +
			"Creating this resource starts the pool via StartWorkspacesPool; " +
			"destroying it stops the pool via StopWorkspacesPool.",

		Attributes: map[string]schema.Attribute{
			"pool_id": schema.StringAttribute{
				Required:    true,
				Description: "The identifier of the WorkSpaces pool to start.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"state": schema.StringAttribute{
				Computed:    true,
				Description: "The current state of the pool (RUNNING, STARTING, UPDATING, etc.).",
			},
		},
	}
}

func (r *WorkspacesPoolRunningResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	config, ok := req.ProviderData.(aws.Config)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *aws.Config, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.config = config
}

func (r *WorkspacesPoolRunningResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data WorkspacesPoolRunningResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := workspaces.NewFromConfig(r.config)

	_, err := conn.StartWorkspacesPool(ctx, &workspaces.StartWorkspacesPoolInput{
		PoolId: aws.String(data.PoolId.ValueString()),
	})

	if err != nil {
		var invalidState *workspacestypes.InvalidResourceStateException
		if errors.As(err, &invalidState) {
			// Pool may already be running; proceed and let Read refresh the state.
			tflog.Warn(ctx, fmt.Sprintf("WorkSpaces pool %s may already be running: %s", data.PoolId.ValueString(), err))
		} else {
			resp.Diagnostics.AddError("Error starting WorkSpaces pool",
				fmt.Sprintf("Could not start WorkSpaces pool %s, unexpected error: %s", data.PoolId.ValueString(), err))
			return
		}
	}

	tflog.Trace(ctx, "started workspaces pool")

	data.State = types.StringValue("STARTING")

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *WorkspacesPoolRunningResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data WorkspacesPoolRunningResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := workspaces.NewFromConfig(r.config)

	output, err := conn.DescribeWorkspacesPools(ctx, &workspaces.DescribeWorkspacesPoolsInput{
		PoolIds: []string{data.PoolId.ValueString()},
	})

	if err != nil {
		var notFound *workspacestypes.ResourceNotFoundException
		if errors.As(err, &notFound) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading WorkSpaces pool state",
			fmt.Sprintf("Could not read WorkSpaces pool %s, unexpected error: %s", data.PoolId.ValueString(), err))
		return
	}

	if len(output.WorkspacesPools) == 0 {
		resp.State.RemoveResource(ctx)
		return
	}

	state := output.WorkspacesPools[0].State

	// Pool is considered "not running" when stopped, stopping, or being deleted.
	if state == workspacestypes.WorkspacesPoolStateStopped ||
		state == workspacestypes.WorkspacesPoolStateStopping ||
		state == workspacestypes.WorkspacesPoolStateDeleting {
		resp.State.RemoveResource(ctx)
		return
	}

	data.State = types.StringValue(string(state))

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *WorkspacesPoolRunningResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// pool_id uses RequiresReplace; Update is never called.
}

func (r *WorkspacesPoolRunningResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data WorkspacesPoolRunningResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := workspaces.NewFromConfig(r.config)

	_, err := conn.StopWorkspacesPool(ctx, &workspaces.StopWorkspacesPoolInput{
		PoolId: aws.String(data.PoolId.ValueString()),
	})

	if err != nil {
		var notFound *workspacestypes.ResourceNotFoundException
		if errors.As(err, &notFound) {
			return
		}
		var invalidState *workspacestypes.InvalidResourceStateException
		if errors.As(err, &invalidState) {
			// Pool may already be stopped.
			tflog.Warn(ctx, fmt.Sprintf("WorkSpaces pool %s may already be stopped: %s", data.PoolId.ValueString(), err))
			return
		}
		resp.Diagnostics.AddError("Error stopping WorkSpaces pool",
			fmt.Sprintf("Could not stop WorkSpaces pool %s, unexpected error: %s", data.PoolId.ValueString(), err))
		return
	}
}

func (r *WorkspacesPoolRunningResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("pool_id"), req, resp)
}
