// Generated by Claude (claude.ai) | Date: 2026-04-17 | Model: claude-sonnet-4-6
// Re-generation prompt: see Workspaces.ai in project root

package provider

import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/workspaces"
	workspacestypes "github.com/aws/aws-sdk-go-v2/service/workspaces/types"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// readResourceTags fetches tags for a WorkSpaces resource and returns them as a types.Map.
func readResourceTags(ctx context.Context, conn *workspaces.Client, resourceId string) (types.Map, error) {
	output, err := conn.DescribeTags(ctx, &workspaces.DescribeTagsInput{
		ResourceId: aws.String(resourceId),
	})
	if err != nil {
		return types.MapNull(types.StringType), err
	}

	tagMap := make(map[string]string, len(output.TagList))
	for _, tag := range output.TagList {
		tagMap[aws.ToString(tag.Key)] = aws.ToString(tag.Value)
	}

	result, diags := types.MapValueFrom(ctx, types.StringType, tagMap)
	if diags.HasError() {
		return types.MapNull(types.StringType), fmt.Errorf("error converting tags to map")
	}
	return result, nil
}

// updateResourceTags diffs old vs new tags and calls DeleteTags / CreateTags as needed.
func updateResourceTags(ctx context.Context, conn *workspaces.Client, resourceId string, oldTags, newTags types.Map) error {
	var oldTagMap, newTagMap map[string]string

	if !oldTags.IsNull() && !oldTags.IsUnknown() {
		oldTags.ElementsAs(ctx, &oldTagMap, false)
	}
	if !newTags.IsNull() && !newTags.IsUnknown() {
		newTags.ElementsAs(ctx, &newTagMap, false)
	}

	var keysToDelete []string
	for k := range oldTagMap {
		if _, exists := newTagMap[k]; !exists {
			keysToDelete = append(keysToDelete, k)
		}
	}

	if len(keysToDelete) > 0 {
		if _, err := conn.DeleteTags(ctx, &workspaces.DeleteTagsInput{
			ResourceId: aws.String(resourceId),
			TagKeys:    keysToDelete,
		}); err != nil {
			return err
		}
	}

	if len(newTagMap) > 0 {
		tags := make([]workspacestypes.Tag, 0, len(newTagMap))
		for k, v := range newTagMap {
			k, v := k, v
			tags = append(tags, workspacestypes.Tag{Key: aws.String(k), Value: aws.String(v)})
		}
		if _, err := conn.CreateTags(ctx, &workspaces.CreateTagsInput{
			ResourceId: aws.String(resourceId),
			Tags:       tags,
		}); err != nil {
			return err
		}
	}

	return nil
}

// tagsToList converts a types.Map of tags to the SDK slice used in Create inputs.
func tagsToList(ctx context.Context, tags types.Map) ([]workspacestypes.Tag, error) {
	if tags.IsNull() || tags.IsUnknown() {
		return nil, nil
	}

	var tagMap map[string]string
	if diags := tags.ElementsAs(ctx, &tagMap, false); diags.HasError() {
		return nil, fmt.Errorf("error reading tags")
	}

	result := make([]workspacestypes.Tag, 0, len(tagMap))
	for k, v := range tagMap {
		k, v := k, v
		result = append(result, workspacestypes.Tag{Key: aws.String(k), Value: aws.String(v)})
	}
	return result, nil
}
