// Generated by Claude (claude.ai) | Date: 2026-04-17 | Model: claude-sonnet-4-6
// Re-generation prompt: see Workspaces.ai in project root

package provider

import (
	"context"
	"errors"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/workspaces"
	workspacestypes "github.com/aws/aws-sdk-go-v2/service/workspaces/types"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var _ resource.Resource = &WorkspacesBundleResource{}
var _ resource.ResourceWithImportState = &WorkspacesBundleResource{}

func NewWorkspacesBundleResource() resource.Resource {
	return &WorkspacesBundleResource{}
}

type WorkspacesBundleResource struct {
	config aws.Config
}

type WorkspacesBundleResourceModel struct {
	BundleId            types.String `tfsdk:"bundle_id"`
	BundleName          types.String `tfsdk:"bundle_name"`
	BundleDescription   types.String `tfsdk:"bundle_description"`
	ImageId             types.String `tfsdk:"image_id"`
	ComputeType         types.String `tfsdk:"compute_type"`
	UserStorageCapacity types.String `tfsdk:"user_storage_capacity"`
	RootStorageCapacity types.String `tfsdk:"root_storage_capacity"`
	Owner               types.String `tfsdk:"owner"`
	State               types.String `tfsdk:"state"`
}

func (r *WorkspacesBundleResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_workspaces_bundle"
}

func (r *WorkspacesBundleResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Creates and manages a custom WorkSpaces bundle via CreateWorkspaceBundle. " +
			"The bundle image can be updated in-place via UpdateWorkspaceBundle.",

		Attributes: map[string]schema.Attribute{
			"bundle_id": schema.StringAttribute{
				Computed:    true,
				Description: "The identifier of the bundle.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"bundle_name": schema.StringAttribute{
				Required:    true,
				Description: "The name of the bundle.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"bundle_description": schema.StringAttribute{
				Required:    true,
				Description: "The description of the bundle.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"image_id": schema.StringAttribute{
				Required:    true,
				Description: "The identifier of the image to use for the bundle. Can be updated in-place via UpdateWorkspaceBundle.",
			},
			"compute_type": schema.StringAttribute{
				Required:    true,
				Description: "The compute type for the bundle.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.OneOf(
						"VALUE", "STANDARD", "PERFORMANCE", "POWER", "GRAPHICS", "POWERPRO",
						"GENERALPURPOSE_4XLARGE", "GENERALPURPOSE_8XLARGE",
						"GRAPHICSPRO", "GRAPHICS_G4DN", "GRAPHICSPRO_G4DN",
						"GRAPHICS_G6_XLARGE", "GRAPHICS_G6_2XLARGE", "GRAPHICS_G6_4XLARGE",
						"GRAPHICS_G6_8XLARGE", "GRAPHICS_G6_16XLARGE",
						"GRAPHICS_GR6_4XLARGE", "GRAPHICS_GR6_8XLARGE",
						"GRAPHICS_G6F_LARGE", "GRAPHICS_G6F_XLARGE", "GRAPHICS_G6F_2XLARGE",
						"GRAPHICS_G6F_4XLARGE", "GRAPHICS_GR6F_4XLARGE",
					),
				},
			},
			"user_storage_capacity": schema.StringAttribute{
				Required:    true,
				Description: "The size of the user storage volume in GB.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"root_storage_capacity": schema.StringAttribute{
				Optional:    true,
				Description: "The size of the root storage volume in GB.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"owner": schema.StringAttribute{
				Computed:    true,
				Description: "The owner of the bundle.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"state": schema.StringAttribute{
				Computed:    true,
				Description: "The state of the bundle (AVAILABLE, PENDING, ERROR).",
			},
		},
	}
}

func (r *WorkspacesBundleResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	config, ok := req.ProviderData.(aws.Config)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *aws.Config, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.config = config
}

func (r *WorkspacesBundleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data WorkspacesBundleResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := workspaces.NewFromConfig(r.config)

	input := &workspaces.CreateWorkspaceBundleInput{
		BundleName:        aws.String(data.BundleName.ValueString()),
		BundleDescription: aws.String(data.BundleDescription.ValueString()),
		ImageId:           aws.String(data.ImageId.ValueString()),
		ComputeType: &workspacestypes.ComputeType{
			Name: workspacestypes.Compute(data.ComputeType.ValueString()),
		},
		UserStorage: &workspacestypes.UserStorage{
			Capacity: aws.String(data.UserStorageCapacity.ValueString()),
		},
	}

	if !data.RootStorageCapacity.IsNull() && !data.RootStorageCapacity.IsUnknown() {
		input.RootStorage = &workspacestypes.RootStorage{
			Capacity: aws.String(data.RootStorageCapacity.ValueString()),
		}
	}

	output, err := conn.CreateWorkspaceBundle(ctx, input)

	if err != nil {
		resp.Diagnostics.AddError("Error creating WorkSpaces bundle",
			fmt.Sprintf("Could not create WorkSpaces bundle, unexpected error: %s", err))
		return
	}

	tflog.Trace(ctx, "created workspaces bundle resource")

	bundle := output.WorkspaceBundle
	data.BundleId = types.StringValue(aws.ToString(bundle.BundleId))
	data.Owner = types.StringValue(aws.ToString(bundle.Owner))
	data.State = types.StringValue(string(bundle.State))

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *WorkspacesBundleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data WorkspacesBundleResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := workspaces.NewFromConfig(r.config)

	output, err := conn.DescribeWorkspaceBundles(ctx, &workspaces.DescribeWorkspaceBundlesInput{
		BundleIds: []string{data.BundleId.ValueString()},
	})

	if err != nil {
		var notFound *workspacestypes.ResourceNotFoundException
		if errors.As(err, &notFound) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading WorkSpaces bundle",
			fmt.Sprintf("Could not read WorkSpaces bundle %s, unexpected error: %s", data.BundleId.ValueString(), err))
		return
	}

	if len(output.Bundles) == 0 {
		resp.State.RemoveResource(ctx)
		return
	}

	bundle := output.Bundles[0]
	data.BundleId = types.StringValue(aws.ToString(bundle.BundleId))
	data.BundleName = types.StringValue(aws.ToString(bundle.Name))
	data.BundleDescription = types.StringValue(aws.ToString(bundle.Description))
	data.ImageId = types.StringValue(aws.ToString(bundle.ImageId))
	data.Owner = types.StringValue(aws.ToString(bundle.Owner))
	data.State = types.StringValue(string(bundle.State))

	if bundle.ComputeType != nil {
		data.ComputeType = types.StringValue(string(bundle.ComputeType.Name))
	}

	if bundle.UserStorage != nil {
		data.UserStorageCapacity = types.StringValue(aws.ToString(bundle.UserStorage.Capacity))
	}

	if bundle.RootStorage != nil {
		data.RootStorageCapacity = types.StringValue(aws.ToString(bundle.RootStorage.Capacity))
	} else {
		data.RootStorageCapacity = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *WorkspacesBundleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data WorkspacesBundleResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := workspaces.NewFromConfig(r.config)

	_, err := conn.UpdateWorkspaceBundle(ctx, &workspaces.UpdateWorkspaceBundleInput{
		BundleId: aws.String(data.BundleId.ValueString()),
		ImageId:  aws.String(data.ImageId.ValueString()),
	})

	if err != nil {
		resp.Diagnostics.AddError("Error updating WorkSpaces bundle",
			fmt.Sprintf("Could not update WorkSpaces bundle %s, unexpected error: %s", data.BundleId.ValueString(), err))
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *WorkspacesBundleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data WorkspacesBundleResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := workspaces.NewFromConfig(r.config)

	_, err := conn.DeleteWorkspaceBundle(ctx, &workspaces.DeleteWorkspaceBundleInput{
		BundleId: aws.String(data.BundleId.ValueString()),
	})

	if err != nil {
		var notFound *workspacestypes.ResourceNotFoundException
		if errors.As(err, &notFound) {
			return
		}
		resp.Diagnostics.AddError("Error deleting WorkSpaces bundle",
			fmt.Sprintf("Could not delete WorkSpaces bundle %s, unexpected error: %s", data.BundleId.ValueString(), err))
		return
	}
}

func (r *WorkspacesBundleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("bundle_id"), req, resp)
}
