// Generated by Claude (claude.ai) | Date: 2026-04-17 | Model: claude-sonnet-4-6
// Re-generation prompt: see Workspaces.ai in project root

package provider

import (
	"context"
	"errors"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/workspaces"
	workspacestypes "github.com/aws/aws-sdk-go-v2/service/workspaces/types"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var _ resource.Resource = &WorkspacesStreamingPropertiesResource{}
var _ resource.ResourceWithImportState = &WorkspacesStreamingPropertiesResource{}

func NewWorkspacesStreamingPropertiesResource() resource.Resource {
	return &WorkspacesStreamingPropertiesResource{}
}

type WorkspacesStreamingPropertiesResource struct {
	config aws.Config
}

type StorageConnectorModel struct {
	ConnectorType types.String `tfsdk:"connector_type"`
	Status        types.String `tfsdk:"status"`
}

type UserSettingModel struct {
	Action        types.String `tfsdk:"action"`
	Permission    types.String `tfsdk:"permission"`
	MaximumLength types.Int32  `tfsdk:"maximum_length"`
}

type WorkspacesStreamingPropertiesResourceModel struct {
	DirectoryId                          types.String            `tfsdk:"directory_id"`
	StorageConnectors                    []StorageConnectorModel `tfsdk:"storage_connectors"`
	StreamingExperiencePreferredProtocol types.String            `tfsdk:"streaming_experience_preferred_protocol"`
	UserSettings                         []UserSettingModel      `tfsdk:"user_settings"`
}

func (r *WorkspacesStreamingPropertiesResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_workspaces_streaming_properties"
}

func (r *WorkspacesStreamingPropertiesResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages streaming properties for a WorkSpaces directory via ModifyStreamingProperties. " +
			"Destroying this resource removes it from Terraform state but does not reset the streaming properties in AWS.",

		Attributes: map[string]schema.Attribute{
			"directory_id": schema.StringAttribute{
				Required:    true,
				Description: "The identifier of the WorkSpaces directory.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"streaming_experience_preferred_protocol": schema.StringAttribute{
				Optional:    true,
				Description: "The preferred streaming protocol. Valid values: TCP, UDP.",
				Validators: []validator.String{
					stringvalidator.OneOf("TCP", "UDP"),
				},
			},
			"storage_connectors": schema.ListNestedAttribute{
				Optional:    true,
				Description: "The storage connector settings for the WorkSpaces directory.",
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"connector_type": schema.StringAttribute{
							Required:    true,
							Description: "The type of storage connector. Valid values: HOME_FOLDER.",
							Validators: []validator.String{
								stringvalidator.OneOf("HOME_FOLDER"),
							},
						},
						"status": schema.StringAttribute{
							Required:    true,
							Description: "Whether the storage connector is enabled. Valid values: ENABLED, DISABLED.",
							Validators: []validator.String{
								stringvalidator.OneOf("ENABLED", "DISABLED"),
							},
						},
					},
				},
			},
			"user_settings": schema.ListNestedAttribute{
				Optional:    true,
				Description: "The user settings for the WorkSpaces directory.",
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"action": schema.StringAttribute{
							Required:    true,
							Description: "The user setting action. Valid values: CLIPBOARD_COPY_FROM_LOCAL_DEVICE, CLIPBOARD_COPY_TO_LOCAL_DEVICE, PRINTING_TO_LOCAL_DEVICE, SMART_CARD.",
							Validators: []validator.String{
								stringvalidator.OneOf(
									"CLIPBOARD_COPY_FROM_LOCAL_DEVICE",
									"CLIPBOARD_COPY_TO_LOCAL_DEVICE",
									"PRINTING_TO_LOCAL_DEVICE",
									"SMART_CARD",
								),
							},
						},
						"permission": schema.StringAttribute{
							Required:    true,
							Description: "Whether the action is enabled. Valid values: ENABLED, DISABLED.",
							Validators: []validator.String{
								stringvalidator.OneOf("ENABLED", "DISABLED"),
							},
						},
						"maximum_length": schema.Int32Attribute{
							Optional:    true,
							Description: "The maximum character length for the user setting.",
						},
					},
				},
			},
		},
	}
}

func (r *WorkspacesStreamingPropertiesResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	config, ok := req.ProviderData.(aws.Config)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *aws.Config, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.config = config
}

func (r *WorkspacesStreamingPropertiesResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data WorkspacesStreamingPropertiesResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := workspaces.NewFromConfig(r.config)

	if err := modifyStreamingProperties(ctx, data, conn); err != nil {
		resp.Diagnostics.AddError("Error creating WorkSpaces Streaming Properties", fmt.Sprintf("Could not set WorkSpaces Streaming Properties, unexpected error: %s", err))
		return
	}

	tflog.Trace(ctx, "created workspaces streaming properties resource")

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *WorkspacesStreamingPropertiesResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data WorkspacesStreamingPropertiesResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := workspaces.NewFromConfig(r.config)

	output, err := conn.DescribeWorkspaceDirectories(ctx, &workspaces.DescribeWorkspaceDirectoriesInput{
		DirectoryIds: []string{data.DirectoryId.ValueString()},
	})

	if err != nil {
		var notFound *workspacestypes.ResourceNotFoundException
		if errors.As(err, &notFound) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading WorkSpaces Streaming Properties",
			fmt.Sprintf("Could not read WorkSpaces directory %s, unexpected error: %s", data.DirectoryId.ValueString(), err))
		return
	}

	if len(output.Directories) == 0 || output.Directories[0].StreamingProperties == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	sp := output.Directories[0].StreamingProperties

	var connectors []StorageConnectorModel
	for _, c := range sp.StorageConnectors {
		connectors = append(connectors, StorageConnectorModel{
			ConnectorType: types.StringValue(string(c.ConnectorType)),
			Status:        types.StringValue(string(c.Status)),
		})
	}
	data.StorageConnectors = connectors

	var userSettings []UserSettingModel
	for _, u := range sp.UserSettings {
		us := UserSettingModel{
			Action:     types.StringValue(string(u.Action)),
			Permission: types.StringValue(string(u.Permission)),
		}
		if u.MaximumLength != nil {
			us.MaximumLength = types.Int32Value(*u.MaximumLength)
		} else {
			us.MaximumLength = types.Int32Null()
		}
		userSettings = append(userSettings, us)
	}
	data.UserSettings = userSettings

	if sp.StreamingExperiencePreferredProtocol != "" {
		data.StreamingExperiencePreferredProtocol = types.StringValue(string(sp.StreamingExperiencePreferredProtocol))
	} else {
		data.StreamingExperiencePreferredProtocol = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *WorkspacesStreamingPropertiesResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data WorkspacesStreamingPropertiesResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := workspaces.NewFromConfig(r.config)

	if err := modifyStreamingProperties(ctx, data, conn); err != nil {
		resp.Diagnostics.AddError("Error updating WorkSpaces Streaming Properties",
			fmt.Sprintf("Could not update WorkSpaces Streaming Properties, unexpected error: %s", err))
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *WorkspacesStreamingPropertiesResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// ModifyStreamingProperties has no corresponding delete API.
	// Removing this resource from Terraform state leaves streaming properties unchanged in AWS.
}

func (r *WorkspacesStreamingPropertiesResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("directory_id"), req, resp)
}

func modifyStreamingProperties(ctx context.Context, data WorkspacesStreamingPropertiesResourceModel, conn *workspaces.Client) error {
	sp := &workspacestypes.StreamingProperties{}

	if !data.StreamingExperiencePreferredProtocol.IsNull() && !data.StreamingExperiencePreferredProtocol.IsUnknown() {
		sp.StreamingExperiencePreferredProtocol = workspacestypes.StreamingExperiencePreferredProtocolEnum(data.StreamingExperiencePreferredProtocol.ValueString())
	}

	for _, c := range data.StorageConnectors {
		sp.StorageConnectors = append(sp.StorageConnectors, workspacestypes.StorageConnector{
			ConnectorType: workspacestypes.StorageConnectorTypeEnum(c.ConnectorType.ValueString()),
			Status:        workspacestypes.StorageConnectorStatusEnum(c.Status.ValueString()),
		})
	}

	for _, u := range data.UserSettings {
		us := workspacestypes.UserSetting{
			Action:     workspacestypes.UserSettingActionEnum(u.Action.ValueString()),
			Permission: workspacestypes.UserSettingPermissionEnum(u.Permission.ValueString()),
		}
		if !u.MaximumLength.IsNull() && !u.MaximumLength.IsUnknown() {
			us.MaximumLength = u.MaximumLength.ValueInt32Pointer()
		}
		sp.UserSettings = append(sp.UserSettings, us)
	}

	_, err := conn.ModifyStreamingProperties(ctx, &workspaces.ModifyStreamingPropertiesInput{
		ResourceId:          aws.String(data.DirectoryId.ValueString()),
		StreamingProperties: sp,
	})

	return err
}
